### PR TITLE
Ignore semicolon following a macro expansion in expression context

### LINKED ISSUE #2273: Macro Expansion Producing Expression with Semicolon
I tried this code:

```rust
macro_rules! mac {
    () => {return 1;}
}

pub fn foo() -> i32 {
    mac!()
}
```

I expected to see this happen:
```
warning: trailing semicolon in macro used in expression position
 --> src/lib.rs:2:20
  |
2 |     () => {return 1;}
  |                    ^
...
6 |     mac!()
  |     ------ in this macro invocation
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, [see issue #79813 <https://github.com/rust-lang/rust/issues/79813>](https://github.com/rust-lang/rust/issues/79813)
  = note: macro invocations at the end of a block are treated as expressions
  = note: to ignore the value produced by the macro, add a semicolon after the invocation of `mac`
  = note: `#[warn(semicolon_in_expressions_from_macros)]` on by default
  = note: this warning originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Instead, this happened:
```
test.rs:2:20: error: tokens here and after are unparsed
    2 |     () => {return 1;}
      |                    ^
```

### Meta

- git sha: ```1b322540fa0fce561cf86e371dd7f304f1343511```

### PR DESCRIPTION
**Pull request by powerboat9**
Fixes #2273

### CODE REVIEW

**Comment by powerboat9** [comment]
Looks like I accidentally duplicated some of #2282 -- converting this into a draft for reexamination after #2282 is merged.

**Comment by powerboat9** [comment]
It looks like I actually didn't duplicate #2282, as issue #2273 is still present on master.

File: gcc/rust/expand/rust-macro-expand.cc [hunk 1]
```diff
@@ -875,6 +875,15 @@ transcribe_expression (Parser<MacroInvocLexer> &parser)
...
 
+  // FIXME: make this an error for some edititons
+  if (parser.peek_current_token ()->get_id () == SEMICOLON)
+    {
+      rust_warning_at (
+	parser.peek_current_token ()->get_locus (), 0,
+	"trailing semicolon in macro used in expression context");
+      parser.skip_token ();
+    }
+
```
Comment (matthewjasper) [inline gcc/rust/expand/rust-macro-expand.cc:886]: The FIXME at line 1050 in this file can be removed.

Comment (powerboat9) [reply gcc/rust/expand/rust-macro-expand.cc:886]: But this will have to be changed to an error in future editions

**Review by CohenArthur — APPROVED** [review]
Looks good :) nice work

File: gcc/rust/expand/rust-macro-expand.cc (hunk 1 above)
Comment (CohenArthur) [reply gcc/rust/expand/rust-macro-expand.cc:886]: We'll keep the existing code, but emit an error or a warning depending on which `-frust-edition` option has been passed. Both behaviors need to stay. So I agree that the comment can be removed, or it can be kept for now since we'll need to touch that part of the code again

**Review by philberty — APPROVED** [review]
LGTM
