### PR TITLE
Fix casting error behind generics [WIP]

### LINKED ISSUE #1897: Bad cast error when behind generics
I tried this code: https://godbolt.org/z/MWbn8587K

```rust
fn test<T>(a:T) -> T {
    a
}

fn main() {
    let a:i32 = test(123 as i32) as i32;
}
```

I expected to see this happen: compile without error

Instead, this happened:

```
<source>:6:17: error: invalid cast 'i32' to 'i32' [E0054]
    6 |     let a:i32 = test(123 as i32) as i32;
      |                 ^~~~                ~~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

### PR DESCRIPTION
**Pull request by goar5670**
Fixes #1897 

gcc/rust/ChangeLog:
```
* typecheck/rust-casts.cc (TypeCastRules::cast_rules): Perform destructure on `from` type
```

gcc/testsuite/ChangeLog:
```
* rust/compile/cast_generics.rs: New test.
```

### CODE REVIEW

File: gcc/rust/typecheck/rust-casts.cc [hunk 1]
```diff
@@ -63,11 +63,11 @@ TypeCastRules::cast_rules ()
 	      from.get_ty ()->debug_str ().c_str (),
 	      to.get_ty ()->debug_str ().c_str ());
 
-  switch (from.get_ty ()->get_kind ())
+  switch (from.get_ty ()->destructure ()->get_kind ())
```
Comment (philberty) [inline gcc/rust/typecheck/rust-casts.cc:66]: I think it would be better to do something like the unify code over in rust-unify.cc UnifyRules::go

```
TyTy::BaseType *
UnifyRules::go ()
{
  TyTy::BaseType *ltype = lhs.get_ty ();
  TyTy::BaseType *rtype = rhs.get_ty ();

  ltype = lhs.get_ty ()->destructure ();
  rtype = rhs.get_ty ()->destructure ();
```

So that you only need to call it once and it doesn't get lost.

**Review by philberty — CHANGES_REQUESTED** [review]
You found the right fix I think a small tweak to call restructure once would be ideal here. I also think this should be squashed into 1 commit.

Otherwise great job.

**Comment by philberty** [comment]
Just so you know i would really like to merge this soon because I want to work on https://github.com/Rust-GCC/gccrs/issues/1898 tomorrow

**Comment by philberty** [comment]
If your having problems with the git commit format checker you can run the checker locally via: 

```
python3 contrib/gcc-changelog/git_check_commit.py origin/master..HEAD
Checking ed45b943a1fee3310fea361c6e127f5a60ae6d22: OK
Checking 27c4590301a3da7d62d5b7e5a88cdbdc8de23070: OK
Checking 5c9a0e4a49f23f277652af6d1cc8173bc255ad44: OK
Checking d5397d90190d4a4d13c688815924b0a9439f3a98: OK
Checking 92d31693da5401291db6f667d9997a889bf0ea8a: OK
Checking 48c65d249e3fdabdac0947226f375cf911529c6b: OK
Checking 4ae86b6ce74474e65da436ab92bcd9b87ed1833b: OK
Checking fa9c51aa8d435b953c58f0ba2db3a339cd9c6f59: OK
Checking a44cf951951d6a0c747a18b3d7c71d1bb96134e6: OK
Checking b6a8e19529614610519ab97d1afa7e5cd214a2a9: OK
```

File: gcc/rust/typecheck/rust-casts.cc (hunk 1 above)
Comment (goar5670) [reply gcc/rust/typecheck/rust-casts.cc]: Edited it, please take another look.

**Review by philberty — APPROVED** [review]
LGTM good work
