### PR TITLE
[#2987] Patch ICE when deriving Clone and Copy

### LINKED ISSUE #2987: Cannot derive both `Clone` and `Copy` on an empty struct
I tried this code:

```rust
#[lang = "copy"]
trait Copy {}

#[lang = "clone"]
trait Clone {
    fn clone(&self) -> Self;
}

#[derive(Copy, Clone)]
struct Empty;
```

I expected to see this happen: no error.

Instead, this happened:

```
crab1: internal compiler error: in go, at rust/expand/rust-derive-clone.cc:106
0x23e9f13 Rust::AST::DeriveClone::go(Rust::AST::Item&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-derive-clone.cc:106
0x23e870c Rust::AST::DeriveVisitor::derive(Rust::AST::Item&, Rust::AST::Attribute const&, Rust::BuiltinMacro)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-derive.cc:37
0x23daaed Rust::builtin_derive_item(Rust::AST::Item&, Rust::AST::Attribute const&, Rust::BuiltinMacro)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:49
0x23da6cd Rust::ExpandVisitor::expand_inner_items(std::vector<std::unique_ptr<Rust::AST::Item, std::default_delete<Rust::AST::Item> >, std::allocator<std::unique_ptr<Rust::AST::Item, std::default_delete<Rust::AST::Item> > > >&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:192
0x23dbf80 Rust::ExpandVisitor::visit(Rust::AST::Crate&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:443
0x23d9ff0 Rust::ExpandVisitor::go(Rust::AST::Crate&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:42
0x22ec683 Rust::Session::expansion(Rust::AST::Crate&, Rust::Resolver2_0::NameResolutionContext&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:933
0x22eaf0f Rust::Session::compile_crate(char const*)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:604
0x22ea8b1 Rust::Session::handle_input_files(int, char const**)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:416
0x2144872 grs_langhook_parse_file()
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-lang.cc:165
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

if the order of `Clone` and `Copy` is switched, then this happens:

```
crab1: internal compiler error: in go, at rust/expand/rust-derive-copy.cc:34
0x23eb6a3 Rust::AST::DeriveCopy::go(Rust::AST::Item&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-derive-copy.cc:34
0x23e873f Rust::AST::DeriveVisitor::derive(Rust::AST::Item&, Rust::AST::Attribute const&, Rust::BuiltinMacro)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-derive.cc:39
0x23daaed Rust::builtin_derive_item(Rust::AST::Item&, Rust::AST::Attribute const&, Rust::BuiltinMacro)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:49
0x23da6cd Rust::ExpandVisitor::expand_inner_items(std::vector<std::unique_ptr<Rust::AST::Item, std::default_delete<Rust::AST::Item> >, std::allocator<std::unique_ptr<Rust::AST::Item, std::default_delete<Rust::AST::Item> > > >&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:192
0x23dbf80 Rust::ExpandVisitor::visit(Rust::AST::Crate&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:443
0x23d9ff0 Rust::ExpandVisitor::go(Rust::AST::Crate&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/expand/rust-expand-visitor.cc:42
0x22ec683 Rust::Session::expansion(Rust::AST::Crate&, Rust::Resolver2_0::NameResolutionContext&)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:933
0x22eaf0f Rust::Session::compile_crate(char const*)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:604
0x22ea8b1 Rust::Session::handle_input_files(int, char const**)
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:416
0x2144872 grs_langhook_parse_file()
	/home/kagounard/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-lang.cc:165
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

### Meta

8a7256676e5

### PR DESCRIPTION
**Pull request by liamnaddell**
```
gcc/rust/ChangeLog:
	* expand/rust-expand-visitor.cc: Fix ICE caused by unique_ptr UB and buggy iterator use

gcc/testsuite/ChangeLog:
	* rust/compile/issue-2987.rs: Add test for deriving Clone and Copy at the same time
```

Fixes #2987 

- \[x] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[x] Read contributing guidlines
- \[x] `make check-rust` passes locally
- \[x] Run `clang-format`
- \[x] Added any relevant test cases to `gcc/testsuite/rust/`

---

Fix an ICE caused by an improper use of iterators that prevented Clone and Copy from being applied to the same struct.

Fixes #2987

### CODE REVIEW

File: gcc/rust/expand/rust-expand-visitor.cc [hunk 1]
```diff
@@ -190,16 +190,17 @@ ExpandVisitor::expand_inner_items (
 		      if (maybe_builtin.has_value ())
 			{
 			  auto new_item
-			    = builtin_derive_item (*item, current,
+			    = builtin_derive_item (item, current,
 						   maybe_builtin.value ());
-			  // this inserts the derive *before* the item - is it a
-			  // problem?
```
Comment (liamnaddell) [inline gcc/rust/expand/rust-expand-visitor.cc:196]: I think this patch is a way of working around the issue

**Review by CohenArthur — APPROVED** [review]
nice, well done!! great work!

**Review by P-E-P — APPROVED** [review]
LGTM
