### PR TITLE
gccrs: Implement typecheck for zero-variant enums

### LINKED ISSUE #3530: Unsupported representation on zero-variant enum
### Summary

The compiler should complain about an unsupported representation on a zero-variant enum.

### Reproducer

I tried this code:

```rust
#[repr(i32)]
enum NightsWatch {}
```

### Does the code make use of any (1.49) nightly feature ?

- [ ] Nightly

### Godbolt link

https://godbolt.org/z/c9zbqfhYx

### Actual behavior

The code compiles even though it shouldn't.

### Expected behavior

I expected to see an error:
`error[E0084]: unsupported representation for zero-variant enum`

### GCC Version

f608c02

### PR DESCRIPTION
**Pull request by Polygonalr**
Fixes #3530

- \[x] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[x] Read contributing guidlines
- \[x] `make check-rust` passes locally
- \[x] Run `clang-format`
- \[x] Added any relevant test cases to `gcc/testsuite/rust/`

This quick fix is kind of an ugly one, since [parsing of `repr` types is not fully implemented yet](https://github.com/Rust-GCC/gccrs/blob/20c8539a23e0a0462e3763c3983ffb3ca9b7e709/gcc/rust/typecheck/rust-hir-type-check-base.cc#L301-L302). This merely adds a new `ReprKind` type similar to [Rust's `ReprFlags`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_abi/src/lib.rs#L81-L101).

I'm open to suggestions for improvements, or any tips on fully implementing the parsing `repr` types properly.

### CODE REVIEW

File: gcc/rust/typecheck/rust-hir-type-check-base.cc [hunk 1]
```diff
@@ -343,13 +343,27 @@ TypeCheckBase::parse_repr_options (const AST::AttrVec &attrs, location_t locus)
 	  // manually parsing the string "packed(2)" here.
 
 	  size_t oparen = inline_option.find ('(', 0);
-	  bool is_pack = false, is_align = false;
+	  bool is_pack = false, is_align = false, is_c = false,
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-base.cc:346]: split these boolean flags up instead of a single declaration

**Review by philberty — CHANGES_REQUESTED** [review]
Just minor style thing and add in another fix please.

File: gcc/rust/typecheck/rust-hir-type-check-base.cc [hunk 2]
```diff
@@ -369,9 +383,23 @@ TypeCheckBase::parse_repr_options (const AST::AttrVec &attrs, location_t locus)
...
+	      repr.repr_kind = TyTy::ADTType::ReprKind::ALIGN;
+	      repr.align = value;
+	    }
+	  else if (is_c)
+	    {
+	      repr.repr_kind = TyTy::ADTType::ReprKind::C;
+	    }
+	  else if (is_integer)
+	    {
+	      repr.repr_kind = TyTy::ADTType::ReprKind::INT;
```
[the remark this answers is not in the document]
Comment (Polygonalr) [reply gcc/rust/typecheck/rust-hir-type-check-base.cc:401]: Sure, will push the another commit in a bit.

File: gcc/rust/typecheck/rust-hir-type-check-base.cc [hunk 3]
```diff
@@ -298,7 +298,7 @@ TypeCheckBase::parse_repr_options (const AST::AttrVec &attrs, location_t locus)
   repr.pack = 0;
   repr.align = 0;
 
-  // FIXME handle repr types....
+  // FIXME handle non-integer repr types....
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-base.cc:301]: You can remove this FIXME and mention "enums default repr is  isize but we now check for other repr in the attibutes."

**Review by philberty — CHANGES_REQUESTED** [review]
just minor change to that comment then looks good to go
