### PR TITLE
rust: Add support for Clone and Copy derive on generic types

### LINKED ISSUE #3139: Ice on using clone
### Code

```rust
#![feature(lang_items)]

#[lang = "clone"]
trait Clone {
    fn clone(&self) -> Self;
}

#[lang = "sized"]
trait Sized {}

struct Abound {
    a: u32,
    b: u32,

}

#[derive(Clone)]
struct Be<T:Clone> {
    a: T,
    b: Abound,
}

impl Clone for u32 {
    fn clone(&self) -> Self {
        *self
    }
}

impl Clone for usize {
    fn clone(&self) -> Self {
        *self
    }
}

impl Clone for Abound {
    fn clone(&self) -> Self {
        return Abound { a: self.a.clone(), b: self.b.clone() };
    }
}

fn main() {
    let b: Be<usize> = Be {a:1,b:Abound { a:0,b:1 }};
    let _: Be<usize> = b.clone();
}
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

### Error output

```
<output>
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
derive_clone_generic.rs:17:3: error: generic item takes at least 1 type arguments but 0 were supplied [E0107]
   17 | #[derive(Clone)]
      |   ^~~~~~
   18 | struct Be<T:Clone> {
      |           ~
derive_clone_generic.rs:17:3: error: failed to resolve type arguments
derive_clone_generic.rs:17:3: note: failed to resolve lifetime
derive_clone_generic.rs:17:3: error: expected algebraic data type got: [<tyty::error>]
crab1: internal compiler error: in TyVar, at rust/typecheck/rust-tyty-util.cc:31
0x131f9ff Rust::TyTy::TyVar::TyVar(unsigned int)
	../../gccrs/gcc/rust/typecheck/rust-tyty-util.cc:31
0x138500b Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BorrowExpr&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:1400
0x11cdd87 Rust::HIR::BorrowExpr::accept_vis(Rust::HIR::HIRExpressionVisitor&)
	../../gccrs/gcc/rust/hir/tree/rust-hir.cc:3809
0x137f7af Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:42
0x13205d3 Rust::TyTy::TypeCheckCallExpr::visit(Rust::TyTy::FnType&)
	../../gccrs/gcc/rust/typecheck/rust-tyty-call.cc:143
0x1306db7 Rust::TyTy::FnType::accept_vis(Rust::TyTy::TyVisitor&)
	../../gccrs/gcc/rust/typecheck/rust-tyty.cc:1879
0x1387dff Rust::TyTy::TypeCheckCallExpr::go(Rust::TyTy::BaseType*, Rust::HIR::CallExpr&, Rust::TyTy::VariantDef&, Rust::Resolver::TypeCheckContext*)
	../../gccrs/gcc/rust/typecheck/rust-tyty-call.h:39
0x138037b Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::CallExpr&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:239
0x11d0867 Rust::HIR::CallExpr::accept_vis(Rust::HIR::HIRExpressionVisitor&)
	../../gccrs/gcc/rust/hir/tree/rust-hir.cc:4865
0x137f7af Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:42
0x1377f07 Rust::Resolver::TypeCheckStructExpr::visit(Rust::HIR::StructExprFieldIdentifierValue&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-struct.cc:287
0x1377487 Rust::Resolver::TypeCheckStructExpr::resolve(Rust::HIR::StructExprStructFields&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-struct.cc:110
0x13770c7 Rust::Resolver::TypeCheckStructExpr::Resolve(Rust::HIR::StructExprStructFields*)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-struct.cc:38
0x1383b4f Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::StructExprStructFields&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:1042
0x11d001f Rust::HIR::StructExprStructFields::accept_vis(Rust::HIR::HIRExpressionVisitor&)
	../../gccrs/gcc/rust/hir/tree/rust-hir.cc:4637
0x137f7af Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:42
0x1381ebb Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:612
0x11d0e5f Rust::HIR::BlockExpr::accept_vis(Rust::HIR::HIRExpressionVisitor&)
	../../gccrs/gcc/rust/hir/tree/rust-hir.cc:5027
0x137f7af Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.cc:42
0x138d727 Rust::Resolver::TypeCheckImplItem::visit(Rust::HIR::Function&)
	../../gccrs/gcc/rust/typecheck/rust-hir-type-check-implitem.cc:489
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
  ```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by philberty**
When we generate derivations for Copy and Clone we need to make sure the associated impl block sets up the generic parameters and arguments correctly. This patch introduces the framework to copy chunks of the AST because we need to make sure these new AST nodes have their own associated id, calling clone on the nodes will just confuse name-resolution and subsequent mappings.

Fixes #3139

gcc/rust/ChangeLog:

	* Make-lang.in: new objects
	* ast/rust-ast-builder.cc (Builder::generic_type_path_segment): new helper
	(Builder::single_generic_type_path): likewise
	(Builder::new_type): likewise
	(Builder::new_lifetime_param): likewise
	(Builder::new_type_param): likewise
	(Builder::new_lifetime): likewise
	(Builder::new_generic_args): likewise
	* ast/rust-ast-builder.h: new helper decls
	* ast/rust-ast.h: new const getters
	* ast/rust-path.h: likewise
	* ast/rust-type.h: likewise
	* expand/rust-derive-clone.cc (DeriveClone::clone_impl): take the types generics
	(DeriveClone::visit_tuple): likewise
	(DeriveClone::visit_struct): likewise
	(DeriveClone::visit_union): likewise
	* expand/rust-derive-clone.h: update header
	* expand/rust-derive-copy.cc (DeriveCopy::copy_impl): similarly take type generics
	(DeriveCopy::visit_struct): likewise
	(DeriveCopy::visit_tuple): likewise
	(DeriveCopy::visit_enum): likewise
	(DeriveCopy::visit_union): likewise
	* expand/rust-derive-copy.h: likewse
	* ast/rust-ast-builder-base.cc: New file.
	* ast/rust-ast-builder-base.h: New file.
	* ast/rust-ast-builder-type.cc: New file.
	* ast/rust-ast-builder-type.h: New file.

gcc/testsuite/ChangeLog:

	* rust/compile/issue-3139-1.rs: New test.
	* rust/compile/issue-3139-2.rs: New test.
	* rust/compile/issue-3139-3.rs: New test.

Thank you for making Rust GCC better!

### CODE REVIEW

File: gcc/rust/ast/rust-ast-builder-base.h [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+// along with GCC; see the file COPYING3.  If not see
+// <http://www.gnu.org/licenses/>.
+
+#include "rust-ast-visitor.h"
+
+namespace Rust {
+namespace AST {
+
+// base class to allow derivatives to overload as needed
+class ASTBuilderBase : public AST::ASTVisitor
```
Comment (P-E-P) [inline gcc/rust/ast/rust-ast-builder-base.h:25]: Unless you do need empty visit functions, it would be better to inherit from `AST::DefaultASTVisitor`. Multiple classes are already using this and it is less prone to errors:
- Nodes are almost always reachable
- You can use `AST::DefaultVisitor::visit(whatever_you_were_visiting)` from within your overload once you've implemented your behavior to automatically visit child nodes.

Comment (philberty) [reply gcc/rust/ast/rust-ast-builder-base.h:25]: sounds good

Comment (philberty) [reply gcc/rust/ast/rust-ast-builder-base.h]: just removed that visitor to use the default one

**Review by P-E-P — APPROVED** [review]

**Review by CohenArthur — COMMENTED** [review]
LGTM!
