### PR TITLE
gccrs: add uninit intrinsic

### LINKED ISSUE #1899: Support uninit intrinsic
I tried this code:

```rust
mod intrinsics {
    extern "rust-intrinsic" {
        pub fn uninit<T>() -> T;
    }
}

mod mem {
    pub unsafe fn uninitialized<T>() -> T {
        intrinsics::uninit()
    }
}

struct Foo(i32, i32);

fn main() {
    let a = unsafe { mem::uninitialized::<Foo>() };
}

```

I expected to see this happen: compile without error

Instead, this happened:

```
test.rs:9:9: error: unknown builtin intrinsic: uninit
    9 |         intrinsics::uninit()
      |         ^~~~~~~~~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible. 87e7c9dedacd4d12636e6c626aab14bcecf686f2

### PR DESCRIPTION
**Pull request by philberty**
Following an investigation from rustc and discussions on zulip the recommendation was that for uninit we memset to 0x01 which is less likely to be a null ptr but still an invalid reference.

Fixes #1899

### CODE REVIEW

File: gcc/rust/backend/rust-compile-intrinsic.cc [hunk 1]
```diff
@@ -882,5 +885,58 @@ unchecked_op_inner (Context *ctx, TyTy::FnType *fntype, tree_code op)
...
+  rust_assert (fntype->get_num_substitutions () == 1);
+  auto &param_mapping = fntype->get_substs ().at (0);
+  const TyTy::ParamType *param_tyty = param_mapping.get_param_ty ();
+  TyTy::BaseType *resolved_tyty = param_tyty->resolve ();
+  tree template_parameter_type
+    = TyTyResolveCompile::compile (ctx, resolved_tyty);
+
+  enter_intrinsic_block (ctx, fndecl);
+
+  // BUILTIN size_of FN BODY BEGIN
```
Comment (CohenArthur) [inline gcc/rust/backend/rust-compile-intrinsic.cc:910]:
```suggestion
  // BUILTIN uninit FN BODY BEGIN
```

File: gcc/rust/backend/rust-compile-intrinsic.cc [hunk 2]
```diff
@@ -882,5 +885,58 @@ unchecked_op_inner (Context *ctx, TyTy::FnType *fntype, tree_code op)
...
+  TREE_READONLY (memset_call) = 0;
+  TREE_SIDE_EFFECTS (memset_call) = 1;
+
+  ctx->add_statement (memset_call);
+
+  auto return_statement
+    = ctx->get_backend ()->return_statement (fndecl, {DECL_RESULT (fndecl)},
+					     Location ());
+  ctx->add_statement (return_statement);
+  // BUILTIN size_of FN BODY END
```
Comment (CohenArthur) [inline gcc/rust/backend/rust-compile-intrinsic.cc:934]:
```suggestion
  // BUILTIN uninit FN BODY END
```

**Review by CohenArthur — APPROVED** [review]
Looks good!

**Review by P-E-P — APPROVED** [review]
I've got nothing to add, LGTM.
