### PR TITLE
Generic pointers coerceable

### LINKED ISSUE #1903: Generic Pointers are castable
I tried this code: https://godbolt.org/z/Kjao733Pj

```rust
fn test<T>(x: *mut T) {
    let x = x as *mut u8;
}
```

I expected to see this happen: compile without error

Instead, this happened:

```
<source>:2:13: error: expected '* mut u8' got '* mut T'
    2 |     let x = x as *mut u8;
      |             ^    ~
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

### PR DESCRIPTION
**Pull request by philberty**
In order to fix the following issues we need to begin the journey to get rid of
the can_eq interface as well as the autoderef_flag hack inside it. In non-generic
contexts in order to call const pointer lang item methods the can_eq interface
was not possible to infer that these types are valid. This patch set adds a new
unify_and interface so that we can optionally inject inference variables and only
commit them when everything is ok and on failure cleanup. So during method
resolution and picking we can now pick using our TryCoerce interface instead
of the bad can_eq one.

Fixes #1903 #1901 #878
Addresses #1895

### CODE REVIEW

File: gcc/rust/typecheck/rust-coercion.cc [hunk 1]
```diff
@@ -169,13 +197,21 @@ TypeCoercionRules::coerce_unsafe_ptr (TyTy::BaseType *receiver,
...
 
 	return CoercionResult::get_error ();
       }
     }
 
+  bool receiver_is_non_ptr = receiver->get_kind () != TyTy::TypeKind::POINTER;
+  if (autoderef_flag && receiver_is_non_ptr)
+    {
+      // it is unsafe to autoderef to raw pointers
+      return CoercionResult::get_error ();
```
Comment (CohenArthur) [inline gcc/rust/typecheck/rust-coercion.cc:212]: Unsafe as in "this is allowed in unsafe contexts"? Or is it always forbidden?

File: gcc/rust/typecheck/rust-hir-dot-operator.cc [hunk 2]
```diff
@@ -86,6 +92,38 @@ MethodResolver::select (const TyTy::BaseType &receiver)
...
+	  const TyTy::ReferenceType &sptr
+	    = *static_cast<const TyTy::ReferenceType *> (impl_self);
+	  const TyTy::ReferenceType &ptr
+	    = *static_cast<const TyTy::ReferenceType *> (raw);
+
+	  // we could do this via lang-item assemblies if we refactor this
+	  bool mut_match = sptr.mutability () == ptr.mutability ();
+	  if (!mut_match)
+	    return true;
+	}
```
Comment (CohenArthur) [inline gcc/rust/typecheck/rust-hir-dot-operator.cc:126]: So having ambiguous implementations for `*mut T` and `*const T` is allowed as you pointed out in zulip, but is it also allowed for `&mut T` and `&T`? Or am I misunderstanding this bit of code?
