### PR TITLE
parser: Parse external type item

### LINKED ISSUE #1917: Cannot parse extern type declarations
I tried this code:

```rust
extern "C" {
    type Opaque;
}
```

I expected to see this happen: no error at the parsing stage - an error when feature gating.

`rustc test.rs -Z parse-only` does not throw errors

Instead, this happened:
```rust
test.rs:2:5: error: unrecognised token ‘type’ in extern block item declaration
    2 |     type Opaque;
      |     ^~~~
test.rs:2:5: error: failed to parse external item despite not reaching end of extern block
test.rs:3:1: error: failed to parse item in crate
    3 | }
      | ^

Analyzing compilation unit

Time variable                                   usr           sys          wall           GGC
 phase setup                        :   0.00 (  0%)   0.00 (  0%)   0.01 (100%)   137k ( 95%)
 TOTAL                              :   0.00          0.00          0.01          145k
Extra diagnostic checks enabled; compiler may run slowly.
Configure with --enable-checking=release to disable checks.
```

### Meta

- What version of Rust GCC were you using: 0d5fe7b9aee

Also ties in with #1579 (feature `extern_types`)

### PR DESCRIPTION
**Pull request by P-E-P**
Add the code to parse type item declaration within an extern block.

gcc/rust/ChangeLog:

	* parse/rust-parse-impl.h (Parser::parse_external_type_item): Add function to parser an external type item. (Parser::parse_external_item): Add identification and parsing for external type items.
	* parse/rust-parse.h: Add parser_external_type_item prototype.

Fixes #1917

### CODE REVIEW

File: gcc/rust/parse/rust-parse-impl.h [hunk 1]
```diff
@@ -3983,6 +3983,36 @@ Parser<ManagedTokenSource>::parse_lifetime ()
...
+      add_error (std::move (error));
+
+      skip_after_semicolon ();
+      return nullptr;
+    }
+
+  if (!skip_token (SEMICOLON))
+    {
+      return nullptr;
+    }
```
Comment (CohenArthur) [inline gcc/rust/parse/rust-parse-impl.h:4008]: I don't know if this is necessary or handled by the parsing of extern blocks. Also, minor style nit:

```suggestion
  if (!skip_token (SEMICOLON))
      return nullptr;
```

**Review by CohenArthur — COMMENTED** [review]
Great stuff :) I'd like to see at least two `-fsyntax-only` tests and we can merge this

```rust
extern "C" {
    type F;
}
```
as a simple case and 
```rust
extern "C" {
    type F;
    type E
}
```

to see if skipping the semicolon is valid or not, and how the error message looks

**Review by CohenArthur — APPROVED** [review]
LGTM! Thank you :)
