### PR TITLE
Check for deprecated attributes

### LINKED ISSUE #4236: `deprecated` attribute should give error with bad arguments
code:
```rust
#[deprecated(a,a)]
pub fn a(){}
```

expected:
```
error[E0541]: unknown meta item 'a'
 --> a.rs:5:14
  |
5 | #[deprecated(a,a)]
  |              ^ expected one of `since`, `note`

error: aborting due to previous error
```
code:
```rust
#[deprecated("a")]
pub fn a(){}
```

expected:
```
error[E0565]: item in `deprecated` must be a key/value pair
 --> a.rs:5:14
  |
5 | #[deprecated("a")]
  |              ^^^

error: aborting due to previous error
```

code:
```rust
#[deprecated(since=a, note=a)]
pub fn A(){}
```

Expected:
```
error: expected unsuffixed literal or identifier, found `a`
 --> a.rs:5:20
  |
5 | #[deprecated(since=a, note=a)]
  |                    ^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by sneaky-potato**
This PR checks for deprecated attributes and emits errors on bad arguments.

This patch fixes #4236

### CODE REVIEW

File: gcc/rust/util/rust-attributes.cc [hunk 1]
```diff
@@ -277,6 +277,97 @@ check_doc_attribute (const AST::Attribute &attribute)
...
+		  auto *nv = static_cast<AST::MetaNameValueStr *> (meta_item);
+
+		  const std::string key = nv->get_name ().as_string ();
+
+		  if (key != "since" && key != "note")
+		    {
+		      rust_error_at (nv->get_locus (), "unknown meta item %qs",
+				     key.c_str ());
+		      rust_inform (nv->get_locus (),
+				   "expected one of %<'since'%>, %<'note'%>");
```
Comment (P-E-P) [inline gcc/rust/util/rust-attributes.cc]: `%<` and `%>` will already be replaced with localized quotes, you can safely remove those inner quotes.

File: gcc/rust/util/rust-attributes.cc [hunk 2]
```diff
@@ -277,6 +277,97 @@ check_doc_attribute (const AST::Attribute &attribute)
...
+		break;
+
+	      case AST::MetaItem::ItemKind::Word:
+		{
+		  // #[deprecated("a")]
+		  auto *w = static_cast<AST::MetaWord *> (meta_item);
+
+		  rust_error_at (
+		    w->get_locus (),
+		    "item in %<'deprecated'%> must be a key/value pair");
```
Comment (P-E-P) [inline gcc/rust/util/rust-attributes.cc]:
```suggestion
		    "item in %<deprecated%> must be a key/value pair");
```

File: gcc/rust/util/rust-attributes.cc [hunk 3]
```diff
@@ -277,6 +277,97 @@ check_doc_attribute (const AST::Attribute &attribute)
...
+		{
+		  // #[deprecated(a,a)]
+		  auto *p = static_cast<AST::MetaItemPath *> (meta_item);
+
+		  std::string ident = p->get_path ().as_string ();
+
+		  rust_error_at (p->get_locus (), "unknown meta item %qs",
+				 ident.c_str ());
+		  rust_inform (p->get_locus (),
+			       "expected one of %<'since'%>, %<'note'%>");
```
Comment (P-E-P) [inline gcc/rust/util/rust-attributes.cc]:
```suggestion
			       "expected one of %<since%>, %<note%>");
```

Comment (sneaky-potato) [reply gcc/rust/util/rust-attributes.cc]: Resolved

File: gcc/rust/util/rust-attributes.cc (hunk 2 above)
Comment (sneaky-potato) [reply gcc/rust/util/rust-attributes.cc]: Resolved

File: gcc/rust/util/rust-attributes.cc (hunk 1 above)
Comment (sneaky-potato) [reply gcc/rust/util/rust-attributes.cc]: Resolved
