### PR TITLE
Parse macro expansion properly

### LINKED ISSUE #943: Support repetition macro matching
We need to support the AST::MacroMatchRepetition

- [x] actually match repetitions and count the number of matches
- [x] Add a clear errors function on the parser so we can reuse the same parser
- [x] track the fragments number of repetitions for transcribing purposes
- [ ] repetitions might result in multiple nodes fragments associated with the macro invocation this means we need to figure out how to do hir lowering for this which currently expects a 1-1 mapping
- [x] transcribe the buffer for repeating groups.

### LINKED ISSUE #952: When parseing a macro item it should parse all items
I tried this code: https://godbolt.org/z/13ar7xhrG

```rust
macro_rules! Test {
    ($a:ident, $b:ty) => {
        struct $a($b);
        struct BAD($b);
    };
}

Test!(Foo, i32);

fn main() -> i32 {
    let a = Foo(123);
    a.0 - 123
}
```

I expected to see this happen: That both structures are expanded and included in the compilation unit.

Instead, this happened: One was parsed and the struct named BAD was ignored

### Meta

- What version of Rust GCC were you using, git sha if possible. a5272f389b02623b8bc4aaeafcf84013dae7c9fb

### LINKED ISSUE #959: Parsing fails on macro containing semicolon
I tried this code:

```rust
extern "C" {
    fn puts(s: *const i8);
}

fn f() { unsafe { puts("blink" as *const str as *const i8); } }

macro_rules! twice {
    ($a:expr) => {$a; $a}
}

fn main() {
    twice!(f());
}
```

I expected to see this happen: no error, `f()` is called twice, `blink` is printed twice (even though the code is unsound)

Instead, this happened: 
```rust
test1.rs:8:21: error: tokens here and after are unparsed
    8 |     ($a:expr) => {$a; $a}
      |                    
```

### PR DESCRIPTION
**Pull request by CohenArthur**
This PR adds a base for trying to parse statements or items in macro invocations. We are now able to parse multiple items / expressions / statements properly, but do not lower them properly, which is the last remaining task in #943 

New macro parsing logic:
```mermaid
flowchart TD;
    has_semi -- Yes --> stmt;
    has_semi -- No --> invocation;
    invocation -- Is Parens --> expr;
    invocation -- Is Square --> expr;
    invocation -- Is Curly --> stmt;
```

Closes #943 
Closes #959 
Closes #952

### CODE REVIEW

**Comment by CohenArthur** [comment]
It seems to me that rustc expands one statement (the macro call) to multiple in the current block.
```rust
macro_rules! define_vars {
    ($($v:ident)*) => { $(let $v = 15;)* }
}

// This is valid and should parse items
fn main() {
    define_vars!(f g h i);
}
```

Look for the block of the main function, whose ident is `main#0`

<summary>AST Pre expansion</summary>
<details>

```rust
Crate {
    attrs: [],
    items: [
        Item {
            attrs: [],
            id: NodeId(4294967040),
            span: test.rs:12:1: 14:2 (#0),
            vis: Visibility {
                kind: Inherited,
                span: test.rs:12:1: 12:1 (#0),
                tokens: None,
            },
            ident: define_vars#0,
            kind: MacroDef(
                MacroDef {
                    body: Delimited(
                        DelimSpan {
                            open: test.rs:12:26: 12:27 (#0),
                            close: test.rs:14:1: 14:2 (#0),
                        },
                        Brace,
                        TokenStream(
                            [
                                (
                                    Delimited(
                                        DelimSpan {
                                            open: test.rs:13:5: 13:6 (#0),
                                            close: test.rs:13:18: 13:19 (#0),
                                        },
                                        Paren,
                                        TokenStream(
                                            [
                                                (
                                                    Token(
                                                        Token {
                                                            kind: Dollar,
                                                            span: test.rs:13:6: 13:7 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Delimited(
                                                        DelimSpan {
                                                            open: test.rs:13:7: 13:8 (#0),
                                                            close: test.rs:13:16: 13:17 (#0),
                                                        },
                                                        Paren,
                                                        TokenStream(
                                                            [
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Dollar,
                                                                            span: test.rs:13:8: 13:9 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "v",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:9: 13:10 (#0),
                                                                        },
                                                                    ),
                                                                    Joint,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Colon,
                                                                            span: test.rs:13:10: 13:11 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "ident",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:11: 13:16 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Token(
                                                        Token {
                                                            kind: BinOp(
                                                                Star,
                                                            ),
                                                            span: test.rs:13:17: 13:18 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                            ],
                                        ),
                                    ),
                                    Alone,
                                ),
                                (
                                    Token(
                                        Token {
                                            kind: FatArrow,
                                            span: test.rs:13:20: 13:22 (#0),
                                        },
                                    ),
                                    Alone,
                                ),
                                (
                                    Delimited(
                                        DelimSpan {
                                            open: test.rs:13:23: 13:24 (#0),
                                            close: test.rs:13:42: 13:43 (#0),
                                        },
                                        Brace,
                                        TokenStream(
                                            [
                                                (
                                                    Token(
                                                        Token {
                                                            kind: Dollar,
                                                            span: test.rs:13:25: 13:26 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Delimited(
                                                        DelimSpan {
                                                            open: test.rs:13:26: 13:27 (#0),
                                                            close: test.rs:13:39: 13:40 (#0),
                                                        },
                                                        Paren,
                                                        TokenStream(
                                                            [
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "let",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:27: 13:30 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Dollar,
                                                                            span: test.rs:13:31: 13:32 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "v",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:32: 13:33 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Eq,
                                                                            span: test.rs:13:34: 13:35 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Literal(
                                                                                Lit {
                                                                                    kind: Integer,
                                                                                    symbol: "15",
                                                                                    suffix: None,
                                                                                },
                                                                            ),
                                                                            span: test.rs:13:36: 13:38 (#0),
                                                                        },
                                                                    ),
                                                                    Joint,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Semi,
                                                                            span: test.rs:13:38: 13:39 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Token(
                                                        Token {
                                                            kind: BinOp(
                                                                Star,
                                                            ),
                                                            span: test.rs:13:40: 13:41 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                            ],
                                        ),
                                    ),
                                    Alone,
                                ),
                            ],
                        ),
                    ),
                    macro_rules: true,
                },
            ),
            tokens: None,
        },
        Item {
            attrs: [],
            id: NodeId(4294967040),
            span: test.rs:17:1: 19:2 (#0),
            vis: Visibility {
                kind: Inherited,
                span: test.rs:17:1: 17:1 (#0),
                tokens: None,
            },
            ident: main#0,
            kind: Fn(
                Fn {
                    defaultness: Final,
                    generics: Generics {
                        params: [],
                        where_clause: WhereClause {
                            has_where_token: false,
                            predicates: [],
                            span: test.rs:17:10: 17:10 (#0),
                        },
                        span: test.rs:17:8: 17:8 (#0),
                    },
                    sig: FnSig {
                        header: FnHeader {
                            unsafety: No,
                            asyncness: No,
                            constness: No,
                            ext: None,
                        },
                        decl: FnDecl {
                            inputs: [],
                            output: Default(
                                test.rs:17:11: 17:11 (#0),
                            ),
                        },
                        span: test.rs:17:1: 17:10 (#0),
                    },
                    body: Some(
                        Block {
                            stmts: [
                                Stmt {
                                    id: NodeId(4294967040),
                                    kind: MacCall(
                                        MacCallStmt {
                                            mac: MacCall {
                                                path: Path {
                                                    span: test.rs:18:5: 18:16 (#0),
                                                    segments: [
                                                        PathSegment {
                                                            ident: define_vars#0,
                                                            id: NodeId(4294967040),
                                                            args: None,
                                                        },
                                                    ],
                                                    tokens: None,
                                                },
                                                args: Delimited(
                                                    DelimSpan {
                                                        open: test.rs:18:17: 18:18 (#0),
                                                        close: test.rs:18:25: 18:26 (#0),
                                                    },
                                                    Parenthesis,
                                                    TokenStream(
                                                        [
                                                            (
                                                                Token(
                                                                    Token {
                                                                        kind: Ident(
                                                                            "f",
                                                                            false,
                                                                        ),
                                                                        span: test.rs:18:18: 18:19 (#0),
                                                                    },
                                                                ),
                                                                Alone,
                                                            ),
                                                            (
                                                                Token(
                                                                    Token {
                                                                        kind: Ident(
                                                                            "g",
                                                                            false,
                                                                        ),
                                                                        span: test.rs:18:20: 18:21 (#0),
                                                                    },
                                                                ),
                                                                Alone,
                                                            ),
                                                            (
                                                                Token(
                                                                    Token {
                                                                        kind: Ident(
                                                                            "h",
                                                                            false,
                                                                        ),
                                                                        span: test.rs:18:22: 18:23 (#0),
                                                                    },
                                                                ),
                                                                Alone,
                                                            ),
                                                            (
                                                                Token(
                                                                    Token {
                                                                        kind: Ident(
                                                                            "i",
                                                                            false,
                                                                        ),
                                                                        span: test.rs:18:24: 18:25 (#0),
                                                                    },
                                                                ),
                                                                Alone,
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                prior_type_ascription: None,
                                            },
                                            style: Semicolon,
                                            attrs: ThinVec(
                                                None,
                                            ),
                                            tokens: None,
                                        },
                                    ),
                                    span: test.rs:18:5: 18:27 (#0),
                                },
                            ],
                            id: NodeId(4294967040),
                            rules: Default,
                            span: test.rs:17:11: 19:2 (#0),
                            tokens: None,
                            could_be_bare_literal: false,
                        },
                    ),
                },
            ),
            tokens: None,
        },
    ],
    span: test.rs:12:1: 19:2 (#0),
    id: NodeId(4294967040),
    is_placeholder: false,
}
```
</details>

<summary> AST post expansion </summary>

<details>

```rust
Crate {
    attrs: [],
    items: [
        Item {
            attrs: [
                Attribute {
                    kind: Normal(
                        AttrItem {
                            path: Path {
                                span: no-location (#1),
                                segments: [
                                    PathSegment {
                                        ident: prelude_import#1,
                                        id: NodeId(2),
                                        args: None,
                                    },
                                ],
                                tokens: None,
                            },
                            args: Empty,
                            tokens: None,
                        },
                        None,
                    ),
                    id: AttrId(1),
                    style: Outer,
                    span: no-location (#1),
                },
            ],
            id: NodeId(1),
            span: no-location (#1),
            vis: Visibility {
                kind: Inherited,
                span: no-location (#1),
                tokens: None,
            },
            ident: #0,
            kind: Use(
                UseTree {
                    prefix: Path {
                        span: no-location (#1),
                        segments: [
                            PathSegment {
                                ident: {{root}}#1,
                                id: NodeId(3),
                                args: None,
                            },
                            PathSegment {
                                ident: std#1,
                                id: NodeId(4),
                                args: None,
                            },
                            PathSegment {
                                ident: prelude#1,
                                id: NodeId(5),
                                args: None,
                            },
                            PathSegment {
                                ident: rust_2015#1,
                                id: NodeId(6),
                                args: None,
                            },
                        ],
                        tokens: None,
                    },
                    kind: Glob,
                    span: no-location (#1),
                },
            ),
            tokens: None,
        },
        Item {
            attrs: [
                Attribute {
                    kind: Normal(
                        AttrItem {
                            path: Path {
                                span: no-location (#1),
                                segments: [
                                    PathSegment {
                                        ident: macro_use#1,
                                        id: NodeId(8),
                                        args: None,
                                    },
                                ],
                                tokens: None,
                            },
                            args: Empty,
                            tokens: None,
                        },
                        None,
                    ),
                    id: AttrId(0),
                    style: Outer,
                    span: no-location (#1),
                },
            ],
            id: NodeId(7),
            span: no-location (#1),
            vis: Visibility {
                kind: Inherited,
                span: no-location (#1),
                tokens: None,
            },
            ident: std#2,
            kind: ExternCrate(
                None,
            ),
            tokens: None,
        },
        Item {
            attrs: [],
            id: NodeId(9),
            span: test.rs:12:1: 14:2 (#0),
            vis: Visibility {
                kind: Inherited,
                span: test.rs:12:1: 12:1 (#0),
                tokens: None,
            },
            ident: define_vars#0,
            kind: MacroDef(
                MacroDef {
                    body: Delimited(
                        DelimSpan {
                            open: test.rs:12:26: 12:27 (#0),
                            close: test.rs:14:1: 14:2 (#0),
                        },
                        Brace,
                        TokenStream(
                            [
                                (
                                    Delimited(
                                        DelimSpan {
                                            open: test.rs:13:5: 13:6 (#0),
                                            close: test.rs:13:18: 13:19 (#0),
                                        },
                                        Paren,
                                        TokenStream(
                                            [
                                                (
                                                    Token(
                                                        Token {
                                                            kind: Dollar,
                                                            span: test.rs:13:6: 13:7 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Delimited(
                                                        DelimSpan {
                                                            open: test.rs:13:7: 13:8 (#0),
                                                            close: test.rs:13:16: 13:17 (#0),
                                                        },
                                                        Paren,
                                                        TokenStream(
                                                            [
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Dollar,
                                                                            span: test.rs:13:8: 13:9 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "v",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:9: 13:10 (#0),
                                                                        },
                                                                    ),
                                                                    Joint,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Colon,
                                                                            span: test.rs:13:10: 13:11 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "ident",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:11: 13:16 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Token(
                                                        Token {
                                                            kind: BinOp(
                                                                Star,
                                                            ),
                                                            span: test.rs:13:17: 13:18 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                            ],
                                        ),
                                    ),
                                    Alone,
                                ),
                                (
                                    Token(
                                        Token {
                                            kind: FatArrow,
                                            span: test.rs:13:20: 13:22 (#0),
                                        },
                                    ),
                                    Alone,
                                ),
                                (
                                    Delimited(
                                        DelimSpan {
                                            open: test.rs:13:23: 13:24 (#0),
                                            close: test.rs:13:42: 13:43 (#0),
                                        },
                                        Brace,
                                        TokenStream(
                                            [
                                                (
                                                    Token(
                                                        Token {
                                                            kind: Dollar,
                                                            span: test.rs:13:25: 13:26 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Delimited(
                                                        DelimSpan {
                                                            open: test.rs:13:26: 13:27 (#0),
                                                            close: test.rs:13:39: 13:40 (#0),
                                                        },
                                                        Paren,
                                                        TokenStream(
                                                            [
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "let",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:27: 13:30 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Dollar,
                                                                            span: test.rs:13:31: 13:32 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Ident(
                                                                                "v",
                                                                                false,
                                                                            ),
                                                                            span: test.rs:13:32: 13:33 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Eq,
                                                                            span: test.rs:13:34: 13:35 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Literal(
                                                                                Lit {
                                                                                    kind: Integer,
                                                                                    symbol: "15",
                                                                                    suffix: None,
                                                                                },
                                                                            ),
                                                                            span: test.rs:13:36: 13:38 (#0),
                                                                        },
                                                                    ),
                                                                    Joint,
                                                                ),
                                                                (
                                                                    Token(
                                                                        Token {
                                                                            kind: Semi,
                                                                            span: test.rs:13:38: 13:39 (#0),
                                                                        },
                                                                    ),
                                                                    Alone,
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Alone,
                                                ),
                                                (
                                                    Token(
                                                        Token {
                                                            kind: BinOp(
                                                                Star,
                                                            ),
                                                            span: test.rs:13:40: 13:41 (#0),
                                                        },
                                                    ),
                                                    Alone,
                                                ),
                                            ],
                                        ),
                                    ),
                                    Alone,
                                ),
                            ],
                        ),
                    ),
                    macro_rules: true,
                },
            ),
            tokens: None,
        },
        Item {
            attrs: [],
            id: NodeId(10),
            span: test.rs:17:1: 19:2 (#0),
            vis: Visibility {
                kind: Inherited,
                span: test.rs:17:1: 17:1 (#0),
                tokens: None,
            },
            ident: main#0,
            kind: Fn(
                Fn {
                    defaultness: Final,
                    generics: Generics {
                        params: [],
                        where_clause: WhereClause {
                            has_where_token: false,
                            predicates: [],
                            span: test.rs:17:10: 17:10 (#0),
                        },
                        span: test.rs:17:8: 17:8 (#0),
                    },
                    sig: FnSig {
                        header: FnHeader {
                            unsafety: No,
                            asyncness: No,
                            constness: No,
                            ext: None,
                        },
                        decl: FnDecl {
                            inputs: [],
                            output: Default(
                                test.rs:17:11: 17:11 (#0),
                            ),
                        },
                        span: test.rs:17:1: 17:10 (#0),
                    },
                    body: Some(
                        Block {
                            stmts: [
                                Stmt {
                                    id: NodeId(12),
                                    kind: Local(
                                        Local {
                                            id: NodeId(13),
                                            pat: Pat {
                                                id: NodeId(14),
                                                kind: Ident(
                                                    ByValue(
                                                        Not,
                                                    ),
                                                    f#0,
                                                    None,
                                                ),
                                                span: test.rs:13:31: 13:33 (#4),
                                                tokens: None,
                                            },
                                            ty: None,
                                            kind: Init(
                                                Expr {
                                                    id: NodeId(15),
                                                    kind: Lit(
                                                        Lit {
                                                            token: Lit {
                                                                kind: Integer,
                                                                symbol: "15",
                                                                suffix: None,
                                                            },
                                                            kind: Int(
                                                                15,
                                                                Unsuffixed,
                                                            ),
                                                            span: test.rs:13:36: 13:38 (#4),
                                                        },
                                                    ),
                                                    span: test.rs:13:36: 13:38 (#4),
                                                    attrs: ThinVec(
                                                        None,
                                                    ),
                                                    tokens: None,
                                                },
                                            ),
                                            span: test.rs:13:27: 13:39 (#4),
                                            attrs: ThinVec(
                                                None,
                                            ),
                                            tokens: None,
                                        },
                                    ),
                                    span: test.rs:13:27: 13:39 (#4),
                                },
                                Stmt {
                                    id: NodeId(16),
                                    kind: Local(
                                        Local {
                                            id: NodeId(17),
                                            pat: Pat {
                                                id: NodeId(18),
                                                kind: Ident(
                                                    ByValue(
                                                        Not,
                                                    ),
                                                    g#0,
                                                    None,
                                                ),
                                                span: test.rs:13:31: 13:33 (#4),
                                                tokens: None,
                                            },
                                            ty: None,
                                            kind: Init(
                                                Expr {
                                                    id: NodeId(19),
                                                    kind: Lit(
                                                        Lit {
                                                            token: Lit {
                                                                kind: Integer,
                                                                symbol: "15",
                                                                suffix: None,
                                                            },
                                                            kind: Int(
                                                                15,
                                                                Unsuffixed,
                                                            ),
                                                            span: test.rs:13:36: 13:38 (#4),
                                                        },
                                                    ),
                                                    span: test.rs:13:36: 13:38 (#4),
                                                    attrs: ThinVec(
                                                        None,
                                                    ),
                                                    tokens: None,
                                                },
                                            ),
                                            span: test.rs:13:27: 13:39 (#4),
                                            attrs: ThinVec(
                                                None,
                                            ),
                                            tokens: None,
                                        },
                                    ),
                                    span: test.rs:13:27: 13:39 (#4),
                                },
                                Stmt {
                                    id: NodeId(20),
                                    kind: Local(
                                        Local {
                                            id: NodeId(21),
                                            pat: Pat {
                                                id: NodeId(22),
                                                kind: Ident(
                                                    ByValue(
                                                        Not,
                                                    ),
                                                    h#0,
                                                    None,
                                                ),
                                                span: test.rs:13:31: 13:33 (#4),
                                                tokens: None,
                                            },
                                            ty: None,
                                            kind: Init(
                                                Expr {
                                                    id: NodeId(23),
                                                    kind: Lit(
                                                        Lit {
                                                            token: Lit {
                                                                kind: Integer,
                                                                symbol: "15",
                                                                suffix: None,
                                                            },
                                                            kind: Int(
                                                                15,
                                                                Unsuffixed,
                                                            ),
                                                            span: test.rs:13:36: 13:38 (#4),
                                                        },
                                                    ),
                                                    span: test.rs:13:36: 13:38 (#4),
                                                    attrs: ThinVec(
                                                        None,
                                                    ),
                                                    tokens: None,
                                                },
                                            ),
                                            span: test.rs:13:27: 13:39 (#4),
                                            attrs: ThinVec(
                                                None,
                                            ),
                                            tokens: None,
                                        },
                                    ),
                                    span: test.rs:13:27: 13:39 (#4),
                                },
                                Stmt {
                                    id: NodeId(24),
                                    kind: Local(
                                        Local {
                                            id: NodeId(25),
                                            pat: Pat {
                                                id: NodeId(26),
                                                kind: Ident(
                                                    ByValue(
                                                        Not,
                                                    ),
                                                    i#0,
                                                    None,
                                                ),
                                                span: test.rs:13:31: 13:33 (#4),
                                                tokens: None,
                                            },
                                            ty: None,
                                            kind: Init(
                                                Expr {
                                                    id: NodeId(27),
                                                    kind: Lit(
                                                        Lit {
                                                            token: Lit {
                                                                kind: Integer,
                                                                symbol: "15",
                                                                suffix: None,
                                                            },
                                                            kind: Int(
                                                                15,
                                                                Unsuffixed,
                                                            ),
                                                            span: test.rs:13:36: 13:38 (#4),
                                                        },
                                                    ),
                                                    span: test.rs:13:36: 13:38 (#4),
                                                    attrs: ThinVec(
                                                        None,
                                                    ),
                                                    tokens: None,
                                                },
                                            ),
                                            span: test.rs:13:27: 13:39 (#4),
                                            attrs: ThinVec(
                                                None,
                                            ),
                                            tokens: None,
                                        },
                                    ),
                                    span: test.rs:13:27: 13:39 (#4),
                                },
                            ],
                            id: NodeId(11),
                            rules: Default,
                            span: test.rs:17:11: 19:2 (#0),
                            tokens: None,
                            could_be_bare_literal: false,
                        },
                    ),
                },
            ),
            tokens: None,
        },
    ],
    span: test.rs:12:1: 19:2 (#0),
    id: NodeId(0),
    is_placeholder: false,
}
```

</details>

**Comment by philberty** [comment]
Might be worth @SimplyTheOther having a flick through this to see if he has any opinions

File: gcc/rust/expand/rust-macro-expand.cc [hunk 1]
```diff
@@ -1072,7 +1075,35 @@ class AttrVisitor : public AST::ASTVisitor
...
+	    continue;
+	  }
+
+	if (!fragment.get_nodes ().empty ())
+	  {
+	    // Remove the current expanded invocation
+	    it = stmts.erase (it);
+	    for (auto &node : fragment.get_nodes ())
+	      {
+		it = stmts.insert (it, AST::SingleASTNode::extract_stmt (node));
```
Comment (SimplyTheOther) [inline gcc/rust/expand/rust-macro-expand.cc:1098]: Since `take_expanded_fragment()` takes ownership of the `ASTFragment` using move and the `fragment` isn't used again afterward, wouldn't it be better to `std::move()` each statement from the SingleASTNode instead of cloning it?

This would probably involve rewriting `extract_stmt()` to move and be a member function. 

Also, wouldn't a macro that contained a `SingleASTNode` that wasn't a statement cause an assertion failure here? It should be a fatal error I would think, but assertion failure is probably less useful as an error message to the programmer. Ignore this if there's some check somewhere else that I missed.

File: gcc/rust/expand/rust-macro-expand.cc [hunk 2]
```diff
@@ -3359,14 +3390,31 @@ MacroExpander::expand_crate ()
...
+	  it++;
+	  continue;
+	}
+
+      if (!fragment.get_nodes ().empty ())
+	{
+	  it = items.erase (it);
+	  for (auto &node : fragment.get_nodes ())
+	    {
+	      it = items.insert (it, AST::SingleASTNode::extract_item (node));
```
Comment (SimplyTheOther) [inline gcc/rust/expand/rust-macro-expand.cc:3410]: Similar considerations to above would apply here.

**Review by SimplyTheOther — APPROVED** [review]
I had a couple of nitpicks, but otherwise looks very good. Nice job.

File: gcc/rust/expand/rust-macro-expand.cc (hunk 1 above)
Comment (CohenArthur) [reply gcc/rust/expand/rust-macro-expand.cc:1098]: > Since `take_expanded_fragment()` takes ownership of the `ASTFragment` using move and the `fragment` isn't used again afterward, wouldn't it be better to `std::move()` each statement from the SingleASTNode instead of cloning it?
> 
> This would probably involve rewriting `extract_stmt()` to move and be a member function.

Very good point. This is definitely something that I'll look into, thanks. I think it would be easy to make `extract_stmt` a member function, I had originally made these functions to pass them as lambdas in `expand_pointer_allow_strip`, but that didn't turn out as ergonomic as I'd hoped.

> 
> Also, wouldn't a macro that contained a `SingleASTNode` that wasn't a statement cause an assertion failure here? It should be a fatal error I would think, but assertion failure is probably less useful as an error message to the programmer. Ignore this if there's some check somewhere else that I missed.

This is definitely an issue and the reason why so many tests fail at the moment. The mechanism we have to "prevent" this is that the content of the macro's expansion are parsed according to the current context. So, for example, if we're in a position expecting an expression 
```rust
let a = add!(1, 561, 4);
```
then the parser will only try to parse expressions from the expanded tokens. Otherwise, this is a parse error.

I don't know if this is enough "protection" against the behavior. But ideally, this should never crash for users.

This is also why tests don't pass right now: Since I didn't add visitors to other constructs such as let-assignments, we try to extract statements from something that is clearly an expression if the above example is located in a block.

File: gcc/rust/expand/rust-macro-expand.cc [hunk 3]
```diff
@@ -3811,53 +3861,63 @@ MacroExpander::transcribe_rule (
   //   as a statement (either via ExpressionStatement or
   //   MacroInvocationWithSemi)
 
-  // parse the item
-  std::vector<AST::SingleASTNode> nodes;
-  switch (invoc_token_tree.get_delim_type ())
+  // The flow-chart in order to choose a parsing function is as follows:
+  //
+  // [is in item context?]
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-expand.cc:3866]: great comment keep this in

File: gcc/rust/expand/rust-macro-expand.cc [hunk 4]
```diff
@@ -3811,53 +3861,63 @@ MacroExpander::transcribe_rule (
...
+  //     -- No --> [has semicolon?]
+  //                 -- Yes --> parser.parse_stmt();
+  //                 -- No --> [switch invocation.delimiter()]
+  //                             -- { } --> parser.parse_stmt();
+  //                             -- _ --> parser.parse_expr();
+
+  // If there is a semicolon OR we are expanding a MacroInvocationSemi, then
+  // we can parse multiple items. Otherwise, parse multiple expressions
+  std::function<AST::SingleASTNode ()> parse_fn
+    = [&parser] () { return AST::SingleASTNode (parser.parse_expr ()); };
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-expand.cc:3877]: great use of lambda's here. Though can we make this two statements:
```
std::unique_ptr<..> e = parser.parse_expr();
return AST::SingleASTNode(std::move(e));
```
This helps with gdb sessions

File: gcc/rust/expand/rust-macro-expand.cc [hunk 5]
```diff
@@ -3125,7 +3156,7 @@ MacroExpander::expand_decl_macro (Location invoc_locus,
       RichLocation r (invoc_locus);
       r.add_range (rules_def.get_locus ());
       rust_error_at (r, "Failed to match any rule within macro");
-      return AST::ASTFragment::create_empty ();
+      return AST::ASTFragment::create_error ();
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-expand.cc:3159]: do we still need to return the ASTFragments to be part of the MacroInvocation since it seems we now issue a fatal_error on that?

File: gcc/rust/expand/rust-macro-expand.cc [hunk 6]
```diff
@@ -3359,14 +3390,31 @@ MacroExpander::expand_crate ()
   for (auto it = items.begin (); it != items.end ();)
     {
       auto &item = *it;
+      rust_debug ("expanding item %ld", it - items.begin ());
 
       // mark for stripping if required
       item->accept_vis (attr_visitor);
 
-      if (item->is_marked_for_strip ())
+      auto fragment = take_expanded_fragment ();
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-expand.cc:3398]: Is this where we expand the invocations SingleAstNodes?

It seems like a good idea actually, though I am having trouble following the logic here. I would have assumed we could do something like:

```
for (auto& item : crate.items) {
  if (item.is_macro_invcoation()) {
    <take ownership of all fragments>
    <append-fragments to crate>
    <clear-fragments from macro-invocation>
  }
}
```

File: gcc/rust/expand/rust-macro-expand.h [hunk 7]
```diff
@@ -137,7 +137,9 @@ struct MacroExpander
 
   MacroExpander (AST::Crate &crate, ExpansionCfg cfg, Session &session)
     : cfg (cfg), crate (crate), session (session),
-      sub_stack (SubstitutionScope ()), resolver (Resolver::Resolver::get ()),
+      sub_stack (SubstitutionScope ()),
+      expanded_fragment (AST::ASTFragment::create_empty ()),
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-expand.h:141]: What does this do? Is this safe/cleared in between all macro expansions?

File: gcc/rust/hir/rust-ast-lower-implitem.h [hunk 8]
```diff
@@ -54,15 +54,19 @@ class ASTLowerImplItem : public ASTLoweringBase
...
+    // if (!invoc.has_semicolon ())
+    //   return;
+
+    // AST::ASTFragment &fragment = invoc.get_fragment ();
+
+    // // FIXME
+    // // this assertion might go away, maybe on failure's to expand a macro?
+    // rust_assert (!fragment.get_nodes ().empty ());
+    // fragment.get_nodes ().at (0).accept_vis (*this);
+    rust_fatal_error (
```
Comment (philberty) [inline gcc/rust/hir/rust-ast-lower-implitem.h:66]: let's keep these as fatal_errors or assertions until the end of the macro expansion milestone since there should be errors already emitted prior to this that allow us to ignore visiting these in the first place.

**Review by philberty — CHANGES_REQUESTED** [review]
I think you're doing the right thing which is great because our other solution to change HIR lowering was going to be messy.

I would like to see how the actual expansion of taking ownership of the fragments to be a little more clear as I am finding it hard to follow right now how we are manipulating the AST. 

Overall lets go with this solution you have found, I think with a little more cleanup this is good to go.

**Comment by philberty** [comment]
I am loving the diagram can we remove the WIP label?

File: gcc/testsuite/rust/execute/torture/macros3.rs [hunk 9]
```diff
@@ -15,35 +15,35 @@ fn f() {
 
 macro_rules! invocation0 {
     (valid) => {
-        f()
+        f();
```
Comment (philberty) [inline gcc/testsuite/rust/execute/torture/macros3.rs:18]: are these test cases invalid? Do they require the semi colon in rustc?

File: gcc/testsuite/rust/execute/torture/macros9.rs [hunk 10]
```diff
@@ -8,13 +8,15 @@ fn f() {
...
+        printf(c_p);
+    }
 }
 
 macro_rules! one_or_more {
     ($($a:expr)+) => {
-        f()
-    }
+        f();
+    };
```
Comment (philberty) [inline gcc/testsuite/rust/execute/torture/macros9.rs:19]: same here

File: gcc/testsuite/rust/execute/torture/macros17.rs [hunk 11]
```diff
@@ -5,9 +5,9 @@ macro_rules! two {
 }
 
 macro_rules! one {
-    (1) => {
+    (1) => {{
         two!(2)
```
Comment (philberty) [inline gcc/testsuite/rust/execute/torture/macros17.rs:9]: neat

File: gcc/rust/ast/rust-macro.h [hunk 12]
```diff
@@ -464,9 +464,6 @@ class MacroInvocation : public TypeNoBounds,
   MacroInvocData invoc_data;
   Location locus;
 
-  // this is the expanded macro
-  ASTFragment fragment;
```
Comment (philberty) [inline gcc/rust/ast/rust-macro.h:468]: brilliant

File: gcc/rust/ast/rust-ast.h [hunk 13]
```diff
@@ -1620,18 +1679,47 @@ class ASTFragment
...
+  bool should_expand () const { return !is_error () && !nodes.empty (); }
+
+  /**
+   * We need to make a special case for Expression fragments as only one
+   * Node will be extracted from the `nodes` vector
+   */
+
+  bool is_expression_fragment () const
+  {
+    return nodes.size () == 1
```
Comment (philberty) [inline gcc/rust/ast/rust-ast.h:1708]: i like this

File: gcc/rust/ast/rust-ast.h [hunk 14]
```diff
@@ -1604,11 +1659,15 @@ class ASTFragment
    * ability for a macro to expand to two statements, for instance. */
 
   std::vector<SingleASTNode> nodes;
+  bool fragment_is_error;
 
 public:
-  ASTFragment (std::vector<SingleASTNode> nodes) : nodes (std::move (nodes)) {}
+  ASTFragment (std::vector<SingleASTNode> nodes, bool fragment_is_error = false)
+    : nodes (std::move (nodes)), fragment_is_error (fragment_is_error)
+  {}
```
Comment (philberty) [inline gcc/rust/ast/rust-ast.h:1667]: might be worth adding in an assertion hat if the vector of nodes must be empty when the flag fragement_is_error is set

**Review by philberty — APPROVED** [review]
This is much much more clear i can see what your doing now.

As gross as it sounds a macro might help you with some of the boiler plate here to enforce some good practices on performing the substitution

File: gcc/testsuite/rust/execute/torture/macros3.rs (hunk 9 above)
Comment (CohenArthur) [reply gcc/testsuite/rust/execute/torture/macros3.rs:18]: So they are not invalid, but they fail this PR's parsing scheme: Because the macro was invoked like so `invocation0(valid);`, the parser is trying to parse a statement, which fails since this is a `CallExpr` without a semicolon behind it. So we need to think about how to handle this. I've added a FIXME comment inside the `transcribe_rule` function where the token stream gets parsed, and I'll open up an issue

**Comment by CohenArthur** [comment]
> As gross as it sounds a macro might help you with some of the boiler plate here to enforce some good practices on performing the substitution

Yeah, this needs some improvements I agree. I want to figure out a good way to go about it so I'll think on it once I implement the rest of the visitors

bors r+
