### PR TITLE
Do not crash on empty macros expand. Fixes #1712

### LINKED ISSUE #1712: ICE when macro invocation results in buggy ast
I tried this code:

```rust
macro_rules! empty {
    () => {}
}

fn main() {
    let a = empty!();
}
```

I expected to see this happen: 
parse error

Instead, this happened: 
output:
```
rust1: internal compiler error: Segmentation fault
0x7feb4d4ab08f ???
        /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7feb4d48c082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

### Meta

- What version of Rust GCC were you using, git sha if possible.
```
$ gccrs -v
Using built-in specs.
COLLECT_GCC=gccrs
COLLECT_LTO_WRAPPER=/home/tamaron/gccrs-install/libexec/gcc/x86_64-pc-linux-gnu/13.0.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gccrs/configure --prefix=/home/tamaron/gccrs-install --disable-bootstrap --enable-multilib --enable-languages=rust --enable-checking=gimple,tree,types CXXFLAGS=-fno-pie CFLAGS=-fno-pie LDFLAGS=-no-pie : (reconfigured) ../gccrs/configure --prefix=/home/tamaron/gccrs-install --disable-bootstrap --enable-multilib --enable-checking=gimple,tree,types CXXFLAGS=-fno-pie CFLAGS=-fno-pie LDFLAGS=-no-pie --enable-languages=c,lto,rust --no-create --no-recursion
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.0.0 20221213 (experimental) (GCC) 
```

### PR DESCRIPTION
**Pull request by teromene**
This PR fixes a compiler crash when expanding an empty macro into an existing AST.
(I ran clang-format but it marked a few other files as dirty, and I therefore did not touch them)

Signed-off-by: Lyra Karenai <teromene@teromene.fr>

Fixes #1712

### CODE REVIEW

File: gcc/rust/expand/rust-macro-expand.cc [hunk 1]
```diff
@@ -839,7 +839,10 @@ static AST::Fragment
 transcribe_expression (Parser<MacroInvocLexer> &parser)
 {
   auto expr = parser.parse_expr ();
-
+  if (expr == nullptr)
+    {
```
Comment (dkm) [inline gcc/rust/expand/rust-macro-expand.cc:843]: For single statement block, you can omit the braces:
```
if (cond)
  stmt;
```

**Comment by dkm** [comment]
Another small required change: the `Signed-off-by` that acknowledges the DCO must refer to your real name.

Also, it would be better for us if you could have all the description in the commit message (you can duplicate part of the PR text). When we push commit in GCC, we don't port the PR message, only the commits... which in your case is empty :)

Thanks for your contribution, sorry for the hassle :)

**Comment by teromene** [comment]
I updated the commit message, is it good now ?

**Comment by dkm** [comment]
Yes, thanks! I can't really say anything about the patch itself and leave it to the real devs.

**Review by philberty — APPROVED** [review]
LGTM good find

**Comment by philberty** [comment]
@teromene you need to remove the checklist from your opening PR comment here otherwise that will be included in the merge commit.

**Comment by teromene** [comment]
Done
