### PR TITLE
gccrs: fix ICE in TyVar constructor

### LINKED ISSUE #3556: ICE in TyVar, at rust/typecheck/rust-tyty-util.cc:31
auto-reduced (treereduce-rust):
````rust
fn main() {
    let ref mut a @ (ref mut b,);
}

````

original:
````rust
fn main() {
    let ref mut a @ (
        //~^ ERROR cannot borrow value as mutable more than once at a time
            ref mut b,
            [
                ref mut c,
                ref mut d,
                ref e,
            ]
        ); //~ error: expected identifier, found `=`
}

````

Version information:

a988708b4ba2b5a27715ea34c09ccfd3ed5143ca

Command:
`crab1 -Warray-bounds -mtune=generic -march=x86-64 -O0 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -frust-incomplete-and-experimental-compiler-do-not-use`

<details><summary><strong>Program output</strong></summary>
<p>

```
crab1: internal compiler error: in TyVar, at rust/typecheck/rust-tyty-util.cc:31
0x869aa0 Rust::TyTy::TyVar::TyVar(unsigned int)
	../../gcc/rust/typecheck/rust-tyty-util.cc:31
0x869abc Rust::TyTy::TyVar::TyVar(unsigned int)
	../../gcc/rust/typecheck/rust-tyty-util.cc:40
0xf1459c ???
	../../gcc/rust/typecheck/rust-hir-type-check-pattern.h:41
0xf14f11 Rust::Resolver::TypeCheckPattern::Resolve(Rust::HIR::Pattern&, Rust::TyTy::BaseType*)
	../../gcc/rust/typecheck/rust-hir-type-check-pattern.cc:39
0xf28f15 Rust::Resolver::TypeCheckStmt::Resolve(Rust::HIR::Stmt&)
	../../gcc/rust/typecheck/rust-hir-type-check-stmt.cc:34
0xf1aaa1 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
	../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:602
0xf192b8 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr&)
	../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:47
0xef6140 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::Function&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:638
0xeecb37 Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:59
0xe84e8b Rust::Resolver::TypeResolution::Resolve(Rust::HIR::Crate&)
	../../gcc/rust/typecheck/rust-hir-type-check.cc:75
0xc5c2d3 Rust::Session::compile_crate(char const*)
	../../gcc/rust/rust-session-manager.cc:685
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by Lishin1215**
fix #3556 
The changes ensure that type lookup failures no longer trigger assertions.
If further support for this pattern is needed, I'm happy to discuss possible approaches further!

gcc/rust/ChangeLog:

	* typecheck/rust-tyty-util.cc (TyVar::TyVar): Add null check to avoid ICE.
	(TyVar::get_tyty): Return nullptr when lookup fails.
	(TyVar::clone): Handle null base type safely.
	(TyVar::monomorphized_clone): Add fallback for error types.

gcc/testsuite/ChangeLog:

	* rust/compile/issue-3556.rs: New test.

### CODE REVIEW

File: gcc/rust/typecheck/rust-tyty-util.cc [hunk 1]
```diff
@@ -30,7 +30,10 @@ TyVar::TyVar (HirId ref) : ref (ref)
   auto context = Resolver::TypeCheckContext::get ();
   BaseType *lookup = nullptr;
   bool ok = context->lookup_type (ref, &lookup);
-  rust_assert (ok);
+  if (!ok || lookup == nullptr || lookup->get_kind () == TypeKind::ERROR)
+    {
+      return;
+    }
```
Comment (dkm) [inline gcc/rust/typecheck/rust-tyty-util.cc]: Usually for single statement, we skip the braces...

File: gcc/rust/typecheck/rust-tyty-util.cc [hunk 2]
```diff
@@ -39,7 +42,10 @@ TyVar::get_tyty () const
   auto context = Resolver::TypeCheckContext::get ();
   BaseType *lookup = nullptr;
   bool ok = context->lookup_type (ref, &lookup);
-  rust_assert (ok);
+  if (!ok || lookup == nullptr)
+    {
+      return nullptr;
```
Comment (dkm) [inline gcc/rust/typecheck/rust-tyty-util.cc]: ditto

File: gcc/rust/typecheck/rust-tyty-util.cc [hunk 3]
```diff
@@ -95,7 +101,12 @@ TyVar::subst_covariant_var (TyTy::BaseType *orig, TyTy::BaseType *subst)
 TyVar
 TyVar::clone () const
 {
-  TyTy::BaseType *c = get_tyty ()->clone ();
+  TyTy::BaseType *base = get_tyty ();
+  if (base == nullptr || base->get_kind () == TypeKind::ERROR)
+    {
+      return TyVar::get_implicit_infer_var (UNKNOWN_LOCATION);
+    }
```
Comment (dkm) [inline gcc/rust/typecheck/rust-tyty-util.cc]: ditto

File: gcc/rust/typecheck/rust-tyty-util.cc [hunk 4]
```diff
@@ -105,6 +116,11 @@ TyVar::monomorphized_clone () const
   auto &mappings = Analysis::Mappings::get ();
   auto context = Resolver::TypeCheckContext::get ();
 
+  TyTy::BaseType *base = get_tyty ();
+  if (base == nullptr || base->get_kind () == TypeKind::ERROR)
+    {
+      return TyVar::get_implicit_infer_var (UNKNOWN_LOCATION);
+    }
```
Comment (dkm) [inline gcc/rust/typecheck/rust-tyty-util.cc]: ditto

File: gcc/rust/typecheck/rust-tyty-util.cc (hunk 1 above)
Comment (Lishin1215) [reply gcc/rust/typecheck/rust-tyty-util.cc]: Thanks for the review, @dkm  
I've updated the code style to remove the unnecessary braces!
