### PR TITLE
Resolve module visibility properly

### LINKED ISSUE #1159: Resolve SimplePaths to DefId's
This change depends on #1158 

- [x] Add missing mappings to HIR::SimplePath #1176 
- [x] Add missing mappings to HIR::SimpePathSegment #1176
- [x] Remove the default locus argument of builtin_location on HIR::SimplePathSegment #1174 

Resolving a SimplePath to a DefId its achieved via the name-resolver class:

```
   Parameter: SimplePath* expr;

    NodeId ast_node_id = expr.get_mappings ().get_nodeid ();

    // then lookup the reference_node_id
    NodeId ref_node_id = UNKNOWN_NODEID;
    if (resolver->lookup_resolved_name (ast_node_id, &ref_node_id))
      {
	// these ref_node_ids will resolve to a pattern declaration but we are
	// interested in the definition that this refers to get the parent id
	Definition def;
	if (!resolver->lookup_definition (ref_node_id, &def))
	  {
	    // FIXME
	    // this is an internal error
	    rust_error_at (expr.get_locus (),
			   "unknown reference for resolved name");
	    return;
	  }
	ref_node_id = def.parent;
      }
```

if we are assuming this path can or should only resolve to modules we can ignore the type resolver name-space.

```
    if (ref_node_id == UNKNOWN_NODEID)
      {
        // this is an internal error but error messages are useful for now
        // down the line we will be able to rely on the changes make in #1158 
        // that this will have already errored out for us and we can just return
	rust_error_at (expr.get_locus (), "path: %s",
		       expr.as_string ().c_str ());
	return;
      }
```

Now we have resolved the expression to its definitions NodeId which is all within the AST. 

### Getting the DefId from NodeId

Note there is a bug with our mappings class here but we can fix this either as part of this issue or in a separate issue/pr we need to reverse map the NodeId back to an Hir node so that we can look up the Hir node to the DefID but the mappings class as nested these reverse mappings with the associated CrateNum which is wrong but we can ignore this for now.

```
    // node back to HIR
    HirId ref;
    if (!mappings->lookup_node_to_hir (expr.get_mappings ().get_crate_num (),
				       ref_node_id, &ref))
      {
	// this is an internal error like above but its useful for debugging for now
	rust_error_at (expr.get_locus (), "reverse lookup failure");
	return;
      }
```

Now that we have the associated HirId of the resolved path we can look it up again in the mappings and again this wrongly associates the crate num here but ignore this for now.

```
  HIR::Item *lookup_hir_item (CrateNum crateNum, HirId id);
```
Now you have an HIR::Item and you can get the DefId directly from that item which should be the module you looking for.

### PR DESCRIPTION
**Pull request by CohenArthur**
Closes #1159

### CODE REVIEW

**Review by philberty — APPROVED** [review]
LGTM

**Comment by CohenArthur** [comment]
@philberty Sorry, I didn't realize this would run bad on existing tests. You can review the last commit only to see how that got fixed. If you approve, I'll rebase so that the buildbot is happy with my changes

File: gcc/rust/privacy/rust-visibility-resolver.cc [hunk 1]
```diff
@@ -45,16 +46,56 @@ VisibilityResolver::go (HIR::Crate &crate)
...
+  // FIXME: Add a hint here if we can find the path in another scope, such as
+  // a type or something else
+  // TODO: For the hint, can we point to the original item's definition if
+  // present?
+
+  Resolver::Definition def;
+  rust_assert (resolver.lookup_definition (ref_node_id, &def));
+
+  // FIXME: Is that what we want?
+  ref_node_id = def.parent;
```
Comment (philberty) [inline gcc/rust/privacy/rust-visibility-resolver.cc:77]: This is fine, for now just leave it as a FIXME. I was to get rid of this step in the future.

File: gcc/rust/privacy/rust-visibility-resolver.cc [hunk 2]
```diff
@@ -45,16 +46,56 @@ VisibilityResolver::go (HIR::Crate &crate)
...
-// {
-//   return false;
-// }
+  HirId ref;
+  rust_assert (
+    mappings.lookup_node_to_hir (restriction.get_mappings ().get_crate_num (),
+				 ref_node_id, &ref));
+
+  auto module
+    = mappings.lookup_module (restriction.get_mappings ().get_crate_num (),
```
Comment (philberty) [inline gcc/rust/privacy/rust-visibility-resolver.cc:85]: also this will get simplified down the line to not require the crate num here but this is fine for now

**Review by philberty — APPROVED** [review]
Still looks good :D

**Comment by CohenArthur** [comment]
bors cancel
