### PR TITLE
Match tokens in macros more closely

### LINKED ISSUE #2264: Literals are not compared correctly in macros
I tried this code:

```rust
macro_rules! m {
    (1) => {};
}

m!(2);
```

I expected to see this happen: an error (rustc produces `error: no rules expected the token `2``)

Instead, this happened:  compiles successfully

### Meta

- What version of Rust GCC were you using, git sha if possible.
2d806801404fc7628a3d022da92b73cd06197f49

### PR DESCRIPTION
**Pull request by powerboat9**
Fixes #2264

### CODE REVIEW

File: gcc/testsuite/rust/compile/macro-issue2264.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+macro_rules! m {
```
Comment (matthewjasper) [inline gcc/testsuite/rust/compile/macro-issue2264.rs:1]: Can you add a similar test with identifiers instead of integer literals?

Comment (powerboat9) [reply gcc/testsuite/rust/compile/macro-issue2264.rs]: Modified the test

**Review by CohenArthur — APPROVED** [review]
LGTM, thank you!
