### PR TITLE
Fix name resolution for enums with generics

### LINKED ISSUE #3304: Generics with Enums does not work with name resolution 2.0
Sorry if this is a duplicate, I tried looking for similar ice patterns or issue names. I didn't find anything.

### Code

```rust
// Works fine
pub struct Bob<T> {
    Bleh: T,
}

// Causes ICE
pub enum ROption<T> {
    RSome(T),
    RNone,
}

fn main() {}
```

### Meta

daa2977f3d52968506a396523f47ab52e0e3a90a

### Error output

```
None
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
TRS-E14 gccrs-build $ gccrs -frust-name-resolution-2.0 simple_gen2.rs
crab1: internal compiler error: in visit, at rust/resolve/rust-late-name-resolver-2.0.cc:285
0x189d030 Rust::Resolver2_0::Late::visit(Rust::AST::TypePath&)
	../../gccrs/gcc/rust/resolve/rust-late-name-resolver-2.0.cc:285
0x163dccb Rust::AST::TypePath::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-path.cc:363
0x16693a5 void Rust::AST::DefaultASTVisitor::visit<Rust::AST::Type>(Rust::AST::Type&)
	../../gccrs/gcc/rust/ast/rust-ast-visitor.h:406
0x166583a Rust::AST::DefaultASTVisitor::visit(Rust::AST::TupleField&)
	../../gccrs/gcc/rust/ast/rust-ast-visitor.cc:884
0x1665aea Rust::AST::DefaultASTVisitor::visit(Rust::AST::EnumItemTuple&)
	../../gccrs/gcc/rust/ast/rust-ast-visitor.cc:912
0x155abe5 Rust::AST::EnumItemTuple::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast.cc:4759
0x166cc3d void Rust::AST::DefaultASTVisitor::visit<Rust::AST::EnumItem>(std::unique_ptr<Rust::AST::EnumItem, std::default_delete<Rust::AST::EnumItem> >&)
	../../gccrs/gcc/rust/ast/rust-ast-visitor.h:410
0x1665db9 Rust::AST::DefaultASTVisitor::visit(Rust::AST::Enum&)
	../../gccrs/gcc/rust/ast/rust-ast-visitor.cc:940
0x187d22a operator()
	../../gccrs/gcc/rust/resolve/rust-default-resolver.cc:106
0x187f52b __invoke_impl<void, Rust::Resolver2_0::DefaultResolver::visit(Rust::AST::Enum&)::<lambda()>&>
	/usr/include/c++/14.2.1/bits/invoke.h:61
0x187ed3c __invoke_r<void, Rust::Resolver2_0::DefaultResolver::visit(Rust::AST::Enum&)::<lambda()>&>
	/usr/include/c++/14.2.1/bits/invoke.h:111
0x187e140 _M_invoke
	/usr/include/c++/14.2.1/bits/std_function.h:290
0x1877cdf std::function<void ()>::operator()() const
	/usr/include/c++/14.2.1/bits/std_function.h:591
0x1876a34 Rust::Resolver2_0::NameResolutionContext::scoped(Rust::Resolver2_0::Rib::Kind, unsigned int, std::function<void ()>, tl::optional<Rust::Identifier>)
	../../gccrs/gcc/rust/resolve/rust-name-resolution-context.cc:115
0x187d2ee Rust::Resolver2_0::DefaultResolver::visit(Rust::AST::Enum&)
	../../gccrs/gcc/rust/resolve/rust-default-resolver.cc:108
0x155ac81 Rust::AST::Enum::accept_vis(Rust::AST::ASTVisitor&)
	../../gccrs/gcc/rust/ast/rust-ast.cc:4777
0x189c342 Rust::Resolver2_0::Late::go(Rust::AST::Crate&)
	../../gccrs/gcc/rust/resolve/rust-late-name-resolver-2.0.cc:114
0x168fcff Rust::Session::compile_crate(char const*)
	../../gccrs/gcc/rust/rust-session-manager.cc:635
0x168f290 Rust::Session::handle_input_files(int, char const**)
	../../gccrs/gcc/rust/rust-session-manager.cc:418
0x14fdfc2 grs_langhook_parse_file
	../../gccrs/gcc/rust/rust-lang.cc:165
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
  ```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by liamnaddell**
Fixes #3304
Here is a checklist to help you with your PR.

- \[x] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[x] Read contributing guidlines
- \[x] `make check-rust` passes locally
- \[x] Run `clang-format`
- \[x] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

### CODE REVIEW

**Comment by liamnaddell** [comment]
Not quite sure if it's appropriate to add a test case for this. It seems like we already have testcases involving enum+Generic, they just weren't run with NR2.0. See, for example issue-850.rs, issue-2105.rs, etc

**Review by CohenArthur — APPROVED** [review]
thanks! this looks great

**Comment by powerboat9** [comment]
Looks good -- should probably add the visitor to `DefaultResolver` instead of `Late` and modify `TopLevel::visit` to use `DefaultResolver`

**Comment by liamnaddell** [comment]
> Looks good -- should probably add the visitor to `DefaultResolver` instead of `Late` and modify `TopLevel::visit(Enum &)` to use `DefaultResolver::visit(Enum &)`

Are you referring to this? I can see how it would make sense to add this to DefaultResolver

```c++
  auto generic_vis = [this, &enum_item] () {
    for (auto &g : enum_item.get_generic_params ())
      {
	g->accept_vis (*this);
      }
  };

  ctx.scoped (Rib::Kind::Item, enum_item.get_node_id (), generic_vis);
  ```

**Comment by powerboat9** [comment]
Yes, I think `DefaultResolver` already takes care of that

**Comment by liamnaddell** [comment]
> Yes, I think `DefaultResolver` already takes care of that

It didn't seem to from my look. I checked lines 101-110 of DefaultResover, and saw:

```c++
101 void
102 DefaultResolver::visit (AST::Enum &type)
103 {
104   // FIXME: Do we need to scope anything by default?
105
106   auto variant_fn = [this, &type] () { AST::DefaultASTVisitor::visit (type); };
107
108   ctx.scoped (Rib::Kind::Item /* FIXME: Correct? */, type.get_node_id (),
109         variant_fn, type.get_identifier ());
110 }
```

**Comment by liamnaddell** [comment]
> > Yes, I think `DefaultResolver` already takes care of that
> 
> It didn't seem to from my look. I checked lines 101-110 of DefaultResover, and saw:
> 
> ```c++
> 101 void
> 102 DefaultResolver::visit (AST::Enum &type)
> 103 {
> 104   // FIXME: Do we need to scope anything by default?
> 105
> 106   auto variant_fn = [this, &type] () { AST::DefaultASTVisitor::visit (type); };
> 107
> 108   ctx.scoped (Rib::Kind::Item /* FIXME: Correct? */, type.get_node_id (),
> 109         variant_fn, type.get_identifier ());
> 110 }
> ```

Granted I am new to this part of the codebase, so it's possible I'm missing something.

**Comment by powerboat9** [comment]
Ah, yeah, it delegates that out to `DefaultASTVisitor::visit`

File: gcc/testsuite/rust/compile/issue-3307.rs
Comment (CohenArthur) [inline gcc/testsuite/rust/compile/issue-3307.rs:1]: I would rename this file `issue-3304.rs` instead, as 3307 is this PR and not the issue itself

File: gcc/testsuite/rust/compile/issue-3307.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#[lang = "sized"]
+trait Sized {}
```
Comment (CohenArthur) [inline gcc/testsuite/rust/compile/issue-3307.rs:2]:
```suggestion
// { dg-additional-options "-frust-name-resolution-2.0" }

#[lang = "sized"]
trait Sized {}
```

File: gcc/testsuite/rust/compile/issue-3307.rs
Comment (liamnaddell) [reply gcc/testsuite/rust/compile/issue-3307.rs:1]: :facepalm: I fixed this

File: gcc/testsuite/rust/compile/issue-3307.rs (hunk 1 above)
Comment (liamnaddell) [reply gcc/testsuite/rust/compile/issue-3307.rs]: I added this patch. Wouldn't this cause issue-3304.rs to be run with NR2.0 twice?

Comment (powerboat9) [reply gcc/testsuite/rust/compile/issue-3307.rs]: Yes, but it shouldn't matter -- that line should be alright either present or not present

Comment (liamnaddell) [reply gcc/testsuite/rust/compile/issue-3307.rs]: I agree, I'm happy to keep it there since it clarifies that this is specifically a NR2.0 test

File: gcc/testsuite/rust/compile/issue-3307.rs
Comment (CohenArthur) [reply gcc/testsuite/rust/compile/issue-3307.rs:1]: no worries it's all good :D
