### PR TITLE
builtin-derive-macros: Add dummy builtin transcriber for builtin derive macros.

### LINKED ISSUE #2257: Inserting builtin macro transcribers for builtin derive macros causes ICE
I tried this code:

```rust
#[rustc_builtin_macro]
#[stable(feature = "rust1", since = "1.0.0")]
#[allow_internal_unstable(core_intrinsics, libstd_sys_internals)]
pub macro RustcDecodable($item:item) {
    /* compiler built-in */
}
```

I expected to see this happen: no error

Instead, this happened:
```rust
crab1: internal compiler error: Segmentation fault
0x402237c crash_signal(int)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/toplev.cc:314
0x1f742cc std::_Function_base::_M_empty() const
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:247
0x1f742a4 std::function<Rust::AST::Fragment (Location, Rust::AST::MacroInvocData&)>::operator bool() const
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:574
0x1f73c51 std::function<Rust::AST::Fragment (Location, Rust::AST::MacroInvocData&)>::function(std::function<Rust::AST::Fragment (Location, Rust::AST::MacroInvocData&)> const&)
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:389
0x2141ffc Rust::Analysis::Mappings::insert_macro_def(Rust::AST::MacroRulesDefinition*)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/util/rust-hir-map.cc:892
0x21b4e7e Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MacroRulesDefinition&)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/resolve/rust-early-name-resolver.cc:902
0x1f31920 Rust::AST::MacroRulesDefinition::accept_vis(Rust::AST::ASTVisitor&)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/ast/rust-ast.cc:4819
0x21b6aa5 Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2::operator()() const
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/resolve/rust-early-name-resolver.cc:104
0x21b6a14 void std::__invoke_impl<void, Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2&>(std::__invoke_other, Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2&)
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:61
0x21b69c4 std::enable_if<__and_<std::is_void<void>, std::__is_invocable<Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2&> >::value, void>::type std::__invoke_r<void, Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2&>(Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2&)
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:154
0x21b68ec std::_Function_handler<void (), Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)::$_2>::_M_invoke(std::_Any_data const&)
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:290
0x21ba444 std::function<void ()>::operator()() const
	/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
0x21b9fec Rust::Resolver::EarlyNameResolver::scoped(unsigned int, std::function<void ()>)
	../../gcc/rust/resolve/rust-early-name-resolver.h:50
0x21b178e Rust::Resolver::EarlyNameResolver::go(Rust::AST::Crate&)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/resolve/rust-early-name-resolver.cc:102
0x2049233 Rust::Session::expansion(Rust::AST::Crate&)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:874
0x2047aaf Rust::Session::compile_crate(char const*)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:582
0x2047417 Rust::Session::handle_input_files(int, char const**)
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-session-manager.cc:398
0x1ed2c36 grs_langhook_parse_file()
	/home/arthur/Git/rust-gcc/gccrs/build/gcc/../../gcc/rust/rust-lang.cc:183
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

This is caused by the Early Name Resolver inserting a non-existing builtint transcriber for the `RustcEncodable` builtin derive macro. That transcriber will never be used, because builtin derive macros do not work on tokens - so we can add a dummy/empty transcriber to the builtin derive macros.

### Meta

- What version of Rust GCC were you using, git sha if possible.

1eef15537f2

### PR DESCRIPTION
**Pull request by CohenArthur**
Fixes #2257.

Derive builtins do not need a real transcriber, but still need one. It
will however never be called since builtin derive macros get expanded
differently, and benefit from knowing on what kind of items they are
applied (struct, enums, unions) rather than receiving a list of tokens
like regular builtin macros.

gcc/rust/ChangeLog:

	* expand/rust-macro-builtins.cc (MacroBuiltin::dummy): New function.
	* expand/rust-macro-builtins.h: Declare it.

gcc/testsuite/ChangeLog:

	* rust/compile/derive_macro7.rs: New test.

### CODE REVIEW

File: gcc/rust/expand/rust-macro-builtins.cc [hunk 1]
```diff
@@ -105,6 +105,22 @@ std::unordered_map<
     {"test_case", MacroBuiltin::sorry},
     {"global_allocator", MacroBuiltin::sorry},
     {"cfg_accessible", MacroBuiltin::sorry},
+    /* Derive builtins do not need a real transcriber, but still need one. It
+       will however never be called since builtin derive macros get expanded
+       differently, and benefit from knowing on what kind of items they are
+       applied (struct, enums, unions) rather than receiving a list of tokens
+       like regular builtin macros */
+    {"RustcEncodable", MacroBuiltin::dummy},
```
Comment (philberty) [inline gcc/rust/expand/rust-macro-builtins.cc:113]: I wonder should it be called MacroBuiltin::builtinDerive maybe. Hmm not sure I like that either lol

**Review by philberty — APPROVED** [review]
LGTM comment is probably enough here, maybe another comment around the declaration for the dummy function would be good too to say yeah these can be for builtin derive macros.

File: gcc/rust/expand/rust-macro-builtins.cc (hunk 1 above)
Comment (CohenArthur) [reply gcc/rust/expand/rust-macro-builtins.cc:113]: I think `MacroBuiltin::proc_macro_builtin` would be better maybe, since we'll need to apply it to macros like `#[test]` too

Comment (CohenArthur) [reply gcc/rust/expand/rust-macro-builtins.cc]: @philberty let me know what you think about that name and I'll merge this :)

**Review by P-E-P — APPROVED** [review]
