### PR TITLE
gccrs: add {add,sub,mul}_with_overflow intrinsics

### LINKED ISSUE #1898: Support overflowing_add in libcore
I tried this code:

```rust
mod intrinsics {
    extern "rust-intrinsic" {
        pub fn add_with_overflow<T>(x: T, y: T) -> (T, bool);
    }
}

pub enum Option<T> {
    None,
    Some(T),
}

#[lang = "i32"]
impl i32 {
    pub fn checked_add(self, rhs: Self) -> Option<Self> {
        let (a, b) = self.overflowing_add(rhs);
        if b {
            Option::None
        } else {
            Option::Some(a)
        }
    }

    pub fn overflowing_add(self, rhs: Self) -> (Self, bool) {
        let (a, b) = unsafe { intrinsics::add_with_overflow(self as i32, rhs as i32) };
        (a as Self, b)
    }
}
```

I expected to see this happen: compile without error

- [ ] #1896 
- [x] #1897

```
test.rs:24:31: error: unknown builtin intrinsic: add_with_overflow
   24 |         let (a, b) = unsafe { intrinsics::add_with_overflow(self as i32, rhs as i32) };
      |                               ^~~~~~~~~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

### PR DESCRIPTION
**Pull request by philberty**
Fixes #1898

Signed-off-by: Philip Herron <herron.philip@googlemail.com>

gcc/rust/ChangeLog:

	* backend/rust-compile-intrinsic.cc (op_with_overflow_inner): (std::function<tree): new wrapper over op_with_overflow (op_with_overflow): generate the intrinsic based on the tree_code op

gcc/testsuite/ChangeLog:

	* rust/compile/torture/intrinsics-8.rs: New test.

### CODE REVIEW

File: gcc/rust/backend/rust-compile-intrinsic.cc [hunk 1]
```diff
@@ -558,6 +572,96 @@ wrapping_op_handler_inner (Context *ctx, TyTy::FnType *fntype, tree_code op)
   return fndecl;
 }
 
+/**
+ * pub fn add_with_overflow<T>(x: T, y: T) -> (T, bool);
+ */
+static tree
+op_with_overflow_inner (Context *ctx, TyTy::FnType *fntype, tree_code op)
+{
+  // wrapping_<op> intrinsics have two parameter
```
Comment (CohenArthur) [inline gcc/rust/backend/rust-compile-intrinsic.cc:581]:
```suggestion
  // <op>_with_overflow intrinsics have two parameters
```

**Review by CohenArthur — APPROVED** [review]
Nice! LGTM :D It'd be good I think to have a test to make sure the values returned are the same as rustc. Since we have `-fwrapv` by default I think this should be the case but just to make sure and not introduce regressions later on

**Review by P-E-P — APPROVED** [review]
Looks fine :+1:
