### PR TITLE
Avoid invalid metavariable substitutions

### LINKED ISSUE #2225: Lacking error on use of undefined metavariable
I tried this code:

```rust
macro_rules! foo {
    () => {
        let $_a = 12;
    }
}

pub fn main() {
    foo!();
}
```

I expected to see this happen:

```
error: expected pattern, found `$`
 --> src/main.rs:3:13
  |
3 |         let $a = 12;
  |             ^^ expected pattern
...
8 |     foo!();
  |     ------ in this macro invocation
  |
```

Instead, this happened: no error

### PR DESCRIPTION
**Pull request by powerboat9**
Fixes #2225 by improving metavariable substitution

### CODE REVIEW

**Review by philberty — APPROVED** [review]
LGTM

File: gcc/rust/expand/rust-macro-substitute-ctx.h [hunk 1]
```diff
@@ -49,12 +49,13 @@ class SubstituteCtx
    * i.e. replacing $var with the associated fragment.
    *
    * @param metavar Metavariable to try and replace
+   * @param expanded Reference to a vector upon which expanded tokens will be
+   * pushed
    *
-   * @return A token containing the associated fragment expanded into tokens if
-   * any, or the cloned token if no fragment was associated
+   * @return True iff the substitution succeeded
```
Comment (CohenArthur) [inline gcc/rust/expand/rust-macro-substitute-ctx.h:55]:
```suggestion
   * @return true if the substitution succeeded, false otherwise
```

**Review by CohenArthur — COMMENTED** [review]
Nice work, one tiny nitpick (sorry I was away when you submitted this PR!) if you want to fix that in a subsequent PR but all good otherwise
