### PR TITLE
gccrs: Fix negative bounds in `RangePattern` being handled incorrectly

### LINKED ISSUE #3659: ICE: in visit, at rust/hir/rust-ast-lower-pattern.cc:258 exlusive range pattern
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -frust-incomplete-and-experimental-compiler-do-not-use
#![feature(exclusive_range_pattern)]

fn main() {
    let x = 3;

    match x {
        0..-1 => 2,
        _ => 3,
    };
}

````

original:
````rust
// Make sure redundant testing paths in `match` expressions are sorted out.

#![feature(exclusive_range_pattern)]

// EMIT_MIR match_test.main.SimplifyCfg-initial.after.mir
fn main() {
    let x = 3;
    let b = true;

    // When `(0..=10).contains(x) && !b`, we should jump to the last arm
    // without testing two other candidates.
    match x {
        0..10 if b..=20 => 1,
        -1 => 2,
        _ => 3,
    };
}

````

Version information:

765121736dfe3f5b319bbe9837880deda326394e

Possibly related line of code:
https://github.com/Rust-GCC/gccrs/blob/765121736dfe3f5b319bbe9837880deda326394e/gcc/rust/hir/rust-ast-lower-pattern.cc#L252-L264

Command:
`/home/matthias/vcs/github/gccrs/gccrs-build/gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use`

<details><summary><strong>Program output</strong></summary>
<p>

```
crab1: internal compiler error: in visit, at rust/hir/rust-ast-lower-pattern.cc:258
0x88ca23 Rust::HIR::ASTLoweringPattern::visit(Rust::AST::RangePattern&)
	../../gcc/rust/hir/rust-ast-lower-pattern.cc:258
0xe6bd46 Rust::HIR::ASTLoweringPattern::translate(Rust::AST::Pattern&, bool)
	../../gcc/rust/hir/rust-ast-lower-pattern.cc:33
0xe5d52e Rust::HIR::ASTLoweringExprWithBlock::visit(Rust::AST::MatchExpr&)
	../../gcc/rust/hir/rust-ast-lower.cc:446
0xe7e908 Rust::HIR::ASTLoweringExprWithBlock::translate(Rust::AST::ExprWithBlock&, bool*)
	../../gcc/rust/hir/rust-ast-lower-block.h:153
0xe7e908 Rust::HIR::ASTLoweringExpr::visit(Rust::AST::MatchExpr&)
	../../gcc/rust/hir/rust-ast-lower-expr.cc:689
0xe87322 Rust::HIR::ASTLoweringExpr::translate(Rust::AST::Expr&, bool*)
	../../gcc/rust/hir/rust-ast-lower-expr.cc:43
0xe92bb7 Rust::HIR::ASTLoweringStmt::visit(Rust::AST::ExprStmt&)
	../../gcc/rust/hir/rust-ast-lower-stmt.cc:50
0xe93247 Rust::HIR::ASTLoweringStmt::translate(Rust::AST::Stmt*, bool*)
	../../gcc/rust/hir/rust-ast-lower-stmt.cc:33
0xe5c00e Rust::HIR::ASTLoweringBlock::visit(Rust::AST::BlockExpr&)
	../../gcc/rust/hir/rust-ast-lower.cc:122
0xe6e3ea Rust::HIR::ASTLoweringBlock::translate(Rust::AST::BlockExpr&, bool*)
	../../gcc/rust/hir/rust-ast-lower-block.h:37
0xe6e3ea Rust::HIR::ASTLoweringItem::visit(Rust::AST::Function&)
	../../gcc/rust/hir/rust-ast-lower-item.cc:444
0xe6f11e Rust::HIR::ASTLoweringItem::translate(Rust::AST::Item&)
	../../gcc/rust/hir/rust-ast-lower-item.cc:38
0xe5cba7 Rust::HIR::ASTLowering::go()
	../../gcc/rust/hir/rust-ast-lower.cc:81
0xe5d0a1 Rust::HIR::ASTLowering::Resolve(Rust::AST::Crate&)
	../../gcc/rust/hir/rust-ast-lower.cc:71
0xce8eb8 Rust::Session::compile_crate(char const*)
	../../gcc/rust/rust-session-manager.cc:663
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

```

</p>
</details>

### LINKED ISSUE #4242: Negative value bounds does not generate correctly for `RangePattern`
Negative literal value bounds in a `RangePattern` are not being compiled properly and are always treated as positive values.

Code was adapted from #3659:

```rust
#![feature(exclusive_range_pattern)]

fn main() {
    let x = 1;

    match x {
        0..-55 => 2,
        -55..-99 => 3,
        -55..0 => 3,
    };
}
```

Resultant GIMPLE:

```cpp
...
  x = 1;
  RUSTTMP.2 = x;
  _1 = RUSTTMP.2 >= 0;
  _2 = RUSTTMP.2 <= 54;
  _3 = _1 & _2;
  if (_3 != 0) goto <D.115>; else goto <D.116>;
  <D.115>:
  { ... }
  <D.116>:
  _4 = RUSTTMP.2 > 54;
  _5 = RUSTTMP.2 <= 98;
  _6 = _4 & _5;
  if (_6 != 0) goto <D.117>; else goto <D.118>;
  <D.117>:
  { ... }
  <D.118>:
  if (0 != 0) goto <D.119>; else goto <D.120>;
  <D.119>:
  { ... }
...
```

### PR DESCRIPTION
**Pull request by Polygonalr**
Fixes #4242
Fixes #3659

The ICE for #3659 was initially fixed by #4049, but the test case did not throw [E0579](https://doc.rust-lang.org/error_codes/E0579.html) as expected. Moreover, the output GIMPLE was found to be wrong (which led to the creation of #4242). This PR aims to fix both issues by correcting parser behavior for `RangePattern`-s and adding E0579 error checking.

### CODE REVIEW

File: gcc/rust/hir/tree/rust-hir-pattern.h [hunk 1]
```diff
@@ -234,24 +234,19 @@ class RangePatternBoundLiteral : public RangePatternBound
   /* Can only be a char, byte, int, or float literal - same impl here as
    * previously */
 
-  // Minus prefixed to literal (if integer or floating-point)
-  bool has_minus;
```
Comment (philberty) [inline gcc/rust/hir/tree/rust-hir-pattern.h:238]: Do you not need this anymore? How do you track it?

**Review by philberty — COMMENTED** [review]
I think LGTM but not sure how it works now with the has_minus removed

File: gcc/rust/hir/tree/rust-hir-pattern.h (hunk 1 above)
Comment (powerboat9) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: It looks like `Literal` instances are constructed such that their contents are prepended with `"-"` -- which ~probably works anyways, but I don't think the gccrs-front-end-back-end strictly expects it

Comment (powerboat9) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: It would probably be best to have range expressions store subexpressions instead of wrapped literals

Comment (Polygonalr) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: > Do you not need this anymore? How do you track it?

`has_minus` is not being used at all, which is why I opted for it to be removed. As @powerboat9 mentioned, the parser is updated to directly store negative values into `Literal` objects.

> It would probably be best to have range expressions store subexpressions instead of wrapped literals

I'm not too sure about that, considering expressions (and runtime values in general) are not supported in range patterns in rustc.

Comment (powerboat9) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: Ah, yeah, it looks like I got this mixed up with range expressions.

https://doc.rust-lang.org/reference/patterns.html#grammar-LiteralPattern
https://doc.rust-lang.org/reference/patterns.html#grammar-RangePattern

It looks like literal patterns should actually support a minus sign in addition to the literal they contain, so we probably have a similar bug when it comes to those.

Comment (Polygonalr) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: Ooo, nice that you pointed out the grammar for `RangePatternBound` should resolve into `LiteralPattern`, which resolves into `-`<sup>?</sup>`LiteralExpression`. If we want to follow the reference's grammar strictly, I guess I can revert the removal of `has_minus` (though I think the code to handle negative values in `RangePatternBoundLiteral` may become a little uglier).

> It looks like literal patterns should actually support a minus sign in addition to the literal they contain, so we probably have a similar bug when it comes to those.

The answer is also **yes** (due to the lack of minus sign tracking present even before this PR). More things to work on for this PR I guess.

The following Rust code:

```rust
fn main() {
    let x = 1;

    match x {
        -55 => 2,
        -99 => 3
    };
}
```

Compiles into

```cpp
...
  RUSTTMP.2 = x;
  if (RUSTTMP.2 == 55) goto <D.110>; else goto <D.111>;
  <D.110>:
  {
    RUSTTMP.1 = 2;
    goto <D.105>;
  }
  <D.111>:
  if (RUSTTMP.2 == 99) goto <D.112>; else goto <D.113>;
  <D.112>:
  {
    RUSTTMP.1 = 3;
    goto <D.105>;
  }
...
```

Comment (Polygonalr) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: > https://doc.rust-lang.org/reference/patterns.html#railroad-LiteralPattern

 > Since negative numbers are not [literals](https://doc.rust-lang.org/reference/expressions/literal-expr.html),

TIL

Comment (Polygonalr) [reply gcc/rust/hir/tree/rust-hir-pattern.h:238]: Changed in my latest update, compilation of the literal bound uses the `has_minus` boolean properly.

File: gcc/rust/backend/rust-compile-pattern.cc [hunk 2]
```diff
@@ -159,6 +161,30 @@ CompilePatternCheckExpr::visit (HIR::RangePattern &pattern)
 					    pattern.get_mappings (),
 					    pattern.get_locus (), ctx);
 
+  rust_assert (
+    (TREE_CODE (upper) == REAL_CST && TREE_CODE (lower) == REAL_CST)
+    || (TREE_CODE (upper) == INTEGER_CST && TREE_CODE (lower) == INTEGER_CST));
```
Comment (powerboat9) [inline gcc/rust/backend/rust-compile-pattern.cc:166]: Does `1f32..1.2f32` break anything?

Comment (Polygonalr) [reply gcc/rust/backend/rust-compile-pattern.cc:166]: Triggers an error that shouldn't be triggered lol, maybe we can create a new issue for it.

```rust
error: mismatched types, expected ‘f32’ but got ‘<integer>’ [E0308]
    7 |         1f32..1.2f32 => 1,
      |         ^~~~
```

Anyways, `1.0f32..1.2f32` compiles properly and does not trigger E0579 but `-1.2f32..-1.0f32` triggers E0579... not sure what went wrong here :/

Comment (philberty) [reply gcc/rust/backend/rust-compile-pattern.cc:166]: probably something thats doing a unify but should be doing a cast_site which can fall back to a coercion possibly
