### PR TITLE
gccrs:fix ICE with continue/break/return in while condition

### LINKED ISSUE #3977: ICE in fold_convert_loc, at fold-const.cc:2662
### Code

```rust
fn main() {
    loop {
        while continue {}
    }
}

```

### Version information

```
5dc8c4d
```

### Command

```
./gcc/crab1 ../test.rs -frust-debug -frust-dump-ast-pretty -Warray-bounds -dumpbase ../test.rs -mtune=generic -march=x86-64 -O0 -version -fdump-tree-gimple -o test.s -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -frust-incomplete-and-experimental-compiler-do-not-use
```

### Program output
```
./test.rs: In function ‘test::main’:
./test.rs:3:9: internal compiler error: in fold_convert_loc, at fold-const.cc:2662
    3 |         while continue {}
      |         ^~~~~
0x29abeb6 internal_error(char const*, ...)
        ../../gccrs/gcc/diagnostic-global-context.cc:517
0xb48036 fancy_abort(char const*, int, char const*)
        ../../gccrs/gcc/diagnostic.cc:1803
0x9618c0 fold_convert_loc(unsigned long, tree_node*, tree_node*)
        ../../gccrs/gcc/fold-const.cc:2662
0x128880a gimple_boolify(tree_node*)
        ../../gccrs/gcc/gimplify.cc:5340
0x12ba21b gimplify_cond_expr
        ../../gccrs/gcc/gimplify.cc:5548
0x129dd43 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ../../gccrs/gcc/gimplify.cc:19743
0x129f8aa gimplify_stmt(tree_node**, gimple**)
        ../../gccrs/gcc/gimplify.cc:8461
0x129c68b gimplify_statement_list
        ../../gccrs/gcc/gimplify.cc:2288
0x129c68b gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ../../gccrs/gcc/gimplify.cc:20240
0x129f8aa gimplify_stmt(tree_node**, gimple**)
        ../../gccrs/gcc/gimplify.cc:8461
0x12a0951 gimplify_bind_expr
        ../../gccrs/gcc/gimplify.cc:1683
0x129cb60 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ../../gccrs/gcc/gimplify.cc:19990
0x129f8aa gimplify_stmt(tree_node**, gimple**)
        ../../gccrs/gcc/gimplify.cc:8461
0x129cc8a gimplify_and_add(tree_node*, gimple**)
        ../../gccrs/gcc/gimplify.cc:550
0x129cc8a gimplify_loop_expr
        ../../gccrs/gcc/gimplify.cc:2262
0x129cc8a gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ../../gccrs/gcc/gimplify.cc:19994
0x129f8aa gimplify_stmt(tree_node**, gimple**)
        ../../gccrs/gcc/gimplify.cc:8461
0x129c68b gimplify_statement_list
        ../../gccrs/gcc/gimplify.cc:2288
0x129c68b gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ../../gccrs/gcc/gimplify.cc:20240
0x129f8aa gimplify_stmt(tree_node**, gimple**)
        ../../gccrs/gcc/gimplify.cc:8461
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by Harishankar14**
Fixes ICE when continue/break/return/loop are used as while conditions.

Fixes #3977

The predicate expression must be evaluated before type checking to ensure side effects occur even when the predicate has `Never` type. This prevents skipping function calls, panics, or other side effects in diverging predicates.

### Proof of fix using `-fdump-tree-gimple`

As requested, here is the GIMPLE dump for the test case `while loop {} {}`. It confirms that the infinite loop side-effect is preserved correctly:

```c
__attribute__((cdecl))
struct () test::main ()
{
  struct () D.107;

  <D.101>:
  <D.103>:
  {
    <D.104>:
    {
      <D.102>:
      goto <D.102>; // Side-effect correctly preserved
      if (0 != 0) goto <D.105>; else goto <D.106>;
      <D.106>:
      {

      }
    }
    goto <D.104>;
    <D.105>:
  }
  goto <D.103>;
  return D.107;
}
```
Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

### CODE REVIEW

**Comment by powerboat9** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=f4db2628116a78ca94e09a3cf1bcfb21

Having a predicate of type `!` should work -- it gets coerced into a boolean. See https://doc.rust-lang.org/reference/types/never.html, though don't get confused by the last paragraph

**Comment by Harishankar14** [comment]
@powerboat9 Thanks for the feedback! I dont really know how did i miss this.. I've updated the fix to properly handle never-type coercion. Instead of rejecting continue as a value, the compiler now:

Detects when the while predicate has type ! (never)
Coerces it to bool by treating it as true (infinite loop)
Issues a warning about unreachable code

**Comment by Harishankar14** [comment]
@powerboat9, @philberty

File: gcc/rust/backend/rust-compile-expr.cc [hunk 1]
```diff
@@ -802,8 +802,24 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+  bool ok = ctx->get_tyctx()->lookup_type(predicate.get_mappings().get_hirid(), &predicate_type);
+  bool is_diverging = false;
+  if (ok && predicate_type !=nullptr){
+    is_diverging = (predicate_type->get_kind() == TyTy::TypeKind::NEVER 
+                    || predicate_type->get_kind() == TyTy::TypeKind::ERROR);
+  }
+  tree condition;
+  if (is_diverging){
+    condition = boolean_true_node;
+  }else{
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: the code formatting looks wrong  you need to use clang format

File: gcc/rust/backend/rust-compile-expr.cc [hunk 2]
```diff
@@ -802,8 +802,24 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
   ctx->add_statement (loop_begin_label_decl);
   ctx->push_loop_begin_label (loop_begin_label);
-
-  tree condition = CompileExpr::Compile (expr.get_predicate_expr (), ctx);
+  
+  HIR::Expr &predicate = expr.get_predicate_expr ();
+  TyTy::BaseType *predicate_type = nullptr;
+  bool ok = ctx->get_tyctx()->lookup_type(predicate.get_mappings().get_hirid(), &predicate_type);
+  bool is_diverging = false;
+  if (ok && predicate_type !=nullptr){
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: i would do rust_assert (ok and != nullptr) this would be an ICE if it happened

File: gcc/rust/backend/rust-compile-expr.cc [hunk 3]
```diff
@@ -802,8 +802,24 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+    is_diverging = (predicate_type->get_kind() == TyTy::TypeKind::NEVER
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: not sure why your checking for error surely we just use error_mark_node if that happens?

File: gcc/rust/backend/rust-compile-expr.cc [hunk 4]
```diff
@@ -802,8 +802,24 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+  HIR::Expr &predicate = expr.get_predicate_expr ();
+  TyTy::BaseType *predicate_type = nullptr;
+  bool ok = ctx->get_tyctx()->lookup_type(predicate.get_mappings().get_hirid(), &predicate_type);
+  bool is_diverging = false;
+  if (ok && predicate_type !=nullptr){
+    is_diverging = (predicate_type->get_kind() == TyTy::TypeKind::NEVER 
+                    || predicate_type->get_kind() == TyTy::TypeKind::ERROR);
+  }
+  tree condition;
+  if (is_diverging){
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: i think this becomes:

if (predicate_type->is<TyTy::NeverType> ()) 

I think reads better

File: gcc/rust/backend/rust-compile-expr.cc [hunk 5]
```diff
@@ -802,8 +802,24 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+    condition = boolean_true_node;
+  }else{
+    condition = CompileExpr::Compile(predicate,ctx);
+    if(condition == error_mark_node || TREE_TYPE(condition) == NULL_TREE){
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: hmm checking for TREE_TYPE null seems odd.. surely its just if error_mark_node? if not you should add a comment

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc [hunk 6]
```diff
@@ -1541,18 +1541,39 @@ void
...
   TyTy::BaseType *block_expr = TypeCheckExpr::Resolve (expr.get_loop_block ());
-
   if (!block_expr->is_unit ())
     {
       rust_error_at (expr.get_loop_block ().get_locus (),
-		     "expected %<()%> got %s",
-		     block_expr->as_string ().c_str ());
+         "expected %<()%> got %s",
+         block_expr->as_string ().c_str ());
+      infered = new TyTy::ErrorType (expr.get_mappings ().get_hirid ());
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-expr.cc]: i think the type check expression defaults infered to be an error type anyways I don't think you need this

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc [hunk 7]
```diff
@@ -1541,18 +1541,39 @@ void
...
+      context->pop_loop_context ();
+      return;
+    }
+  if (block_expr->get_kind () == TyTy::TypeKind::ERROR)
+    {
+      infered = new TyTy::ErrorType (expr.get_mappings ().get_hirid ());
+      context->pop_loop_context ();
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-expr.cc:1560]: same here the Resolve call checks for nullptr and makes an error type if you read the top of this file

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc [hunk 8]
```diff
@@ -1541,18 +1541,39 @@ void
 TypeCheckExpr::visit (HIR::WhileLoopExpr &expr)
 {
   context->push_new_while_loop_context (expr.get_mappings ().get_hirid ());
-
-  TypeCheckExpr::Resolve (expr.get_predicate_expr ());
+  TyTy::BaseType *predicate_type
+    = TypeCheckExpr::Resolve (expr.get_predicate_expr ());
+  if (predicate_type->get_kind () == TyTy::TypeKind::ERROR)
+    {
+      infered = new TyTy::ErrorType (expr.get_mappings ().get_hirid ());
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-expr.cc]: yeah just pop and return dont need to explicitly set error type here

**Review by philberty — CHANGES_REQUESTED** [review]
i think this can be simplified a fair bit but good job.

File: gcc/rust/backend/rust-compile-expr.cc (hunk 1 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: Fixed.

File: gcc/rust/backend/rust-compile-expr.cc (hunk 2 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: Fixed.

File: gcc/rust/backend/rust-compile-expr.cc (hunk 4 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: fixed

File: gcc/rust/backend/rust-compile-expr.cc (hunk 5 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: I was overcautious.. i guess.But i agree, with you. It was unwanted.
Fixed it.

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc (hunk 7 above)
Comment (Harishankar14) [reply gcc/rust/typecheck/rust-hir-type-check-expr.cc:1560]: Fixed.

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc (hunk 8 above)
Comment (Harishankar14) [reply gcc/rust/typecheck/rust-hir-type-check-expr.cc]: Fixed

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc (hunk 6 above)
Comment (Harishankar14) [reply gcc/rust/typecheck/rust-hir-type-check-expr.cc]: fixed.

**Comment by Harishankar14** [comment]
@philberty  LMK, if any changes required. Applied all the ones which you pointed out. :)

**Comment by Harishankar14** [comment]
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=f4db2628116a78ca94e09a3cf1bcfb21
> 
> Having a predicate of type `!` should work -- it gets coerced into a boolean. See https://doc.rust-lang.org/reference/types/never.html, though don't get confused by the last paragraph

@powerboat9 This should do, lmk your thoughts.

File: gcc/rust/backend/rust-compile-expr.cc [hunk 9]
```diff
@@ -803,7 +803,25 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+  HIR::Expr &predicate = expr.get_predicate_expr ();
+  TyTy::BaseType *predicate_type = nullptr;
+  bool ok
+    = ctx->get_tyctx ()->lookup_type (predicate.get_mappings ().get_hirid (),
+				      &predicate_type);
+  rust_assert (ok && predicate_type != nullptr);
+  tree condition;
+  if (predicate_type->get_kind () == TyTy::TypeKind::NEVER)
+    {
+      condition = boolean_true_node;
```
Comment (powerboat9) [inline gcc/rust/backend/rust-compile-expr.cc:816]: The predicate expression should still be evaluated, as otherwise code that executes but never returns is skipped and continued past.

Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc:816]: Hmm, interesting, i guess even though it returns nothing, might have side effects (like function calls) that should still execute, even though it never returns.I guess that is what you meant right @powerboat9

Comment (powerboat9) [reply gcc/rust/backend/rust-compile-expr.cc:816]: Yep. For example,

```rust
fn foo() {
    while panic!("stop immediately") {
        break
    }
    never_ever_call_this ();
}
```

Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc:816]: @powerboat9 understood, will fix it and let you know !!

Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc:816]: @powerboat9  I have done the changes, tested it out with few testcases and examples, works !! Sorry for the multiple request notif..Some bug within my side from github

Comment (powerboat9) [reply gcc/rust/backend/rust-compile-expr.cc:816]: It's alright. It looks like the code is still broken though -- if the condition doesn't actually make it into the final tree output, it won't make it into the final compiled program.

**Review by powerboat9 — CHANGES_REQUESTED** [review]

File: gcc/rust/backend/rust-compile-expr.cc (hunk 9 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc:816]: @powerboat9  Ah !! Sorry i pushed the wrong code. 
https://github.com/Rust-GCC/gccrs/pull/4270#discussion_r2531332395
My solution was l
```
if (condition == error_mark_node)
{
    condition = boolean_true_node;
}
else if (predicate_type->get_kind() == TyTy::TypeKind::NEVER)
{
    // The predicate was compiled and added to the tree.
    // For NEVER type, we need to ensure it's in the output, so explicitly add it
    ctx->add_statement(condition);
    condition = boolean_true_node;
}
```


Haven't committed or updated yet.. But yeah go through this and lmk !!

Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc:816]: `fn side_effect() ->i32{
           42
}`

`fn never_returns(_x: i32) -> ! {
    loop {}
}`

`fn test_nested() {
    while never_returns(side_effect()) {
        break;
    }
    // side_effect() must be compiled and evaluated before never_returns()
}`

`fn main() {
    if false {
        test_nested();
    }
}`

Test Output.
image

File: gcc/rust/typecheck/rust-hir-type-check-expr.cc [hunk 10]
```diff
@@ -1609,9 +1608,9 @@ TypeCheckExpr::visit (HIR::ContinueExpr &expr)
     {
       rust_error_at (expr.get_locus (), ErrorCode::E0268,
 		     "%<continue%> outside of a loop");
+      infered = new TyTy::ErrorType (expr.get_mappings ().get_hirid ());
```
Comment (powerboat9) [inline gcc/rust/typecheck/rust-hir-type-check-expr.cc]: Is this necessary?

Comment (Harishankar14) [reply gcc/rust/typecheck/rust-hir-type-check-expr.cc]: @powerboat9  that could be ignored tbh! Do you want me to remove it ??

File: gcc/rust/backend/rust-compile-expr.cc [hunk 11]
```diff
@@ -803,7 +803,23 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
   ctx->push_loop_begin_label (loop_begin_label);
 
-  tree condition = CompileExpr::Compile (expr.get_predicate_expr (), ctx);
+  HIR::Expr &predicate = expr.get_predicate_expr ();
+  TyTy::BaseType *predicate_type = nullptr;
+  bool ok
+    = ctx->get_tyctx ()->lookup_type (predicate.get_mappings ().get_hirid (),
+				      &predicate_type);
+  rust_assert (ok && predicate_type != nullptr);
+  tree condition;
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: you dont need to declare the variable seperate just do tree condition = CompileExpr::Compile (predicate, ctx)

File: gcc/rust/backend/rust-compile-expr.cc [hunk 12]
```diff
@@ -803,7 +803,23 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+  condition = CompileExpr::Compile (predicate, ctx);
+  if (condition == error_mark_node)
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc]: you can just ignore the case of condition == error mark node... because it will show up in -fdump-tree-gimple, not sure how it could error something else should spit out and error message so i would just do:

```
tree condition = CompileExpr::Compile (predicate, ctx);
if (predicate_type->get_kind() == TyTy::TypeKind::NEVER)
{
    // The predicate was compiled and added to the tree.
    // For NEVER type, we need to ensure it's in the output, so explicitly add it
    ctx->add_statement(condition);
    condition = boolean_true_node;
}
```

Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: @philberty  Resolved.

File: gcc/rust/backend/rust-compile-expr.cc (hunk 11 above)
Comment (Harishankar14) [reply gcc/rust/backend/rust-compile-expr.cc]: @philberty Haha yeah, that was ugly, fixed.

**Comment by Harishankar14** [comment]
> nearly there

Yeah completed as per your suggestions,waiting for your review @philberty

**Comment by philberty** [comment]
you need to fix the commit format CI is failing for you.

**Comment by Harishankar14** [comment]
> you need to fix the commit format CI is failing for you.

Yep, done  @philberty

File: gcc/rust/backend/rust-compile-expr.cc [hunk 13]
```diff
@@ -803,7 +803,18 @@ CompileExpr::visit (HIR::WhileLoopExpr &expr)
...
+  TyTy::BaseType *predicate_type = nullptr;
+  bool ok
+    = ctx->get_tyctx ()->lookup_type (predicate.get_mappings ().get_hirid (),
+				      &predicate_type);
+  rust_assert (ok && predicate_type != nullptr);
+  tree condition = CompileExpr::Compile (predicate, ctx);
+  if (predicate_type->get_kind () == TyTy::TypeKind::NEVER)
+    {
+      ctx->add_statement (condition);
+      condition = boolean_true_node;
```
Comment (philberty) [inline gcc/rust/backend/rust-compile-expr.cc:816]: i dont think this is right to just override to boolean_true_node it means the never expression will never get evaluated

Comment (powerboat9) [reply gcc/rust/backend/rust-compile-expr.cc:816]: I think `ctx->add_statement` takes care of that

**Review by philberty — DISMISSED** [review]
OK I think this is ready but before we merge can you show an example of -fdump-tree-gimple in the git commit message of what we are doing here for this senario? But also put it in the github description

**Comment by Harishankar14** [comment]
> OK I think this is ready but before we merge can you show an example of -fdump-tree-gimple in the git commit message of what we are doing here for this senario? But also put it in the github description

@philberty  modified it, should be okay ?

**Comment by Harishankar14** [comment]
@P-E-P
