### PR TITLE
Fix unresolved imports

### LINKED ISSUE #3486: NR2: Unresolved import
- issue-850.rs
- issue-855.rs
- iterators1.rs
- issue-3033.rs
- for-loop2.rs

### PR DESCRIPTION
**Pull request by P-E-P**
- [x] issue-850.rs
- [x] issue-855.rs
- [x] iterators1.rs
- [x] issue-3033.rs
- [x] for-loop2.rs

Fixes #3486

### CODE REVIEW

File: gcc/rust/resolve/rust-forever-stack.hxx [hunk 1]
```diff
@@ -643,11 +643,16 @@ ForeverStack<N>::resolve_path (
       if (final_node.rib.kind == Rib::Kind::TraitOrImpl)
 	return tl::nullopt;
 
-      std::string seg_name
-	= unwrap_type_segment (segments.back ()).as_string ();
+      auto seg = unwrap_type_segment (segments.back ());
```
Comment (powerboat9) [inline gcc/rust/resolve/rust-forever-stack.hxx:646]: This should probably be `auto &seg`

File: gcc/rust/resolve/rust-forever-stack.hxx [hunk 2]
```diff
@@ -643,11 +643,16 @@ ForeverStack<N>::resolve_path (
...
+      std::string seg_name = seg.as_string ();
 
       // assuming this can't be a lang item segment
-      tl::optional<Rib::Definition> res = final_node.rib.get (seg_name);
+      tl::optional<Rib::Definition> res;
+      if (seg.is_lower_self_seg ())
+	res = final_node.parent.value ().rib.get (
+	  unwrap_type_segment (segments[segments.size () - 2]).as_string ());
```
[the remark this answers is not in the document]
Comment (powerboat9) [reply gcc/rust/resolve/rust-forever-stack.hxx:653]: https://doc.rust-lang.org/reference/items/use-declarations.html#self-imports

[the remark this answers is not in the document]
Comment (P-E-P) [reply gcc/rust/resolve/rust-forever-stack.hxx:653]: I'm far from done with this PR, I'll take a look at your comments tomorrow.

[the remark this answers is not in the document]
Comment (P-E-P) [reply gcc/rust/resolve/rust-forever-stack.hxx]: I've introduced the example from the specification to make sure we won't miss it next time.

File: gcc/rust/resolve/rust-early-name-resolver-2.0.cc [hunk 3]
```diff
@@ -417,10 +417,16 @@ Early::finalize_rebind_import (const Early::ImportPair &mapping)
...
       locus = rebind.get_identifier ().get_locus ();
       break;
-    case AST::UseTreeRebind::NewBindType::NONE:
-      declared_name = path.get_final_segment ().as_string ();
-      locus = path.get_final_segment ().get_locus ();
-      break;
+      case AST::UseTreeRebind::NewBindType::NONE: {
+	const auto &segments = path.get_segments ();
+	// We don't want to insert `self` with `use module::self`
+	if (path.get_final_segment ().is_lower_self_seg ())
```
Comment (powerboat9) [inline gcc/rust/resolve/rust-early-name-resolver-2.0.cc:423]: Would probably want to `rust_assert` there are enough segments in `path` that these accesses don't go out of bounds

File: gcc/rust/resolve/rust-forever-stack.hxx [hunk 4]
```diff
@@ -594,6 +594,29 @@ ForeverStack<N>::resolve_segments (
...
+
+template <>
+template <typename S>
+tl::optional<Rib::Definition>
+ForeverStack<Namespace::Types>::resolve_final_segment (
+  Node &final_node, std::string &seg_name, const std::vector<S> &segments)
+{
+  auto &seg = unwrap_type_segment (segments.back ());
+  if (seg.is_lower_self_seg ())
+    return final_node.parent.value ().rib.get (
```
Comment (powerboat9) [inline gcc/rust/resolve/rust-forever-stack.hxx:614]: Should be able to just grab the node id from `final_node` and convert that into a `Rib::Definition` -- that should also remove the need for the `segments` parameter

**Review by powerboat9 — CHANGES_REQUESTED** [review]
Otherwise, looks good

File: gcc/rust/resolve/rust-early-name-resolver-2.0.cc (hunk 3 above)
Comment (P-E-P) [reply gcc/rust/resolve/rust-early-name-resolver-2.0.cc:423]: Technically at this point the previous steps would error out if there was a self alone, bet we're never too safe.

**Review by powerboat9 — APPROVED** [review]
