### PR TITLE
gccrs: fix parser error on parenthesised types

### LINKED ISSUE #4148: tests: `make check-rust` fails to catch a parsing error
### Summary

When trying to add a reproducer / regression test for #2886, the test case should fail with a parsing error, similar to what is found in <https://godbolt.org/z/WorW4oqG4>.

### Reproducer

I tried this code (in `gcc/testsuite/rust/compile/parens.rs`):

```rust
pub fn ret_parens(x: i32) -> i32 {
    ((x+1))
}

pub fn arg_ret_parens((x): (i32)) -> (i32) {
    ((x+1))
}

pub fn ret_rpit_parens2(x: i32) -> (i32) {
    ((x+1))
}

pub fn ret_parens3(x: i32) -> i32 {
    ((x+1))
}
```

Related: #2886 

### Does the code make use of any (1.49) nightly feature ?

- [ ] Nightly

### Godbolt link

https://godbolt.org/z/WorW4oqG4

### Actual behavior

The test passes, which it should only after a proper fix.

### Expected behavior

The test should fail to compile with the following errors:

```
<source>:7:21: error: Failed to resolve trait by looking up hir node
    7 | fn increment1((x): (i32)) -> i32{
      |                     ^~~
<source>:8:7: error: cannot apply operator '+' to types dyn [] and <integer>
    8 |     ((x+1))
      |       ^
<source>:11:27: error: Failed to resolve trait by looking up hir node
   11 | fn increment2(x: i32) -> (i32) {
      |                           ^~~
Compiler returned: 1
```

### GCC Version

GCC 15.2.1, GCCRS c742973c23448e321fba4d9ff98a9092dc0df7ba

### PR DESCRIPTION
**Pull request by Villosse**
Do not cast parenthesised types to TraitBound types

Fixes #4148

gcc/rust/ChangeLog:

	* parse/rust-parse-impl.h (Parser::parse_paren_prefixed_type):

gcc/testsuite/ChangeLog:

	* rust/compile/issue-4148.rs:

Thank you for making Rust GCC better!

If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.

Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

### CODE REVIEW

File: gcc/rust/parse/rust-parse-impl.h [hunk 1]
```diff
@@ -9488,28 +9488,39 @@ Parser<ManagedTokenSource>::parse_paren_prefixed_type ()
...
-		new AST::ParenthesisedType (std::move (released_ptr),
-					    left_delim_locus));
-	    }
-	  else
-	    {
-	      // trait object type (one bound)
 
-	      // get value semantics trait bound
-	      AST::TraitBound value_bound (*converted_bound);
+	  /*
```
Comment (P-E-P) [inline gcc/rust/parse/rust-parse-impl.h]: This is dead code, if it isn't required it won't be touched again, delete it and put a comment if any information should remain.

File: gcc/rust/parse/rust-parse-impl.h [hunk 2]
```diff
@@ -9488,28 +9488,39 @@ Parser<ManagedTokenSource>::parse_paren_prefixed_type ()
...
 	  std::unique_ptr<AST::Type> released_ptr = std::move (types[0]);
+
+	  // We don't want to convert it to TraitBound as it could be a
+	  // ParenthesisedType
+
+	  return std::unique_ptr<AST::ParenthesisedType> (
+	    new AST::ParenthesisedType (std::move (released_ptr),
+					left_delim_locus));
+
 	  /* HACK: attempt to convert to trait bound. if fails, parenthesised
```
Comment (P-E-P) [inline gcc/rust/parse/rust-parse-impl.h]: Should probably be removed.

File: gcc/rust/parse/rust-parse-impl.h [hunk 3]
```diff
@@ -9488,28 +9488,39 @@ Parser<ManagedTokenSource>::parse_paren_prefixed_type ()
 	{
 	  // release vector pointer
 	  std::unique_ptr<AST::Type> released_ptr = std::move (types[0]);
+
+	  // We don't want to convert it to TraitBound as it could be a
```
Comment (P-E-P) [inline gcc/rust/parse/rust-parse-impl.h]: This comment fails to cover one case, what if it isn't ?

**Review by P-E-P — APPROVED** [review]
