### PR TITLE
gccrs: Track fn_once output lang item properly

### LINKED ISSUE #2105: ICE with closures in insert_autoderef_mappings
### Code

```rust
pub enum Option<T> {
    Some(T),
    None,
}

pub use Option::{Some, None};

#[lang = "fn_once"]
pub trait FnOnce<Args> {
    #[lang = "fn_once_output"]
    type Output;

    extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
}

impl<T> Option<T> {
    pub fn map<R, F: FnOnce(T) -> R>(self, f: F) -> Option<R> {
        match self {
            Some(value) => Some(f(value)),
            None => None,
        }
    }
}
```

### Meta

- What version of Rust GCC were you using, git sha if possible. 92b137048583c2c22c585097119dba6a5fe06228

### Error output

```
crab1: internal compiler error: in insert_autoderef_mappings, at rust/typecheck/rust-typecheck-context.cc:342
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
crab1: internal compiler error: in insert_autoderef_mappings, at rust/typecheck/rust-typecheck-context.cc:342
0x76846b Rust::Resolver::TypeCheckContext::insert_autoderef_mappings(unsigned int, std::vector<Rust::Resolver::Adjustment, std::allocator<Rust::Resolver::Adjustment> >&&)
        ../../gcc/rust/typecheck/rust-typecheck-context.cc:342
0xbaf838 Rust::Resolver::coercion_site(unsigned int, Rust::TyTy::TyWithLocation, Rust::TyTy::TyWithLocation, Location)
        ../../gcc/rust/typecheck/rust-type-util.cc:219
0xb73077 Rust::TyTy::TypeCheckCallExpr::visit(Rust::TyTy::ADTType&)
        ../../gcc/rust/typecheck/rust-tyty-call.cc:64
0xb9ec00 Rust::TyTy::TypeCheckCallExpr::go(Rust::TyTy::BaseType*, Rust::HIR::CallExpr&, Rust::TyTy::VariantDef&, Rust::Resolver::TypeCheckContext*)
        ../../gcc/rust/typecheck/rust-tyty-call.h:39
0xb9ec00 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::CallExpr&)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:226
0xb9b85e Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:41
0xb9cfb5 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::MatchExpr&)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:1399
0xb9b85e Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:41
0xb9c886 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:537
0xb9b85e Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:41
0xba95b1 Rust::Resolver::TypeCheckImplItem::visit(Rust::HIR::Function&)
        ../../gcc/rust/typecheck/rust-hir-type-check-implitem.cc:311
0xba723b Rust::Resolver::TypeCheckImplItem::Resolve(Rust::HIR::ImplBlock*, Rust::HIR::ImplItem*, Rust::TyTy::BaseType*, std::vector<Rust::TyTy::SubstitutionParamMapping, std::allocator<Rust::TyTy::SubstitutionParamMapping> >)
        ../../gcc/rust/typecheck/rust-hir-type-check-implitem.cc:180
0xb90868 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::ImplBlock&)
        ../../gcc/rust/typecheck/rust-hir-type-check-item.cc:341
0xb8b3ec Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
        ../../gcc/rust/typecheck/rust-hir-type-check-item.cc:49
0xb8b3ec Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
        ../../gcc/rust/typecheck/rust-hir-type-check-item.cc:35
0xb572eb Rust::Resolver::TypeResolution::Resolve(Rust::HIR::Crate&)
        ../../gcc/rust/typecheck/rust-hir-type-check.cc:37
0xa3b3e1 Rust::Session::compile_crate(char const*)
        ../../gcc/rust/rust-session-manager.cc:620
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
  ```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by philberty**
In order to setup the Output assoicated type we can rely on using generic argument bindings. So for example when we have the FnOnce trait:
```
  #[lang = "fn_once"]
  pub trait FnOnce<Args> {
      #[lang = "fn_once_output"]
      type Output;

      extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
  }
```
Thn we might have a function such as:

  ```pub fn map<R, F: FnOnce(T) -> R>(self, f: F) -> Option<R> { ... }```

This trait bound predicate of FnOnce(T) -> R we setup generics for the bound as:

  ```FnOnce<(T), Output=R>```

This means we can reuse our generic arguments handling to get this support.

Fixes #2105

gcc/rust/ChangeLog:

	* typecheck/rust-tyty-bounds.cc (TypeCheckBase::get_predicate_from_bound):
	* util/rust-hir-map.cc (Mappings::lookup_trait_item_lang_item):
	* util/rust-hir-map.h:

gcc/testsuite/ChangeLog:

	* rust/compile/issue-2105.rs: New test.

### CODE REVIEW

File: gcc/rust/typecheck/rust-tyty-bounds.cc [hunk 1]
```diff
@@ -227,22 +227,26 @@ TypeCheckBase::get_predicate_from_bound (HIR::TypePath &type_path,
...
+	// set
+	rust_assert (fn.has_return_type ());
+	TypeCheckType::Resolve (fn.get_return_type ().get ());
+
+	HIR::TraitItem *trait_item = mappings->lookup_trait_item_lang_item (
+	  Analysis::RustLangItem::ItemType::FN_ONCE_OUTPUT);
+
+	std::vector<HIR::GenericArgsBinding> bindings;
+	Location output_locus = fn.get_return_type ()->get_locus ();
+	HIR::GenericArgsBinding binding (Identifier (
```
Comment (philberty) [inline gcc/rust/typecheck/rust-tyty-bounds.cc:240]: @dkm  look at this ugly one lol
