### PR TITLE
gccrs: Fix ICE caused by TypeCheckBase::parse_repr_options

### LINKED ISSUE #3550: ICE in parse_repr_options, at rust/typecheck/rust-hir-type-check-base.cc:313
auto-reduced (treereduce-rust):
````rust
#[cfg_attr(not(wrong = "32"), repr(i32))]
enum Eu64 {
    Au64 = 0,
}

````

original:
````rust
// With no repr attribute the discriminant will default to isize.
// On 32-bit architectures this is equivalent to i32 so the variants
// collide. On other architectures we need compilation to fail anyway,
// so force the repr.
#[cfg_attr(not(wrong = "32"), repr(i32))]
enum Eu64 {
    Au64 = 0,
    Bu64 = 0x8000_0000_0000_0000 //~ERROR already exists
}

fn main() {}

````

Version information:

a988708b4ba2b5a27715ea34c09ccfd3ed5143ca

Command:
`crab1 -Warray-bounds -mtune=generic -march=x86-64 -O0 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -frust-incomplete-and-experimental-compiler-do-not-use`

<details><summary><strong>Program output</strong></summary>
<p>

```
crab1: internal compiler error: in parse_repr_options, at rust/typecheck/rust-hir-type-check-base.cc:313
0x86d382 Rust::Resolver::TypeCheckBase::parse_repr_options(std::vector<Rust::AST::Attribute, std::allocator<Rust::AST::Attribute> > const&, unsigned int)
	../../gcc/rust/typecheck/rust-hir-type-check-base.cc:313
0xef1ee0 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::Enum&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:345
0xeecb37 Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:59
0xe84e8b Rust::Resolver::TypeResolution::Resolve(Rust::HIR::Crate&)
	../../gcc/rust/typecheck/rust-hir-type-check.cc:75
0xc5c2d3 Rust::Session::compile_crate(char const*)
	../../gcc/rust/rust-session-manager.cc:685
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by Polygonalr**
Closes #3550.

Expansion of `cfg_attr` causes `AttrInput`-s to be all parsed into `AttrInputMetaItemContainer`. `TypeCheckBase::parse_repr_options` assumes that the `AttrInput`-s within the attributes are all raw token trees instead of already-parsed meta items, which caused it to throw the ICE. The fix is simply to update `parse_repr_options` to also accept `AttrInputMetaItemContainer` attribute inputs.

### CODE REVIEW

File: gcc/rust/typecheck/rust-hir-type-check-base.cc [hunk 1]
```diff
@@ -421,14 +421,27 @@ TypeCheckBase::parse_repr_options (const AST::AttrVec &attrs, location_t locus)
...
 	  bool is_token_tree = input.get_attr_input_type ()
 			       == AST::AttrInput::AttrInputType::TOKEN_TREE;
-	  if (!is_token_tree)
+	  bool is_meta_item = input.get_attr_input_type ()
+			      == AST::AttrInput::AttrInputType::META_ITEM;
+	  if (!is_token_tree && !is_meta_item)
 	    {
 	      rust_error_at (attr.get_locus (), "malformed %<repr%> attribute");
 	      continue;
 	    }
```
Comment (P-E-P) [inline gcc/rust/typecheck/rust-hir-type-check-base.cc:430]: Not directly related to this PR but I wonder if we should move this to the attribute checker or builtin attribute checker (and assert it here).
