### PR TITLE
Fix parsing of statement macros 

### LINKED ISSUE #2239: Cannot parse statement after curly bracket macro invocation
I tried this code:

```rust
macro_rules! unroll {
    {} => {}
}

pub fn foo() {
    let mut _a = 14;
    unroll! {}
    let mut _b = 13;
}
```

minimized from `verify_512_helper` in `libcore 1.49` (`library/stdarch/crates/core_arch/src/x86/avx512vpclmulqdq.rs`)

I expected to see this happen: no error
Instead, this happened: 

```rust
minimized.rs:8:5: error: expecting ‘}’ but ‘let’ found
    8 |     let mut _b = 13;
      |     ^~~
minimized.rs:8:5: error: error may be from having an expression (as opposed to statement) in the body of the function but not last
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

058682f736b

### PR DESCRIPTION
**Pull request by matthewjasper**
Fixes various bugs in statement macro handling
- Parses braced macros as statements where appropriate
- Checks for semicolons (sometimes) when expanding statement macros
- Handles final statement vs. tail expression changing for macros
- Distinguishes between expression and statement macros in AST

This PR takes an approach similar to rustc (and gccrs before #2206) where statement macros are parsed as statements and the parser "recovers" into parsing an expression when required.  I didn't use the existing block expr vs. non-block expr handling because it doesn't handle match arms correctly (or interpolated expression macros once those are implemented).

Closes #2239

### CODE REVIEW

**Comment by philberty** [comment]
It looks like there is overlap with #2292

File: gcc/rust/parse/rust-parse-impl.h [hunk 1]
```diff
@@ -6348,8 +6341,16 @@ Parser<ManagedTokenSource>::parse_let_stmt (AST::AttrVec outer_attrs,
...
-      return nullptr;
+    {
+      // `stmt` macro variables are parsed without a semicolon, but should be
+      // parsed as a full statement when interpolated. This should be handled
+      // by having the interpolated statement be distinguishable from normal
+      // tokens, e.g. by NT tokens.
+      if (restrictions.allow_close_after_expr_stmt)
+	maybe_skip_token (SEMICOLON);
+      else if (!skip_token (SEMICOLON))
+	return nullptr;
```
Comment (philberty) [inline gcc/rust/parse/rust-parse-impl.h:6352]: should this be an error?

File: gcc/rust/parse/rust-parse-impl.h [hunk 2]
```diff
@@ -7289,10 +7348,27 @@ Parser<ManagedTokenSource>::parse_expr_stmt (AST::AttrVec outer_attrs,
...
+	      if (id != RIGHT_PAREN && id != RIGHT_CURLY && id != RIGHT_SQUARE)
+		{
+		  expect_token (SEMICOLON);
+		  return nullptr;
+		}
+	    }
+	  else
+	    {
+	      expect_token (SEMICOLON);
+	      return nullptr;
```
Comment (philberty) [inline gcc/rust/parse/rust-parse-impl.h:7369]: same here

File: gcc/rust/parse/rust-parse-impl.h [hunk 3]
```diff
@@ -7289,10 +7348,27 @@ Parser<ManagedTokenSource>::parse_expr_stmt (AST::AttrVec outer_attrs,
...
       else if (expr->is_expr_without_block ())
-	return nullptr;
+	{
+	  if (restrictions.allow_close_after_expr_stmt)
+	    {
+	      TokenId id = lexer.peek_token ()->get_id ();
+	      if (id != RIGHT_PAREN && id != RIGHT_CURLY && id != RIGHT_SQUARE)
+		{
+		  expect_token (SEMICOLON);
+		  return nullptr;
```
Comment (philberty) [inline gcc/rust/parse/rust-parse-impl.h:7363]: same here?

**Review by philberty — APPROVED** [review]
This LGTM approach looks reasonable because of how Rust treats stmts vs expressions.  I reviewed the parser changes as best I can but its been too long since I wrote parser code you need @CohenArthur to sign off on that one.

File: gcc/rust/parse/rust-parse-impl.h (hunk 1 above)
Comment (matthewjasper) [reply gcc/rust/parse/rust-parse-impl.h:6352]: `skip_token` errors if it returns false.

File: gcc/rust/parse/rust-parse-impl.h (hunk 2 above)
Comment (matthewjasper) [reply gcc/rust/parse/rust-parse-impl.h:7369]: `expect_token` emits an error

**Review by philberty — APPROVED** [review]

**Review by P-E-P — APPROVED** [review]

**Comment by CohenArthur** [comment]
I will review this PR today, sorry for the wait!

File: gcc/rust/parse/rust-parse-impl.h [hunk 4]
```diff
@@ -7261,19 +7262,77 @@ Parser<ManagedTokenSource>::parse_method ()
...
+    case SELF_ALIAS:
+    case DOLLAR_SIGN:
+      case SCOPE_RESOLUTION: {
+	AST::PathInExpression path = parse_path_in_expression ();
+	std::unique_ptr<AST::Expr> null_denotation;
+
+	if (lexer.peek_token ()->get_id () == EXCLAM)
+	  {
+	    // Bind a reference to avoid -Wredundant-move on post-P1825R0
+	    // compilers. Change to non-refeerence type and remove the moves
```
Comment (CohenArthur) [inline gcc/rust/parse/rust-parse-impl.h:7290]:
```suggestion
	    // compilers. Change to non-reference type and remove the moves
```

**Review by CohenArthur — COMMENTED** [review]
This is a lot of awesome work, thanks a lot! I really appreciate it. It's going to help a lot for parsing `core`. Minor comments but I'm really in favor of merging this

File: gcc/rust/ast/rust-ast.cc [hunk 5]
```diff
@@ -4223,12 +4223,10 @@ Attribute::is_parsed_to_meta_item () const
 }
 
 void
-BlockExpr::strip_tail_expr ()
+BlockExpr::normalize_tail_expr ()
```
[the remark this answers is not in the document]
Comment (P-E-P) [reply gcc/rust/ast/rust-ast.cc:4226]: Tbh I prefer the normalize_tail_expr name :laughing:

[the remark this answers is not in the document]
Comment (CohenArthur) [reply gcc/rust/ast/rust-ast.cc:4226]: I think `convert_last_stmt` is a bit clearer, but I'm okay with `normalize_tail_expr` as well :)
