### PR TITLE
Parse const with no value

### LINKED ISSUE #2665: Cannot parse disabled const in impl
The following snippet is rejected by GCCRS even though the code is disabled and should be accepted.

I tried this code:

```rust
fn main() {}

#[cfg(FALSE)]
impl X {
    const Y: u8;
}
```

I expected to see this happen: Compiles correctly

Instead, this happened:

```
./test.rs:5:16: error: expecting ‘=’ but ‘;’ found
    5 |     const Y: u8;
      |                ^
./test.rs:6:1: error: failed to parse inherent impl item in inherent impl
    6 | }
      | ^
./test.rs:6:1: error: failed to parse item in crate
```

### Meta

- c7728c8020334fecb47789163ba94326aab6208c

### PR DESCRIPTION
**Pull request by P-E-P**
Fixes #2665.

### CODE REVIEW

File: gcc/rust/parse/rust-parse-impl.h [hunk 1]
```diff
@@ -4783,6 +4783,16 @@ Parser<ManagedTokenSource>::parse_const_item (AST::Visibility vis,
...
 
+  // A const with no given expression value
+  if (lexer.peek_token ()->get_id () == SEMICOLON)
+    {
+      lexer.skip_token ();
+      return std::unique_ptr<AST::ConstantItem> (
+	new AST::ConstantItem (std::move (ident), std::move (vis),
+			       std::move (type), std::move (outer_attrs),
+			       locus));
+    }
```
Comment (CohenArthur) [inline gcc/rust/parse/rust-parse-impl.h:4794]: I think this is good, but we need to handle it somewhere else, right? e.g. the rest of the AST and HIR are probably expecting that an `impl`'s `const` always has a value, right?

Comment (CohenArthur) [reply gcc/rust/parse/rust-parse-impl.h:4794]: yeah, this ICEs:

```rust
struct S;

impl S {
    const D: u8;
}
```

while it should produce a nice error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9b8643a863d5350e8b226e8bc9789b88

this should be adressed in a later PR however :)
