### PR TITLE
Expansion code for cfg attributes, bug fixes and minor enhancements in parser

### LINKED ISSUE #42: StructFieldExpr are missing location info
Currently initializing struct members in StructExprFieldIndexValue and StructExprFieldIdentifierValue don't have any location info.

### LINKED ISSUE #52: Parser failed to handle expressions within index portion ArrayIndexExpr
```test.rs:8:22: error: expecting ‘]’ but ‘+’ found
    8 |     let c = xs[index + 1];
      |                      ^
left denotation is null; returning null for parse_expr
```

### LINKED ISSUE #53: Parser failed to handle CopiedArray
test.rs:8:36: error: expecting ‘;’ but ‘]’ found                                                                           
    8 |     let mut array: [i32; 3] = [0; 3];                                                                              
      |                                    ^                 
test.rs:8:5: error: failed to parse statement or expression without block in block expression
    8 |     let mut array: [i32; 3] = [0; 3];                                                                              
      |     ^                                                                                                              
test.rs:8:36: error: unrecognised token ‘]’ for start of item                                                              
    8 |     let mut array: [i32; 3] = [0; 3];                                                                              
      |                                    ^                                                                               
test.rs:8:36: error: failed to parse item in crate

### PR DESCRIPTION
**Pull request by SimplyTheOther**
This PR adds the code used to expand the AST to allow the proper handling of the `cfg` conditional compilation attribute, as well as related attributes such as `cfg_attr` and theoretically the `cfg!` macro as well. This will ensure that allowed aspects of Rust, e.g. functions, can be stripped based on these attributes. This is one aspect of the "macro expansion" phase (#17), and is probably the first one that should be executed (as name resolution is not possible before this aspect). 

Additionally, there are also bug fixes and parser enhancements. #53 (can't handle copied array expression), #52 (can't parse some expressions inside array index expression), and #42 (no locations in struct expression fields) should all be fixed. Additionally, the use tree parsing was enhanced to be closer to the required behaviour. 

There were also some minor changes to the AST - fields/member variables that were made public for access in the resolution stages have been made private again, and now use getter functions. This decision was made to allow changing the representation of the variables later (e.g. moving variables into parent or child classes).
Also, the copy constructors and copy assignment operators of many AST classes were made safer by adding checks for null pointers before attempting to dereference them (when cloning nodes).

Closing keywords for issues:
Fixes #53, fixes #52, resolves #42.

### CODE REVIEW

**Comment by philberty** [comment]
nice work!

File: gcc/rust/analysis/rust-scan.cc [hunk 1]
```diff
@@ -353,7 +353,7 @@ TopLevelScan::visit (AST::UseDeclaration &use_decl)
 void
 TopLevelScan::visit (AST::Function &function)
 {
-  functions[function.function_name] = &function;
```
Comment (philberty) [inline gcc/rust/analysis/rust-scan.cc:356]: thanks for doing this my branch to move to HIR is updating the pipeline with a new name/type resolution algorithm so we wont need those extra fields on LetStmt and Function inside the AST which i will remove with that PR
