### PR TITLE
Reject empty cfg_attr

### LINKED ISSUE #3966: segfault with cfg_attr on struct field
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -frust-incomplete-and-experimental-compiler-do-not-use
struct S {
    #[cfg_attr()]
    field: u8,
}

````

original:
````rust
// Derive helpers are resolved successfully inside `cfg_attr`.

//@ check-pass
// Derive helpers are resolved successfully inside `cfg_attr`.

#[macro_use]
extern crate test_macros;

#[macro_use]
#[macro_use]
struct S {
    #[cfg_attr()]
    field: u8,
}

fn main() {}

````

Version information:

5dc8c4d20d62462ebce137c6e5146235ab9e9e2e

Command:
`/home/matthias/vcs/github/gccrs/gccrs-build/gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use`

<details><summary><strong>Program output</strong></summary>
<p>

```
crab1: internal compiler error: Segmentation fault
0x2fecaf8 internal_error(char const*, ...)
	../../gcc/diagnostic-global-context.cc:517
0x196d57f crash_signal
	../../gcc/toplev.cc:321
0xcc2cd3 std::__uniq_ptr_impl<Rust::AST::MetaItemInner, std::default_delete<Rust::AST::MetaItemInner> >::_M_ptr() const
	/usr/include/c++/15.1.1/bits/unique_ptr.h:193
0xcc2cd3 std::unique_ptr<Rust::AST::MetaItemInner, std::default_delete<Rust::AST::MetaItemInner> >::get() const
	/usr/include/c++/15.1.1/bits/unique_ptr.h:473
0xcc2cd3 std::unique_ptr<Rust::AST::MetaItemInner, std::default_delete<Rust::AST::MetaItemInner> >::operator->() const
	/usr/include/c++/15.1.1/bits/unique_ptr.h:466
0xcc2cd3 Rust::AST::Attribute::check_cfg_predicate(Rust::Session const&) const
	../../gcc/rust/ast/rust-ast.cc:4267
0xe91d86 Rust::expand_cfg_attrs(std::vector<Rust::AST::Attribute, std::allocator<Rust::AST::Attribute> >&)
	../../gcc/rust/expand/rust-cfg-strip.cc:108
0xe92509 Rust::CfgStrip::maybe_strip_struct_fields(std::vector<Rust::AST::StructField, std::allocator<Rust::AST::StructField> >&)
	../../gcc/rust/expand/rust-cfg-strip.cc:179
0xd6d76f void Rust::AST::DefaultASTVisitor::visit<Rust::AST::Item>(std::unique_ptr<Rust::AST::Item, std::default_delete<Rust::AST::Item> >&)
	../../gcc/rust/ast/rust-ast-visitor.h:416
0xd6d76f Rust::AST::DefaultASTVisitor::visit(Rust::AST::Crate&)
	../../gcc/rust/ast/rust-ast-visitor.cc:38
0xe94226 Rust::CfgStrip::visit(Rust::AST::Crate&)
	../../gcc/rust/expand/rust-cfg-strip.cc:158
0xda3154 Rust::Session::expansion(Rust::AST::Crate&, Rust::Resolver2_0::NameResolutionContext&)
	../../gcc/rust/rust-session-manager.cc:941
0xdb8ed7 Rust::Session::compile_crate(char const*)
	../../gcc/rust/rust-session-manager.cc:620
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by P-E-P**
Fixes #3966

### CODE REVIEW

File: gcc/rust/ast/rust-ast.cc [hunk 1]
```diff
@@ -4169,6 +4170,13 @@ Attribute::check_cfg_predicate (const Session &session) const
     return false;
 
   auto &meta_item = static_cast<AttrInputMetaItemContainer &> (*attr_input);
+  if (meta_item.get_items ().empty ()
+      && string_path == Values::Attributes::CFG_ATTR)
+    {
+      rust_error_at (path.get_locus (), "malformed %qs attribute input",
```
Comment (powerboat9) [inline gcc/rust/ast/rust-ast.cc]: Since `string_path` is known to be `"cfg_attr"`, you can use `"%<cfg_attr%>"`
