### PR TITLE
Initial support for module

### LINKED ISSUE #432: `mod` keyword not supported.
```
mod foomod {
    struct Foo {
     f: i32,
     g: u32,
    }
}

fn test() -> foomod::Foo {
    foomod::Foo{
        f:1,
        g:3,
    }
}
```
Ends up with : 
```
gccrs/gcc/testsuite/rust.test/unsupported/struct_field_vis.rs:10:14: error: failed to resolve TypePath: foomod::Foo
gcc/testsuite/rust.test/unsupported/struct_field_vis.rs:10:14: error: unresolved type
gcc/testsuite/rust.test/unsupported/struct_field_vis.rs:11:5: error: unknown root segment in path foomod::Foo lookup foomod
```

The error could be expected because of missing `pub` in `foomod`.
But adding `pub` does not help:

```
mod foomod {
    pub struct Foo {
        pub f: i32,
        pub g: u32,
    }
}

fn test() -> foomod::Foo {
    foomod::Foo{
        f:1,
        g:3,
    }
}
```
Still gives the same error. 

Looks like all definition are currently private and that the compiler is not very friendly when trying to access a private member from outside (but I could be wrong!)

### PR DESCRIPTION
**Pull request by dkm**
Adds name resolution, HIR lowering and type checking. For modules
which should allow for initial multiple file parsing support.

Fixes #432

### CODE REVIEW

**Comment by dkm** [comment]
This is still on going.
There are several issues:
```
mod foomod {
    pub struct Foo {
        pub foofield: i32,
    }
}

fn main() {
    //    foomod::Foo{f:3i32}
    let t = foomod::Foo{
        foofield: 12,
    };
}
```
Is segfaulting and

```
mod foomod {
    pub fn totobob() {
    }
}
fn main() {
    foomod::totobob();
}
```
gives:
```
compile/torture/mod1.rs:12:9: error: failed to lookup function type
   12 |     pub fn totobob() {
      |         ^
```
Looks like even simple cases are not working, I must have broken something during a rebase. Still progressing slowly :)

**Comment by philberty** [comment]
Can you share the segv? I think your really close to getting this right, It will take me a while to review this and the segv backtrace might give me some hints

**Comment by philberty** [comment]
Awesome work though thanks for bearing with this.

As I said in the other PR, I think you can see that the structure is not that "nice" yet. So i think we should start thinking about better ways to improve the API's and interfaces in the front-end.

**Comment by dkm** [comment]
Sure I can share the segfault :) I'm in the process of rebasing/cleaning my working tree (hence the other small PRs).

**Comment by dkm** [comment]
Beware that I have not yet looked into it as I am more focused on the "nearly working" case.

```
rust1: internal compiler error: Segmentation fault
0xecee9f crash_signal
        ../../gcc/toplev.c:327
0x7fd82096dd5f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x9c3949 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::PathInExpression&)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.h:875
0x9bf5f5 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.h:48
0x9b9845 Rust::Resolver::TypeCheckStructExpr::visit(Rust::HIR::StructExprStructFields&)
        ../../gcc/rust/typecheck/rust-hir-type-check.cc:129
0x9c542a Rust::Resolver::TypeCheckStructExpr::Resolve(Rust::HIR::StructExprStructFields*)
        ../../gcc/rust/typecheck/rust-hir-type-check-struct-field.h:38
0x9c542a Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::StructExprStructFields&)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.h:833
0x9bf5f5 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.h:48
0x9c2003 Rust::Resolver::TypeCheckStmt::visit(Rust::HIR::LetStmt&)
        ../../gcc/rust/typecheck/rust-hir-type-check-stmt.h:60
0x9b88e2 Rust::Resolver::TypeCheckStmt::Resolve(Rust::HIR::Stmt*, bool)
        ../../gcc/rust/typecheck/rust-hir-type-check-stmt.h:38
0x9b88e2 operator()
        ../../gcc/rust/typecheck/rust-hir-type-check.cc:97
0x9b88e2 __invoke_impl<bool, Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)::<lambda(Rust::HIR::Stmt*)>&, Rust::HIR::Stmt*>
        /usr/include/c++/10/bits/invoke.h:60
0x9b88e2 __invoke_r<bool, Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)::<lambda(Rust::HIR::Stmt*)>&, Rust::HIR::Stmt*>
        /usr/include/c++/10/bits/invoke.h:141
0x9b88e2 _M_invoke
        /usr/include/c++/10/bits/std_function.h:291
0x9b8a89 std::function<bool (Rust::HIR::Stmt*)>::operator()(Rust::HIR::Stmt*) const
        /usr/include/c++/10/bits/std_function.h:622
0x9b8a89 Rust::HIR::BlockExpr::iterate_stmts(std::function<bool (Rust::HIR::Stmt*)>)
        ../../gcc/rust/hir/tree/rust-hir-expr.h:2484
0x9b8a89 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
        ../../gcc/rust/typecheck/rust-hir-type-check.cc:96
0x9bf5f5 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gcc/rust/typecheck/rust-hir-type-check-expr.h:48
0x9bfae5 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::Function&)
        ../../gcc/rust/typecheck/rust-hir-type-check-item.h:81
0x9b904b Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item*)
        ../../gcc/rust/typecheck/rust-hir-type-check-item.h:40
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

File: gcc/rust/hir/rust-ast-lower-item.h [hunk 1]
```diff
@@ -53,6 +54,42 @@ class ASTLoweringItem : public ASTLoweringBase
...
 
+  void visit (AST::ModuleBodied &module) override
+  {
+    auto crate_num = mappings->get_current_crate ();
+    Analysis::NodeMapping mapping (crate_num, module.get_node_id (),
+				   mappings->get_next_hir_id (crate_num),
+				   mappings->get_next_localdef_id (crate_num));
+
+    // should be lowered from module.get_vis()
+    HIR::Visibility vis = HIR::Visibility::create_public ();
```
Comment (philberty) [inline gcc/rust/hir/rust-ast-lower-item.h:65]: I think there is a case to make a much simpler HIR::visibility, an enum might just work: https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/hir/enum.VisibilityKind.html

File: gcc/rust/resolve/rust-ast-resolve-toplevel.h [hunk 2]
```diff
@@ -39,6 +41,29 @@ class ResolveTopLevel : public ResolverBase
     item->accept_vis (resolver);
   };
 
+  void visit (AST::ModuleBodied& module) override {
+    auto path = prefix.append (CanonicalPath(module.get_name()));
+    resolver->get_name_scope ().insert (
+      path, module.get_node_id (), module.get_locus (), false,
```
Comment (philberty) [inline gcc/rust/resolve/rust-ast-resolve-toplevel.h:47]: I think the name resolution stuff could be extracted into a single commit a test case like:

```rust
mod foo {
  struct A;
}

fn main() {}
```

Might work since the path expression stuff will not be invoked.

**Review by philberty — CHANGES_REQUESTED** [review]
I think this looks really good, I am going to check out your branch and try something since I think your 99% of the way there.

I think the only change needed would be to potentially extract this into 2-3 commits.

1. name resolution
2. HIR lowering
3. Type resolution and finish PathExpression work + testcases

Nice job :)

File: gcc/rust/typecheck/rust-hir-type-check-toplevel.h [hunk 3]
```diff
@@ -100,6 +101,12 @@ class TypeCheckTopLevel : public TypeCheckBase
     context->insert_type (struct_decl.get_mappings (), type);
   }
 
+  void visit (HIR::ModuleBodied &module) override
+  {
+    for (auto &item : module.get_items ())
+      TypeCheckItem::Resolve (item.get ());
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-toplevel.h:107]: This should be:

```c++
    for (auto &item : module.get_items ())
      TypeCheckTopLevel::Resolve (item.get ());
```

File: gcc/rust/typecheck/rust-hir-type-check-expr.h [hunk 4]
```diff
@@ -1146,6 +1147,8 @@ class TypeCheckExpr : public TypeCheckBase
 		rust_error_at (seg.get_locus (), "reverse lookup failure");
 		return new TyTy::ErrorType (expr.get_mappings ().get_hirid ());
 	      }
+            // MARC: why is this not an error to have a NodeId not referering to any HIR?
+            // Is it because we may be using a to-be-completed HIR graph ?
 	    return root_tyty;
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-expr.h:1152]: The reason it is not an error is consider consider a test case:

```rust
struct <T>Foo(T);

impl Foo<i32> {
  fn test() ...
}

impl Foo<f32> {
  fn test() ...
}

fn main() {
  let a;
  a = Foo::new();  
}
```

In that path of Foo::new we must take into consideration any generic arguments to determine which new function we should be calling to. So this is where the Path Probe takes place over in: https://github.com/Rust-GCC/gccrs/blob/7d3157eec84ef8620f4648200f54b293e561b8c4/gcc/rust/typecheck/rust-hir-path-probe.h#L42

This means we take the type that has been resolved for the segments up to this point and use it as the receiver to match an impl block for that type and then look for any impl items which match the segment we want.

**Comment by philberty** [comment]
I've pushed this commit onto a branch: https://github.com/Rust-GCC/gccrs/commit/c361bec2608c7e579af3a8d5ff8a283071af610d

you should be able to cherry-pick in and squash if you like.

It allows for the compilation of:

```rust
pub struct Bar {
    pub f: i32,
}

mod foomod {
    pub struct Foo {
        pub prout: i32,
    }

    pub fn totoprout() -> i32 {
        return 3i32;
    }
}

pub fn toto() {}

fn test() -> Bar {
    Bar { f: 23i32 }
}

fn main() {
    let a;
    a = foomod::Foo { prout: 3i32 };

    toto();

    let b;
    b = foomod::totoprout();
}
```

File: gcc/rust/typecheck/rust-hir-type-check-toplevel.h (hunk 3 above)
Comment (dkm) [reply gcc/rust/typecheck/rust-hir-type-check-toplevel.h]: fixed by your changes

File: gcc/rust/typecheck/rust-hir-type-check-expr.h (hunk 4 above)
Comment (dkm) [reply gcc/rust/typecheck/rust-hir-type-check-expr.h:1156]: Ok, thanks, I think I understand a bit better now!

**Comment by dkm** [comment]
> I think this looks really good, I am going to check out your branch and try something since I think your 99% of the way there.
> 
> I think the only change needed would be to potentially extract this into 2-3 commits.
> 
>     1. name resolution
> 
>     2. HIR lowering
> 
>     3. Type resolution and finish PathExpression work + testcases
> 
> 
> Nice job :)

Ok ! I'll first add few tests and if everything is fine, I'll split the changes in 3. I'll squash your changes and mark you as co-author if that's ok with you ?

**Comment by dkm** [comment]
Haven't had much time for this :/
There is still problem with name resolution. 
This:
```
mod A {
    pub mod B {
        pub mod C {
            pub struct Foo {
            }
        }
    }
}

impl A::B::C::Foo {
    pub fn new() -> Self {
        A::B::C::Foo {
            f: 23i32,
        }
    }
}
fn main() {
    let _a = A::B::C::Foo::new();
}
```
raises this error:
```
error: failed to resolve TypePath: A::B::C::Foo
```
The error comes from the lookup method `Scope::lookup()` that iterates over Ribs but never queries the one having the name defined. I think I'm missing something to correctly route the search instead of simply going up the Rib stack.

And for other simple case like:
```
mod A {
    pub struct Foo {
        pub f: i32,
    }
}

fn main() {
    let _b = A::Foo {
        f: 33i32,
    };
}
```
GCC will ICE after getting `null` from `resolve_root_path( "A::Foo::[C: 0 Nid: 15 Hid: 26]")` in ` void visit (HIR::PathInExpression &expr)`.

File: gcc/rust/resolve/rust-ast-resolve-type.h [hunk 5]
```diff
@@ -193,24 +193,52 @@ class ResolveRelativeTypePath
...
 
     CanonicalPath lookup = canonical_path;
-    if (!prefix.is_error ())
+    if (!prefix.is_empty ())
       lookup = prefix.append (canonical_path);
 
     auto resolver = Resolver::get ();
     NodeId resolved_node = UNKNOWN_NODEID;
+
+    // Lookup type in the following priority order:
```
Comment (dkm) [inline gcc/rust/resolve/rust-ast-resolve-type.h:210]: I think here, I need to what's documented here : https://github.com/rust-lang/rust/blob/1f94abcda6884893d4723304102089198caa0839/compiler/rustc_resolve/src/lib.rs#L1722
When the type can't be found in the type NS, then we need to look for it in modules (and others element as documented). Is my understanding correct here? Currently, I'm trying to see if this would work by doing a global search in all Ribs (instead of targeting only the ones related to the module). It seems to work, but then a similar lookup is done so I need do apply the same workaround.

File: gcc/rust/resolve/rust-name-resolver.h [hunk 6]
```diff
@@ -321,14 +327,25 @@ class Scope
...
     bool ok = false;
-    iterate ([&] (Rib *r) mutable -> bool {
-      if (r->decl_was_declared_here (defId))
-	{
-	  ok = true;
-	  r->append_reference_for_def (defId, refId);
-	}
-      return true;
-    });
+
```
Comment (dkm) [inline gcc/rust/resolve/rust-name-resolver.h:330]: This is where the defId is looked up only in the type NS and where it should probably use the same search behavior (ie. search in modules if not found in type NS).

**Comment by philberty** [comment]
This was so close:

```
diff --git a/gcc/rust/resolve/rust-ast-resolve-item.h b/gcc/rust/resolve/rust-ast-resolve-item.h
index 923faf8b416..bc9aa4a9418 100644
--- a/gcc/rust/resolve/rust-ast-resolve-item.h
+++ b/gcc/rust/resolve/rust-ast-resolve-item.h
@@ -226,13 +226,14 @@ public:
     resolver->push_new_type_rib (resolver->get_type_scope ().peek ());
     resolver->push_new_label_rib (resolver->get_type_scope ().peek ());
 
-    auto path = CanonicalPath::new_seg (module.get_node_id(), module.get_name ());
+    auto path
+      = CanonicalPath::new_seg (module.get_node_id (), module.get_name ());
 
     for (auto &item : module.get_items ())
-      ResolveTopLevel::go (item.get (), path);
+      ResolveTopLevel::go (item.get ());
 
     for (auto &item : module.get_items ())
-      ResolveItem::go(item.get());
+      ResolveItem::go (item.get ());
 
     resolver->get_name_scope ().pop ();
     resolver->get_type_scope ().pop ();
diff --git a/gcc/rust/resolve/rust-ast-resolve-toplevel.h b/gcc/rust/resolve/rust-ast-resolve-toplevel.h
index c28a0820e52..d6ca42018e8 100644
--- a/gcc/rust/resolve/rust-ast-resolve-toplevel.h
+++ b/gcc/rust/resolve/rust-ast-resolve-toplevel.h
@@ -42,8 +42,8 @@ public:
 
   void visit (AST::Module &module) override
   {
-    auto path = prefix.append (CanonicalPath::new_seg (module.get_node_id(),
-                                                       module.get_name()));
+    auto path = prefix.append (
+      CanonicalPath::new_seg (module.get_node_id (), module.get_name ()));
     resolver->get_name_scope ().insert (
       path, module.get_node_id (), module.get_locus (), false,
       [&] (const CanonicalPath &, NodeId, Location locus) -> void {
@@ -53,15 +53,13 @@ public:
       });
 
     resolver->insert_new_definition (module.get_node_id (),
-                                     Definition{
-                                       module.get_node_id (),
-                                       module.get_node_id ()
-                                     });
+                                    Definition{module.get_node_id (),
+                                               module.get_node_id ()});
 
     // This crashes the compiler. Resolving top level is OK, but looks like it's
     // missing parts.
-    // for (auto &item : module.get_items())
-    //   ResolveTopLevel::go (item.get(), path);
+    for (auto &item : module.get_items ())
+      ResolveTopLevel::go (item.get (), path);
   }
 
   void visit (AST::TypeAlias &alias) override
```

**Comment by philberty** [comment]
I think the error handling in the resolve root within typechecking is a bit unclear how it should work. It is also missing some error cases.

So when I tested the branch it was failing to resolve the path full within the typechecker. I think I will add some documentation of this, as it is also failing to handle some error cases fully which was causing the crash for you.

Because the typechecker was not resolving the segment it should have raised an error here: https://github.com/Rust-GCC/gccrs/blob/5e723d0b7a85d109f01196b264a25823e77496e1/gcc/rust/typecheck/rust-hir-type-check-expr.h#L1240

Since it was able to resolve the module which does not have a type but then went on to fail to resolve the next segment, it should handle this case and return an error but instead returned a nullptr.

Basically the name resolution pass is a bit funny where you have the module and call resolve toplevel with the path prefix which gives you all the top-level names within the root scope rib. Then we you actually call resolve item to drill down into each AST::Item to resolve those names the module case has to do two things, it must call like you already had the Resolvetoplevel again but it should not take the path prefix it needs to add in the relative names of the module for this scope rib before it can finally resolve as normal.

**Comment by philberty** [comment]
Basically you found some bugs in the error handling within the resolve_root_path.

I would suggest that you apply this small diff to your code and try to cleanup/rebase your commits and we can see how the testsuite looks at that point. I think it would be nice to get this work merged soon since its very close to working.

**Comment by philberty** [comment]
From reviewing this patch everything is starting to shape up really well. The changeset should break down into 4/5 commits i think:

1. Add name resolution stuff which will be all of the changes inside the resolve package
2. HIR lowering this is using the HIR::ModuleBodied hangover from the AST this is fine for now we should add a task to desugar this a bit in a separate PR but the current state of this is fine for this PR
3. Backend code generation is fine since it should simply be adding that visitor for the module.
4. Typechecking as far as I can tell you have it correct right now.
5. Testcases

It's difficult to do a more fine-grained code review at the moment I think you need to rebase some commits. I would be interested in seeing what your test suite results look like at that point. 

I can see some commits which are pulling things into cc files which I think look good along with a change to the resolve-unused pass.

Don't worry about duplicate or missing warnings or anything like this for the unused scan right now. It's part of what @thomasyonug is looking into right now.  I can see you tweaked something here in (fedd21987ef69f57d95191ac83634b26513bb9b6)

In relation to that you could create a separate PR after this to add the dead-code scanning for modules by adding a visitor for HIR::ModuleBodied into DeadCode Scan over in:

https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/lint/rust-lint-marklive.h

File: gcc/rust/resolve/rust-ast-resolve-unused.h [hunk 7]
```diff
@@ -43,14 +43,15 @@ class ScanUnused
...
+    return true;
   }
 
   static void Scan ()
   {
     auto resolver = Resolver::get ();
-    resolver->iterate_name_ribs ([&] (Rib *r) -> void { ScanRib (r); });
-    resolver->iterate_type_ribs ([&] (Rib *r) -> void { ScanRib (r); });
-    resolver->iterate_label_ribs ([&] (Rib *r) -> void { ScanRib (r); });
+    resolver->iterate_name_ribs ([&] (Rib *r) -> bool { return ScanRib (r); });
```
Comment (philberty) [inline gcc/rust/resolve/rust-ast-resolve-unused.h:52]: Let's not change this as part of this PR. I think this scan unused needs some wor, in general, its causing dups for us at the moment.

File: gcc/rust/resolve/rust-ast-resolve.cc [hunk 8]
```diff
@@ -608,6 +613,19 @@ ResolvePath::resolve_path (AST::PathInExpression *expr)
 	  return;
 	}
     }
+
+  // its fully resolved lets mark it as such
+  if (resolved_node != UNKNOWN_NODEID)
+    {
```
Comment (philberty) [inline gcc/rust/resolve/rust-ast-resolve.cc:619]: nice

File: gcc/rust/resolve/rust-name-resolver.cc [hunk 9]
```diff
@@ -0,0 +1,37 @@
+#include <rust-name-resolver.h>
+
+namespace Rust {
+namespace Resolver {
+
+  void Scope::append_reference_for_def (NodeId refId, NodeId defId)
+  {
```
Comment (philberty) [inline gcc/rust/resolve/rust-name-resolver.cc:7]: I like the move to pull things into implementation files. Just remember to add the GCC Copyright header too

File: gcc/rust/resolve/rust-name-resolver.h [hunk 10]
```diff
@@ -80,12 +85,12 @@ class CanonicalPath
 
   static CanonicalPath create_empty () { return CanonicalPath ({}); }
 
-  bool is_error () const { return segs.size () == 0; }
+  bool is_empty () const { return segs.size () == 0; }
```
Comment (philberty) [inline gcc/rust/resolve/rust-name-resolver.h:88]: nice

File: gcc/rust/resolve/rust-name-resolver.h [hunk 11]
```diff
@@ -318,19 +324,30 @@ class Scope
...
-	}
-      return true;
-    });
-    rust_assert (ok);
-  }
+  void append_reference_for_def (NodeId refId, NodeId defId);
+  // {
+  //   bool ok = false;
+
+  //   Resolver *resolver = Resolver::get ();
```
Comment (philberty) [inline gcc/rust/resolve/rust-name-resolver.h:331]: we can remove this comment now its in its own implementation file.

File: gcc/rust/resolve/rust-name-resolver.h [hunk 12]
```diff
@@ -438,14 +455,15 @@ class Resolver
...
-  void iterate_type_ribs (std::function<void (Rib *)> cb)
+  void iterate_type_ribs (std::function<bool (Rib *)> cb)
   {
     for (auto it = type_ribs.begin (); it != type_ribs.end (); it++)
       {
 	if (it->first == global_type_node_id)
 	  continue;
 
-	cb (it->second);
+	if (!cb (it->second))
```
Comment (philberty) [inline gcc/rust/resolve/rust-name-resolver.h:465]: This is a good refactor change but I think it should be in a separate PR

File: gcc/rust/typecheck/rust-hir-type-check-expr.h [hunk 13]
```diff
@@ -1274,17 +1286,30 @@ class TypeCheckExpr : public TypeCheckBase
...
+	    //          ^^^^^^^^^^^^^^^^
+            // This is an error, we are not expecting a module.
+	    rust_error_at (seg.get_locus (), "expected value");
+            return new TyTy::ErrorType (expr.get_mappings ().get_hirid
+                                        ());
+          }
+
+        TyTy::BaseType *lookup
+	  = nullptr;
 	if (!context->lookup_type (ref, &lookup))
```
Comment (philberty) [inline gcc/rust/typecheck/rust-hir-type-check-expr.h:1313]: This all looks good here. You have a good comment about the nullptr vs error node. There is a nasty bug in here when we have bad name resolution, where you hit an assertion in the caller of resolve_root_node: when we have a path like:

module::foobar

and say for example foobar is not resolved or does not exist the result of this function is going to be a nullptr. I think the fix will be tricky to fix that as part of this PR so lets keep the changes to a minimum to handle modules for now. So long as there are no regressions to the testsuite

File: gcc/rust/util/rust-hir-map.cc [hunk 14]
```diff
@@ -331,6 +331,28 @@ Mappings::lookup_hir_impl_block (CrateNum crateNum, HirId id)
...
+void
+Mappings::insert_module (CrateNum crateNum, HirId id, HIR::Module *module)
+{
+  rust_assert (lookup_module (crateNum, id) == nullptr);
+
+  hirModuleMappings[crateNum][id] = module;
+}
+
+HIR::Module *
+Mappings::lookup_module (CrateNum crateNum, HirId id)
```
Comment (philberty) [inline gcc/rust/util/rust-hir-map.cc:343]: This will be a nice isolated commit.

File: gcc/rust/util/rust-hir-map.h [hunk 15]
```diff
@@ -25,6 +25,8 @@
 #include "rust-ast-full-decls.h"
 #include "rust-hir-full-decls.h"
 
+//#include "rust-hir-item.h"
```
Comment (philberty) [inline gcc/rust/util/rust-hir-map.h:28]: nice find

File: gcc/rust/resolve/rust-ast-resolve-type.h (hunk 5 above)
Comment (philberty) [reply gcc/rust/resolve/rust-ast-resolve-type.h:210]: This is interesting to read, I was thinking the fixup we added yesterday here:

which will do a scan toplevel with an empty path prefix a 2nd time which was causing an assertion inside insert_new_definition which was fixed with my PR earlier today should solve this.

I think I would like to see if you can revert this change to the type path name scope resolution and see if the fixes from yesterday and today still allow your test cases to pass.

Basically what happens is when the name resolver starts at the moment we endup with all the AST::Items canonical path's within the top-level scope so for example:


```rust
mod foo {
    pub struct Foo {
        pub f: i32,
    }

    pub fn foofn() -> i32 {
        return 3i32;
    }
}

struct Bar {b:i32}
```

The first scan toplevel gives us the paths:

[foo::Foo , foo:foofn, Bar]

But when we do the ResolveItems and we hit the Module we should do the resolve toplevel on each item then resolve item on each item so we end up with:

[Foo, foofn]
[foo::Foo , foo:foofn, Bar]

This means the relative paths of each item should be resolveable within the new rib that has been created.

The solution inside rustc here is kind of clever. The name resolver inside gccrs might need some thought because, one of the cases we don't funny support properly is the case of AST:::Items within blocks which can be forward declared and constantly having to do scan toplevel is getting a bit confusing.

Lets revert this change, see how it works and maintain a comment to the piece of source code from rustc which might provide a cleaner solution down the line.

**Review by philberty — CHANGES_REQUESTED** [review]
Nice work once again. Lets clean this up and see what the testsuite looks like.

File: gcc/rust/resolve/rust-ast-resolve.cc (hunk 8 above)
Comment (dkm) [reply gcc/rust/resolve/rust-ast-resolve.cc:619]: As I don't need to touch this method, I've simply reverted the .h->.cc move here.

File: gcc/rust/resolve/rust-name-resolver.h (hunk 12 above)
Comment (dkm) [reply gcc/rust/resolve/rust-name-resolver.h]: done and merged in #625

**Comment by dkm** [comment]
Still need to clean the tests and double-check all the commits are ok. Don't bother reviewing it now, I'll remove the draft state when it's ready :)

File: gcc/rust/resolve/rust-ast-resolve-toplevel.h (hunk 2 above)
Comment (dkm) [reply gcc/rust/resolve/rust-ast-resolve-toplevel.h:48]: Done, added in a dedicated test and checked it works with only the changes for name resolution applied.

**Comment by philberty** [comment]
Nice work! The build is passing.

**Comment by dkm** [comment]
I did some cleanup in tests to remove unnecessary dups. I've also added an execution test that is currently FAIL (but must be minor).

File: gcc/testsuite/rust/execute/torture/mod1.rs [hunk 16]
```diff
@@ -0,0 +1,25 @@
...
+    }
+}
+
+fn main() ->i32 {
+    let a = A::B::C::Foo::new();
+    let b = A::B::C::Foo {
+        f: -23i32,
+    };
+
+    a.f - b.f
```
Comment (philberty) [inline gcc/testsuite/rust/execute/torture/mod1.rs:24]: does that not need to be a.f + b.f since it is currently:

```
23 - (-23)
```

Comment (dkm) [reply gcc/testsuite/rust/execute/torture/mod1.rs:24]: woops

**Review by philberty — APPROVED** [review]
LGTM to merge I think the commit message still references WIP.

**Comment by dkm** [comment]
> LGTM to merge I think the commit message still references WIP.

Thanks for reviewing it even in draft state. Let me do a last proof reading, remove the draft state and reword first PR message :D

**Comment by dkm** [comment]
Hope to have everything in order now. All commits should still be correct and should not cause failure in buildbot.
