### PR TITLE
gccrs: Add testcase to show matching of enum variants

### LINKED ISSUE #852: Dataless enum variants can be matched without full path
I tried this code: https://godbolt.org/z/7eqP9vrTn

```rust
extern "C" {
    fn printf(s: *const i8, ...);
}

enum Foo {
   A,
   B(i32),
}

fn main() {
    let result = Foo::B(123);

    match result {
        A => unsafe {
            let a = "A\n\0";
            let b = a as *const str;
            let c = b as *const i8;

            printf(c);
        },
        Foo::B(x) => unsafe {
            let a = "Result: %i\n\0";
            let b = a as *const str;
            let c = b as *const i8;

            printf(c, x);
        },
    }
}

```

I expected to see this happen: compile without error
Instead, this happened:

```
rust1: error: expected [Foo{A = 1, B (0:Int:i32:(Ref: 28 TyRef: 8[8,]):bounds:[])}] got [<tyty::error>]
<source>:13:5: error: failed to type resolve expression
   13 |     match result {
      |     ^
<source>:10:1: error: expected [()] got [<tyty::error>]
   10 | fn main() {
      | ^
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

### PR DESCRIPTION
**Pull request by philberty**
Fixes #852

gcc/testsuite/ChangeLog:

	* rust/compile/issue-852.rs: New test.

### CODE REVIEW

File: gcc/testsuite/rust/compile/issue-852.rs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+enum Foo {
+    A,
+    B(i32),
+}
+
+fn main() {
+    let result = Foo::B(123);
+
+    match result {
+        A => unsafe {
```
Comment (CohenArthur) [inline gcc/testsuite/rust/compile/issue-852.rs:15]:
```suggestion
        Foo::A => unsafe {
```

Comment (CohenArthur) [reply gcc/testsuite/rust/compile/issue-852.rs:15]: Otherwise the second match arm should never be entered - I didn't catch up on the Zulip discussion which addresses this tho :D
