### PR TITLE
Fix bad transmute for aggregate types

### LINKED ISSUE #1432: Bad conversion in transmute
I tried this code:

see https://godbolt.org/z/b98qTvKEe

```rust
mod intrinsics {
    extern "rust-intrinsic" {
        pub fn wrapping_add<T>(a: T, b: T) -> T;
        pub fn rotate_left<T>(a: T, b: T) -> T;
        pub fn rotate_right<T>(a: T, b: T) -> T;
        pub fn offset<T>(ptr: *const T, count: isize) -> *const T;
    }
}

mod mem {
    extern "rust-intrinsic" {
        fn transmute<T, U>(_: T) -> U;
        fn size_of<T>() -> usize;
    }
}

macro_rules! impl_uint {
    ($($ty:ident = $lang:literal),*) => {
        $(
            impl $ty {
                pub fn wrapping_add(self, rhs: Self) -> Self {
                    // intrinsics::wrapping_add(self, rhs)
                    self + rhs
                }

                pub fn rotate_left(self, n: u32) -> Self {
                    unsafe {
                        intrinsics::rotate_left(self, n as Self)
                    }
                }

                pub fn rotate_right(self, n: u32) -> Self {
                    unsafe {
                        intrinsics::rotate_right(self, n as Self)
                    }
                }

                pub fn to_le(self) -> Self {
                    #[cfg(target_endian = "little")]
                    {
                        self
                    }
                }

                pub const fn from_le_bytes(bytes: [u8; mem::size_of::<Self>()]) -> Self {
                    Self::from_le(Self::from_ne_bytes(bytes))
                }

                pub const fn from_le(x: Self) -> Self {
                    #[cfg(target_endian = "little")]
                    {
                        x
                    }
                }

                pub const fn from_ne_bytes(bytes: [u8; mem::size_of::<Self>()]) -> Self {
                    unsafe { mem::transmute(bytes) }
                }
            }
        )*
    }
}

impl_uint!(
    u8 = "u8",
    u16 = "u16",
    u32 = "u32",
    u64 = "u64",
    u128 = "u128",
    usize = "usize"
);
```

I expected to see this happen: compile without error

Instead, this happened: 

```
<source>: In function 'transmute<[u8:CAPACITY], u8>':
<source>:12:9: error: invalid types in nop conversion
   12 |         fn transmute<T, U>(_: T) -> U;
      |         ^
u8
const u8[1]
D.965 = (u8) _;
<source>:12:9: internal compiler error: 'verify_gimple' failed
0x216c8ee internal_error(char const*, ...)
	???:0
0x1276fb5 verify_gimple_in_seq(gimple*)
	???:0
0xf3b136 gimplify_body(tree_node*, bool)
	???:0
0xf3b2d1 gimplify_function_tree(tree_node*)
	???:0
0xd759d7 cgraph_node::analyze()
	???:0
0xd794c1 symbol_table::finalize_compilation_unit()
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Compiler returned: 1
```

### Meta

- What version of Rust GCC were you using, git sha if possible. 8809ee8c6a5621e830f3cfe66c381f986e63c7f2

### PR DESCRIPTION
**Pull request by philberty**
This changes the CONVERT_EXPR to use the same ```*(foo*)&bar``` style cast from
the c front-end to handle the case of:
```
  int a[1];
  int b = (int)a;
```
Which is converted into:
```
  int b = *(int*)&a;
```
which the constant folders can turn directly into int b = a[0];

Fixes #1432

### CODE REVIEW

File: gcc/rust/backend/rust-compile-intrinsic.cc [hunk 1]
```diff
@@ -545,8 +545,22 @@ transmute_intrinsic_handler (Context *ctx, TyTy::BaseType *fntype_tyty)
...
-				     result_type_tree, convert_me_expr);
+      // Return *(orig_type*)&decl.  */
+      // tree t = build_fold_addr_expr_loc (location.gcc_location (), this->t_);
+      // t = fold_build1_loc (location.gcc_location (), NOP_EXPR,
+      //       	       build_pointer_type (this->orig_type_), t);
+      // return build_fold_indirect_ref_loc (location.gcc_location (), t);
+
+      // result_expr = fold_build1_loc (Location ().gcc_location (),
+      // CONVERT_EXPR,
+      //   			     result_type_tree, convert_me_expr);
```
Comment (CohenArthur) [inline gcc/rust/backend/rust-compile-intrinsic.cc:556]: Dead code?

**Review by CohenArthur — COMMENTED** [review]
Looks nice, It's cool to see this working :D
