### PR TITLE
gccrs: Fix ICE in insert_associated_trait_impl due to recursion

### LINKED ISSUE #4166: ICE in insert_associated_trait_impl, at rust/typecheck/rust-typecheck-context.cc:255
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -frust-incomplete-and-experimental-compiler-do-not-use
pub trait Foo {}

pub struct FooImpl;

const foo_impl: () = {
    impl Foo for FooImpl {
        fn foo() {
            let () = foo_impl;
        }
    }
};

````

original:
````rust
pub trait Foo {
    type Bar;
    fn foo(bar: Self::bar);
}

pub struct FooImpl;

const foo_impl: () = {
    impl Foo for FooImpl {
        type Bar = ();

        fn foo(_bar: Self::Bar) {
            let () = foo_impl; // non-exhaustive pattern: `_` not covered reported here
        }
    }
};
````

Version information:

4db0cf74f64086e2bb2eff029c597239df8442e1

Possibly related line of code:
https://github.com/Rust-GCC/gccrs/blob/4db0cf74f64086e2bb2eff029c597239df8442e1/gcc/rust/typecheck/rust-typecheck-context.cc#L249-L261

Command:
`/home/matthias/vcs/github/gccrs/gccrs-build/gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use`

<details><summary><strong>Program output</strong></summary>
<p>

```
/tmp/icemaker_global_tempdir.J4KdGj8QZ6tS/rustc_testrunner_tmpdir_reporting.rY4R5JiGIHX4/mvce.rs:7:9: error: method ‘foo’ is not a member of trait ‘Foo’
    6 |     impl Foo for FooImpl {
      |          ~~~
    7 |         fn foo() {
      |         ^~
/tmp/icemaker_global_tempdir.J4KdGj8QZ6tS/rustc_testrunner_tmpdir_reporting.rY4R5JiGIHX4/mvce.rs:7:9: error: method ‘foo’ is not a member of trait ‘Foo’
    6 |     impl Foo for FooImpl {
      |          ~~~
    7 |         fn foo() {
      |         ^~
crab1: internal compiler error: in insert_associated_trait_impl, at rust/typecheck/rust-typecheck-context.cc:255
0x301e249 internal_error(char const*, ...)
	../../gcc/diagnostic-global-context.cc:786
0xc22881 fancy_abort(char const*, int, char const*)
	../../gcc/diagnostics/context.cc:1787
0x9091c3 Rust::Resolver::TypeCheckContext::insert_associated_trait_impl(unsigned int, Rust::Resolver::AssociatedImplTrait&&)
	../../gcc/rust/typecheck/rust-typecheck-context.cc:255
0x103f8e2 Rust::Resolver::TypeCheckItem::validate_trait_impl_block(Rust::Resolver::TraitReference*, Rust::HIR::ImplBlock&, Rust::TyTy::BaseType*, std::vector<Rust::TyTy::SubstitutionParamMapping, std::allocator<Rust::TyTy::SubstitutionParamMapping> >&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:855
0x1044bcd Rust::Resolver::TypeCheckItem::visit(Rust::HIR::ImplBlock&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:493
0x103a985 Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:57
0x1075c6b ???
	../../gcc/rust/typecheck/rust-hir-type-check-stmt.h:47
0x1076143 Rust::Resolver::TypeCheckStmt::Resolve(Rust::HIR::Stmt&)
	../../gcc/rust/typecheck/rust-hir-type-check-stmt.cc:34
0x1067904 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
	../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:614
0x1065f44 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr&)
	../../gcc/rust/typecheck/rust-hir-type-check-expr.cc:50
0x103a0b3 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::ConstantItem&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:448
0x103a985 Rust::Resolver::TypeCheckItem::Resolve(Rust::HIR::Item&)
	../../gcc/rust/typecheck/rust-hir-type-check-item.cc:57
0xfda37b Rust::Resolver::TypeResolution::Resolve(Rust::HIR::Crate&)
	../../gcc/rust/typecheck/rust-hir-type-check.cc:71
0xe8752c Rust::Session::compile_crate(char const*)
	../../gcc/rust/rust-session-manager.cc:682
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by Harishankar14**
This patch fixes an Internal Compiler Error (ICE) that occurred when handling recursive const blocks containing trait implementations. Previously, the compiler asserted that an associated trait implementation ID must not already exist in the context. However, recursive definitions could trigger a second visit to the same implementation, causing the assertion to fail.

We now check if the ID exists and return early if it does, allowing the compiler to handle the recursion gracefully and emit standard error messages instead of crashing.

Fixes #4166

gcc/rust/ChangeLog:

	* typecheck/rust-typecheck-context.cc (insert_associated_trait_impl): Remove assertion and add check for existing ID to prevent ICE.

gcc/testsuite/ChangeLog:

	* rust/compile/issue-4166.rs: New test.

Thank you for making Rust GCC better!

If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.

Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

### CODE REVIEW

File: gcc/rust/typecheck/rust-typecheck-context.cc [hunk 1]
```diff
@@ -252,8 +252,11 @@ void
 TypeCheckContext::insert_associated_trait_impl (
```
Comment (P-E-P) [inline gcc/rust/typecheck/rust-typecheck-context.cc:252]: I think we should rename that function to something like `try_insert_associated_trait_impl` to highlight that it may now fail. We could also return a bool or a tl::expected to signify whether the insertion has succeeded.

Comment (Harishankar14) [reply gcc/rust/typecheck/rust-typecheck-context.cc:252]: @P-E-P  yeah initially i did feel the same to change to bool. Wanted to know the feedback before.Will update it and request for a review

**Comment by Harishankar14** [comment]
@P-E-P  Done with the changes
