### PR TITLE
Parse variadic functions

### LINKED ISSUE #2664: Cannot parse variadic functions
Cannot parse variadic functions even if those are disabled.

I tried this code:

```rust
fn main() {}

#[cfg(FALSE)]
fn variadic(x: isize, ...) {}
```

I expected to see this happen: *explanation*

Instead, this happened: Failure on variadic ellipsis parsing.

```
./test.rs:4:23: error: unexpected token ‘...’ in pattern
    4 | fn variadic(x: isize, ...) {}
      |                       ^~~
./test.rs:4:23: error: failed to parse function param (in function params)
./test.rs:4:23: error: expecting ‘)’ but ‘...’ found
./test.rs:4:23: error: function declaration missing closing parentheses after parameter list
./test.rs:5:1: error: failed to parse item in crate
```

### Meta

- c7728c8020334fecb47789163ba94326aab6208c

### LINKED ISSUE #2700: Cannot parse named variadic on extern functions
Named variadics are not parsed correctly.

I tried this code:

```rust
extern "C" {
    fn variadic(x: isize, args: ...);
}

fn main() {}
```

I expected to see this happen: Compiles with a waning (unused function).

Instead, this happened:

Emit an error

```
./test.rs:2:33: error: unrecognised token ‘...’ in type
    2 |     fn variadic(x: isize, args: ...);
      |                                 ^~~
./test.rs:2:33: error: could not parse param type in extern block function declaration
./test.rs:2:27: error: could not parse named function parameter in external function
    2 |     fn variadic(x: isize, args: ...);
      |                           ^~~~
./test.rs:2:5: error: failed to parse external item despite not reaching end of extern block
    2 |     fn variadic(x: isize, args: ...);
      |     ^~
./test.rs:9:1: error: failed to parse item in crate
```

### Meta

- b3f02d9c8cb

### PR DESCRIPTION
**Pull request by P-E-P**
Parse variadic functions.

This version of the PR modifies the way variadic are stored in the ast. Variadic were previously handled at function level, but this makes the parser a bit ugly. This PR suggest keeping variadic informations as a special parameter instead. It requires a lot of work to reflect this change at all level of the compiler. Many passes consider the number of arguments without checking for variadicity, therefore, this PR creates a big pile of ICE as of [c6d9843](https://github.com/Rust-GCC/gccrs/pull/2701/commits/c6d984301f88b315137b61cb91a0053d5e3e0f46).

Alternative to #2704

Fixes #2664 
Fixes #2700

### CODE REVIEW

**Comment by P-E-P** [comment]
Although these changes pass the test, they are not entirely complete. We should error out when the variadic argument is incorrect. This should be handled in another PR.

Those bugs are described in issues #2711 and #2710

**Review by philberty — CHANGES_REQUESTED** [review]
In theory it should be possibe to add a hello world test here by adding a parameter name to the printf varadic function lets make sure that works and go for it

File: gcc/rust/expand/rust-expand-visitor.cc [hunk 1]
```diff
@@ -1264,12 +1264,13 @@ ExpandVisitor::visit (AST::ExternalFunctionItem &item)
   for (auto &param : item.get_generic_params ())
     visit (param);
 
-  // FIXME: Should this work? What is the difference between NamedFunctionParam
-  // and FunctionParam?
-  // expand_function_params (item.get_function_params ());
+  auto end = item.is_variadic () ? item.get_function_params ().end () - 1
```
Comment (philberty) [inline gcc/rust/expand/rust-expand-visitor.cc:1267]: This seems sus... are you trying to get the last argument?

File: gcc/rust/expand/rust-cfg-strip.cc [hunk 2]
```diff
@@ -2588,7 +2588,8 @@ CfgStrip::visit (AST::ExternalFunctionItem &item)
   /* strip function parameters if required - this is specifically
    * allowed by spec */
   auto &params = item.get_function_params ();
-  for (auto it = params.begin (); it != params.end ();)
+  auto end = item.is_variadic () ? params.end () - 1 : params.end ();
```
Comment (philberty) [inline gcc/rust/expand/rust-cfg-strip.cc:2591]: same here

File: gcc/rust/ast/rust-item.h [hunk 3]
```diff
@@ -570,7 +586,10 @@ class FunctionParam
   FunctionParam &operator= (FunctionParam &&other) = default;
 
   // Returns whether FunctionParam is in an invalid state.
-  bool is_error () const { return param_name == nullptr || type == nullptr; }
+  bool is_error () const
+  {
+    return (param_name == nullptr || type == nullptr) && !variadic;
```
Comment (philberty) [inline gcc/rust/ast/rust-item.h:591]: this is hard to read to me... I would have a if (varadic) { return error_condition } else param_name == nullptr || type ==nullptr

File: gcc/rust/expand/rust-expand-visitor.cc (hunk 1 above)
Comment (P-E-P) [reply gcc/rust/expand/rust-expand-visitor.cc:1267]: I'm trying to avoid the last argument in the for loop if the function is variadic because this argument has no type. I recognize it is not as easy to read as I would like but I haven't found a better way to express it.

Comment (P-E-P) [reply gcc/rust/expand/rust-expand-visitor.cc:1267]: Now that I've worked on #2713 I know that AST validation pass is done after the expansion dump. This means there may be some invalid variadic function as shown in issues #2710 and #2711 going in that loop whose type cannot be fetched. Instead of avoiding the last parameter when the function is variadic, we should check for the presence of a type in the loop.

**Review by CohenArthur — APPROVED** [review]
thank you! nice work :)

File: gcc/rust/parse/rust-parse-impl.h [hunk 4]
```diff
@@ -22,7 +22,9 @@
 /* DO NOT INCLUDE ANYWHERE - this is automatically included with rust-parse.h
  * This is also the reason why there are no include guards. */
 
+#include "rust-ast-full-decls.h"
 #include "rust-token.h"
+#include <vector>
```
[the remark this answers is not in the document]
Comment (P-E-P) [reply gcc/rust/parse/rust-parse-impl.h:27]: Yeah, I didn't catch this while reviewing my diff sorry. My editor has this new behavior that I need to disable.

File: gcc/rust/expand/rust-expand-visitor.cc (hunk 1 above)
Comment (P-E-P) [reply gcc/rust/expand/rust-expand-visitor.cc]: Rebased and fixed!

File: gcc/rust/expand/rust-cfg-strip.cc (hunk 2 above)
Comment (P-E-P) [reply gcc/rust/expand/rust-cfg-strip.cc]: Fixed!

File: gcc/rust/ast/rust-item.h (hunk 3 above)
Comment (P-E-P) [reply gcc/rust/ast/rust-item.h]: Fixed!

**Comment by P-E-P** [comment]
> In theory it should be possibe to add a hello world test here by adding a parameter name to the printf varadic function lets make sure that works and go for it

I did as you suggested, with two new tests in [171e3ae](https://github.com/Rust-GCC/gccrs/pull/2701/commits/171e3ae7071792d3907217a0ad26d02a594c67de), one execute with a printf as well as another test to ensure named variadic with a wildcard pattern are parsed correctly.

**Review by philberty — APPROVED** [review]
LGTM go for it
