### PR TITLE
lint: Fix ICE on error_mark_node in unused variable linter

### LINKED ISSUE #3910: ICE in check_decl, at rust/checks/lints/rust-lint-unused-var.cc:28
### Code

```rust
struct B<const M: u32> {}
impl<const M: u32> B<M> {
    const M: u32 = M;
}
```

### Version information

```
bc2a3e6
```

### Command

```
./gcc/crab1 ../test.rs -frust-debug -frust-dump-ast-pretty -Warray-bounds -dumpbase ../test.rs -mtune=generic -march=x86-64 -O0 -version -fdump-tree-gimple -o test.s -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -frust-incomplete-and-experimental-compiler-do-not-use
```

### Program output
```
crab1: internal compiler error: in check_decl, at rust/checks/lints/rust-lint-unused-var.cc:28
0x29abe86 internal_error(char const*, ...)
        ../../gccrs/gcc/diagnostic-global-context.cc:517
0xb48036 fancy_abort(char const*, int, char const*)
        ../../gccrs/gcc/diagnostic.cc:1803
0x919e8b check_decl
        ../../gccrs/gcc/rust/checks/lints/rust-lint-unused-var.cc:28
0xf62e6b Rust::Analysis::UnusedVariables::Lint(Rust::Compile::Context&)
        ../../gccrs/gcc/rust/checks/lints/rust-lint-unused-var.cc:93
0xca283c Rust::Session::compile_crate(char const*)
        ../../gccrs/gcc/rust/rust-session-manager.cc:739
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by Pasta-coder**
Fixes Rust-GCC#3910

### CODE REVIEW

File: gcc/rust/checks/lints/rust-lint-unused-var.cc [hunk 1]
```diff
@@ -25,6 +25,8 @@ namespace Analysis {
 static void
 check_decl (tree *t)
 {
+  if (*t == error_mark_node)
```
Comment (powerboat9) [inline gcc/rust/checks/lints/rust-lint-unused-var.cc]: I think this should be `t == error_mark_node`

Comment (powerboat9) [reply gcc/rust/checks/lints/rust-lint-unused-var.cc]: Actually, never mind, disregard

**Comment by philberty** [comment]
actually this is hiding a code gen bug it shouldnt merge this unless we understand why an error mark node has crept into the IR

**Comment by Pasta-coder** [comment]
Because `const` generics aren't fully lowered yet, compile_constant_item returns an `error_mark_node`. However, the backend blindly pushes this into the `context via ctx->insert_const_decl` inside `rust-compile-implitem.cc` and `rust-compile-item.cc` without checking if the compilation actually succeeded.

I will instead add an `if (const_expr != error_mark_node)` guard right before the `insert_const_decl calls` in the backend. I'll update the PR with this fix shortly!

**Review by philberty — APPROVED** [review]
LGTM

**Comment by Pasta-coder** [comment]
@P-E-P can we merge this ?

File: gcc/testsuite/rust/compile/issue-3910.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// { dg-options "-frust-incomplete-and-experimental-compiler-do-not-use" }
```
Comment (P-E-P) [inline gcc/testsuite/rust/compile/issue-3910.rs]: You don't need that additional option within the testsuite, IIRC the .exp file injects it anyway.

Comment (Pasta-coder) [reply gcc/testsuite/rust/compile/issue-3910.rs]: okay

**Comment by Pasta-coder** [comment]
cc @P-E-P

**Review by P-E-P — APPROVED** [review]
